{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper-jvm/1.5.0-SNAPSHOT/fhir-helper-jvm-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper-jvm",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sxnqzhxomnbi3behrjzbzlb4mu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-metadata-1.5.0-SNAPSHOT.jar",
          "size": 261,
          "sha512": "70d4fceb8483b638df5e95694148a390da793069e5ecf950456b9764089ca57751ee1d27d76b1071e3a84b352e8acadc231523d94f9237882ae3717ea974714c",
          "sha256": "64add7cc74020796a90a265628310d058344e33d5a9d0de2a62dbbac8f960c49",
          "sha1": "ef79c712b5dbaa03ff63097e873c83ab20e5d7c5",
          "md5": "6a05f7ca0d34875c1f5ba763a9163313"
        }
      ]
    }
  ]
}
