{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper-jvm/1.5.0-SNAPSHOT/fhir-helper-jvm-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper-jvm",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gndhex6c6rci5pvscc5m523zlq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-metadata-1.5.0-SNAPSHOT.jar",
          "size": 261,
          "sha512": "bc9aa619a56086d0f8b44baf147b530bae7a31fc1d6767251da01a31ee12d6dc77ac015d255b2ff0707e4b9b3ec108fb77ff5678262b1ed20d34869b01565fa3",
          "sha256": "eae266226ceae9f806bae17f5351bbf6b6bf5310472602010af2dc044152d513",
          "sha1": "cf2c777083ecc3e682ad66e60bb8840cd4b5b928",
          "md5": "3772b3916194f9e7f1c3b37e6c6e87df"
        }
      ]
    }
  ]
}
