{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lenvfmshubfgpfcwxttldlaas4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-SNAPSHOT.aar",
          "size": 61890,
          "sha512": "3ece44cd41c82c4b83b9d85dcbd47cd0bf1e7afcf0fe739c4e17b0e60fa924e0b7ab26d1d5b44f511fcbb6591ca3a50f787448442f0fdad8e5039877d47096bd",
          "sha256": "d3ca1186eb915409c0f0198e600752022ba5ea96b59091ceb38dce93a4bff22c",
          "sha1": "f47b674e40584f419f24ea7108b11c01802abf72",
          "md5": "a48353f46bdddf5d52b07fdbe71caad9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-SNAPSHOT.aar",
          "size": 61890,
          "sha512": "3ece44cd41c82c4b83b9d85dcbd47cd0bf1e7afcf0fe739c4e17b0e60fa924e0b7ab26d1d5b44f511fcbb6591ca3a50f787448442f0fdad8e5039877d47096bd",
          "sha256": "d3ca1186eb915409c0f0198e600752022ba5ea96b59091ceb38dce93a4bff22c",
          "sha1": "f47b674e40584f419f24ea7108b11c01802abf72",
          "md5": "a48353f46bdddf5d52b07fdbe71caad9"
        }
      ]
    }
  ]
}
