{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g4x2o3g47fflfm7puixnhoc67m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "d3af4b5af0f70cd47d645ecc03af78161707bfcce01dc3eeeda2e5e0f114e7e1aaef86f1b74fee3322bfad2c30507b21a851008eee99b941b6ed063734391db5",
          "sha256": "0b959fbd44625794b02173e9dcdb9deb66974993e91df08345f1920bd8c95e4a",
          "sha1": "0a70f3344514786396d5a91a67ae320e368108bb",
          "md5": "ee5c5831ac1f677085d25a6fcdaef458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "d3af4b5af0f70cd47d645ecc03af78161707bfcce01dc3eeeda2e5e0f114e7e1aaef86f1b74fee3322bfad2c30507b21a851008eee99b941b6ed063734391db5",
          "sha256": "0b959fbd44625794b02173e9dcdb9deb66974993e91df08345f1920bd8c95e4a",
          "sha1": "0a70f3344514786396d5a91a67ae320e368108bb",
          "md5": "ee5c5831ac1f677085d25a6fcdaef458"
        }
      ]
    }
  ]
}
