{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nzdlny3vq5gmbk5z5jgjueypsy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "c57a0f9b5a62c42943595c0f5e7d92fcc396c79ac331b897f44a1ddbb58df247fd7a2f0ccfbed27f509b8a1f175ed3d277908217fee79889155e1b5f483f4590",
          "sha256": "a56b9dbf41e2b366a8f336588be43219a2e2dbfe0ef8a9227eda2c6ebbee5546",
          "sha1": "77bdcd9da3e91388f619c072e0cf62a9d31ed2e6",
          "md5": "3b6eb461f4d7a9e5ce1b5de5b2adf3ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "c57a0f9b5a62c42943595c0f5e7d92fcc396c79ac331b897f44a1ddbb58df247fd7a2f0ccfbed27f509b8a1f175ed3d277908217fee79889155e1b5f483f4590",
          "sha256": "a56b9dbf41e2b366a8f336588be43219a2e2dbfe0ef8a9227eda2c6ebbee5546",
          "sha1": "77bdcd9da3e91388f619c072e0cf62a9d31ed2e6",
          "md5": "3b6eb461f4d7a9e5ce1b5de5b2adf3ef"
        }
      ]
    }
  ]
}
