{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "frww6tbtmngozdpq62odvmnrma"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "1bfe3da8eaa1269a5b200edab3b28aff0b142dbd978ee76b4c0a8d632ba8b471a0c419f5ff1fbd9c2f08ec470f0566d3feba2c52951f965a9ad6fe41bb078b0d",
          "sha256": "e33a97e395bc346bdcc39ccc26c32729114bd3f2485e04aae222c82534da31f3",
          "sha1": "7e695f633d0b0274993a0fdd6de6a5bd46a72e1d",
          "md5": "62a08d574bd7af0bfb57016368ad04f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "1bfe3da8eaa1269a5b200edab3b28aff0b142dbd978ee76b4c0a8d632ba8b471a0c419f5ff1fbd9c2f08ec470f0566d3feba2c52951f965a9ad6fe41bb078b0d",
          "sha256": "e33a97e395bc346bdcc39ccc26c32729114bd3f2485e04aae222c82534da31f3",
          "sha1": "7e695f633d0b0274993a0fdd6de6a5bd46a72e1d",
          "md5": "62a08d574bd7af0bfb57016368ad04f5"
        }
      ]
    }
  ]
}
