{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-SNAPSHOT/util-ktor-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hyncfjmu6zeuxl3ohgu2ifc2m4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "cbb05d45af0cf10c8f5a01afe26237aea0a5bc17321ec07114a31705445d24c191e5ac5f9a4c21cf0cc742609243b215dda441562e74fbb81463e2395c5f3595",
          "sha256": "c32a6c7d0a4a72140f3dcc2bb1b44bd7d17a4f3147dce43a803a508c720faac6",
          "sha1": "9219f396179c00dfadce417c1785045952f4d414",
          "md5": "8221211ba42b2d7ad87245232ca87e8e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "cbb05d45af0cf10c8f5a01afe26237aea0a5bc17321ec07114a31705445d24c191e5ac5f9a4c21cf0cc742609243b215dda441562e74fbb81463e2395c5f3595",
          "sha256": "c32a6c7d0a4a72140f3dcc2bb1b44bd7d17a4f3147dce43a803a508c720faac6",
          "sha1": "9219f396179c00dfadce417c1785045952f4d414",
          "md5": "8221211ba42b2d7ad87245232ca87e8e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-SNAPSHOT/util-ktor-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
