{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-SNAPSHOT/util-ktor-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "esrb7lawqzfnpgnbkhf22vkz64"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "228878cf19282cf0e99e3d275deaa2fbef3af864a9279efd2c097b59a7bb7b25932c349f289fe701d2dfaf60d8a55e0665f82edd5b295ba7f643caf945cdfb53",
          "sha256": "9521b12f46a8e7da35cbbcc2912f605163277ee8ffb21247c006a6c9b1eaf2a7",
          "sha1": "17d5c77917fdddbd98da69f210b55315ead96b26",
          "md5": "d9e62ef9b89de50d32f3f076c9b77c39"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "228878cf19282cf0e99e3d275deaa2fbef3af864a9279efd2c097b59a7bb7b25932c349f289fe701d2dfaf60d8a55e0665f82edd5b295ba7f643caf945cdfb53",
          "sha256": "9521b12f46a8e7da35cbbcc2912f605163277ee8ffb21247c006a6c9b1eaf2a7",
          "sha1": "17d5c77917fdddbd98da69f210b55315ead96b26",
          "md5": "d9e62ef9b89de50d32f3f076c9b77c39"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-SNAPSHOT/util-ktor-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
