{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-SNAPSHOT/util-ktor-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2vy4lgcowjffdf4rz5cbiomaxy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "0e94248e63e530b92527f69e1e738377436545f08c13401c9ab61bc9c3c3dc38e567df6ce14421ff913a06f68fc27ef6e6e73eaad7c63471a38cdd4f11a176f2",
          "sha256": "418875565627ebb9ae1d4e609e71d33feeac06d57f9c5a3a6763a9dbde50b4a0",
          "sha1": "410a723bb54e21e2c7ea2ca1a5ecc51b20f939e3",
          "md5": "fcb4639da1637dcecf77ef1971a0a9ea"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "0e94248e63e530b92527f69e1e738377436545f08c13401c9ab61bc9c3c3dc38e567df6ce14421ff913a06f68fc27ef6e6e73eaad7c63471a38cdd4f11a176f2",
          "sha256": "418875565627ebb9ae1d4e609e71d33feeac06d57f9c5a3a6763a9dbde50b4a0",
          "sha1": "410a723bb54e21e2c7ea2ca1a5ecc51b20f939e3",
          "md5": "fcb4639da1637dcecf77ef1971a0a9ea"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-SNAPSHOT/util-ktor-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
