{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0-SNAPSHOT/util-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-release.aar",
          "url": "util-android-1.13.0-SNAPSHOT.aar",
          "size": 14484,
          "sha512": "8c17dca8e80571c47731a30a6395a2d74b9fb9af208c107bccd739a6cc6801e3681f873452e314884b80ecee3973a381408a48c232fbf4c504b5cfb3a0627c6c",
          "sha256": "d71ed2be7cddd3f882f5fb6def28ce993bc7066b0f6a0120a2966c4216ee7ea8",
          "sha1": "a54080b2d0ee09c591a1c61914141ee3d52b042d",
          "md5": "c4896e47869207a98d2df1bb68b14171"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "util-release.aar",
          "url": "util-android-1.13.0-SNAPSHOT.aar",
          "size": 14484,
          "sha512": "8c17dca8e80571c47731a30a6395a2d74b9fb9af208c107bccd739a6cc6801e3681f873452e314884b80ecee3973a381408a48c232fbf4c504b5cfb3a0627c6c",
          "sha256": "d71ed2be7cddd3f882f5fb6def28ce993bc7066b0f6a0120a2966c4216ee7ea8",
          "sha1": "a54080b2d0ee09c591a1c61914141ee3d52b042d",
          "md5": "c4896e47869207a98d2df1bb68b14171"
        }
      ]
    }
  ]
}
