{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5v43hn77trafjll76efllknfsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.4.0-SNAPSHOT.jar",
          "url": "fhir-java-1.4.0-SNAPSHOT.jar",
          "size": 987574,
          "sha512": "7672fa3a270be6a740f8cde0b7a8741e6a60c87e8af2dffea0aadbe9733a996dc5b5445481514cf4416012fd8e502f5e2fa7f66a834db0cadb2859be73542a9d",
          "sha256": "f3f61170e5e149da4f2f8f2adda9738541d168f796e29cd114daadc5c8808a1d",
          "sha1": "62074181f55cbd6cdbb6545818ffec1419511865",
          "md5": "ab7be98b38b08dcb74fd2f6740aa2dbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.4.0-SNAPSHOT.jar",
          "url": "fhir-java-1.4.0-SNAPSHOT.jar",
          "size": 987574,
          "sha512": "7672fa3a270be6a740f8cde0b7a8741e6a60c87e8af2dffea0aadbe9733a996dc5b5445481514cf4416012fd8e502f5e2fa7f66a834db0cadb2859be73542a9d",
          "sha256": "f3f61170e5e149da4f2f8f2adda9738541d168f796e29cd114daadc5c8808a1d",
          "sha1": "62074181f55cbd6cdbb6545818ffec1419511865",
          "md5": "ab7be98b38b08dcb74fd2f6740aa2dbb"
        }
      ]
    }
  ]
}
