{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/91f5616/crypto-91f5616.module",
    "group": "care.data4life.hc-crypto-kmp",
    "module": "crypto",
    "version": "91f5616",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "vyvng5utczgy7p5escs4xhono4"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-debug.aar",
          "url": "crypto-android-debug-91f5616.aar",
          "size": 62538,
          "sha512": "868bf2c3839231867a286146bbce8e57eec41755b3472a77606bf3cd95dc03cce0ee301fcdb861436f18388c35fc70be5bde26196cb5132124bae0aa03a3fda0",
          "sha256": "db4179458d7476c677cea41fce8548034dd41757dc1789d2ca52b7cb60050746",
          "sha1": "68f9c746e03bc3729859dfae52e7218488356e17",
          "md5": "9b7c1913a82a892183c61d1d5d63673d"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-debug.aar",
          "url": "crypto-android-debug-91f5616.aar",
          "size": 62538,
          "sha512": "868bf2c3839231867a286146bbce8e57eec41755b3472a77606bf3cd95dc03cce0ee301fcdb861436f18388c35fc70be5bde26196cb5132124bae0aa03a3fda0",
          "sha256": "db4179458d7476c677cea41fce8548034dd41757dc1789d2ca52b7cb60050746",
          "sha1": "68f9c746e03bc3729859dfae52e7218488356e17",
          "md5": "9b7c1913a82a892183c61d1d5d63673d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/91f5616/crypto-metadata-91f5616.module",
        "group": "care.data4life.hc-crypto-kmp",
        "module": "crypto-metadata",
        "version": "91f5616"
      }
    }
  ]
}
