{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine-jvm/0.2.0-SNAPSHOT/test-util-coroutine-jvm-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine-jvm",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "qc2efozchbfeviccdtqghgnk2i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-metadata-0.2.0-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "991073c4118e4635a87c787dcd118cbbfcb18c4669bcabdd9d63026697d69812993f52656eab268d11d00bec94083a738e42ffdad17ef0bebe646cdda92fc31b",
          "sha256": "4c60cefc13fc9662c4109f3e004a0093bc57e3c04e79198130ffadd9ccfd11b1",
          "sha1": "a5bb2af06a4beb3dc33fc49131d53817ae545e4f",
          "md5": "8ffc8085ba190c5b91c016f59e9f0136"
        }
      ]
    }
  ]
}
