{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.13.2/auth-1.13.2.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "vdxti2yu6bcl7jd7234bn6a3ei"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "auth-release.aar",
          "url": "auth-android-1.13.2.aar",
          "size": 45321,
          "sha512": "769db83d76699b3ccbfe47a4ac7654335d8fc7449f16c20ccc3d3a7234ddafb41d29a1433451e60c1cd61d0c0cc4638ee56c9114846ef4f99fa076372bd44026",
          "sha256": "4c8966f2417d8a6cd28eaf3c0ba7d64b3216f909f20938e2ac0d26e80c3a684b",
          "sha1": "b670739363f5987b395ab0970f9dcb059bfc6955",
          "md5": "25b0dff4f5d0669cdc1294de59c2d597"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "auth-release.aar",
          "url": "auth-android-1.13.2.aar",
          "size": 45321,
          "sha512": "769db83d76699b3ccbfe47a4ac7654335d8fc7449f16c20ccc3d3a7234ddafb41d29a1433451e60c1cd61d0c0cc4638ee56c9114846ef4f99fa076372bd44026",
          "sha256": "4c8966f2417d8a6cd28eaf3c0ba7d64b3216f909f20938e2ac0d26e80c3a684b",
          "sha1": "b670739363f5987b395ab0970f9dcb059bfc6955",
          "md5": "25b0dff4f5d0669cdc1294de59c2d597"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../auth-metadata/1.13.2/auth-metadata-1.13.2.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-metadata",
        "version": "1.13.2"
      }
    }
  ]
}
