{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.2.0-SNAPSHOT/fhir-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.2.0-SNAPSHOT.aar",
          "size": 14950578,
          "sha512": "9b17b7566e978753c9455f8cf584777720093f53ae77a164d94511852276c34c9805f75f3441eb393e77ed7d5fc0cb96f1f60a95bcc2c08e64b3d25d88063b2b",
          "sha256": "da743777cb398a212a6c6dc348e29c482d689ef7706e2ed896e57099d0e380dd",
          "sha1": "315c58463932d60e5a0b217d82c1601360134c1d",
          "md5": "ceca098f30aafb13ca393fb101d91c77"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.2.0-SNAPSHOT.aar",
          "size": 14950578,
          "sha512": "9b17b7566e978753c9455f8cf584777720093f53ae77a164d94511852276c34c9805f75f3441eb393e77ed7d5fc0cb96f1f60a95bcc2c08e64b3d25d88063b2b",
          "sha256": "da743777cb398a212a6c6dc348e29c482d689ef7706e2ed896e57099d0e380dd",
          "sha1": "315c58463932d60e5a0b217d82c1601360134c1d",
          "md5": "ceca098f30aafb13ca393fb101d91c77"
        }
      ]
    }
  ]
}
