{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.2.0-SNAPSHOT/fhir-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosx64-0.2.0-SNAPSHOT.klib",
          "size": 9800351,
          "sha512": "4f94a663b09ef4daed655f0b8595e7fd762acd8316dcaaec180baab64e8041f7082bd93f375b9a8ba12acfd4f3147d2ad4575f5924e9c9a1a17990130763eeb8",
          "sha256": "da47534227307391143270136528896d07ba6f728ced560211e223d52d40e6d6",
          "sha1": "09b8040412ffefa7491227eca32d3b30589d5730",
          "md5": "3eb5a4666ee64d58c0babfeb309b4526"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-iosx64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "fhir-iosx64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ae6ed72a1ff72cf27603f31904a0d95aca52cf4ed19d49c8e394359a100431c6c2c0512ff077516f89b69233073fc3178a01e633a0eb93f33480edb95dd7fa1f",
          "sha256": "6e85c1a6b16327da5fc8367df4f6e328daf3bf08ae3beed236e9c01a879b3d84",
          "sha1": "0711a5ada5ceecda476f7c28e61dabf630229103",
          "md5": "fb2fed92c03871ef22d5cd7005436902"
        }
      ]
    }
  ]
}
