{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-SNAPSHOT/util-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5iasa5iuhjg7bela42sx2nlvzi"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.7.0-SNAPSHOT.klib",
          "size": 22832,
          "sha512": "7b27f1906c43d35e15593d24263000b13c22b380702f78014b54fd3e075a41703d1fa1f8a2a8f9195f5113e18b002413661f3eafb30cac2aa578f3e301ea27e3",
          "sha256": "b36b1ca01957f3601f10e1b0eb96ffd91b9545b7304d4609d282353165617274",
          "sha1": "a3fde26c1a8f485e622b891faadbc6ea1958a68a",
          "md5": "cf40a7d792a9cdda0ae391ebb734fd0b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-SNAPSHOT/util-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
