{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper-jvm/1.6.0-SNAPSHOT/fhir-helper-jvm-1.6.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper-jvm",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "x3qntpbatbejzhgfqoucstgame"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.6.0-SNAPSHOT.jar",
          "url": "fhir-helper-metadata-1.6.0-SNAPSHOT.jar",
          "size": 261,
          "sha512": "21588cffaa751ed4e9a9e02f8308cf76153601f9d691cfd261292620f28285484c7f64aaee674c828bca00b958953d1418bf07137d12a43e07510b5536b38172",
          "sha256": "0cfc056a68b628efa7553e8633d67d59d471703683c00e1d916cc1d1b8d2863c",
          "sha1": "ae45a40d0873003c7004a7229230fce93853def2",
          "md5": "d03a0bf03745c6e8f3a2b6240c86875d"
        }
      ]
    }
  ]
}
