{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.14.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "securestore-metadata-1.14.0-SNAPSHOT.jar",
          "url": "securestore-1.14.0-SNAPSHOT.jar",
          "size": 7274,
          "sha512": "1e037d838b95eaa1d9cdec929000bb4bcb3990c9f0427f2a99ec2f1bc9c21626382edc50e70cc5157774b1f7bc2a282697647cef70b4e12624e60e72e81c94fb",
          "sha256": "980bdf70cbe553527be372867afeb175e0af1eeaa399c3ab34703badf27fc039",
          "sha1": "3f8b9ae87f2489c14dd5898bce8f3544ae5e5d11",
          "md5": "576492d84a0dd2c18185089b34816618"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.14.0-SNAPSHOT/securestore-android-debug-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.14.0-SNAPSHOT/securestore-android-debug-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.14.0-SNAPSHOT/securestore-android-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.14.0-SNAPSHOT/securestore-android-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.14.0-SNAPSHOT/securestore-jvm-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.14.0-SNAPSHOT/securestore-jvm-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.14.0-SNAPSHOT"
      }
    }
  ]
}
