{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cdfwhwvegvgfnmhtly3plx3hyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1d150717c474986d13bb16c5ffeec50759cef37424bb362cbc19545dfff21b854d4adb1ff453c2d96a3ebd4ec91a66e05b32553a59708f6d4cb58ad9e2eb4d4f",
          "sha256": "f27792de238e803c8aa7667fa669366dc11ebd68810f72a5b4fbcc895f300a6a",
          "sha1": "6bdceeac7d230600a4aa5147853aeee10aac24c6",
          "md5": "09dcb598d5fdc960d45ffec7fd245d48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1d150717c474986d13bb16c5ffeec50759cef37424bb362cbc19545dfff21b854d4adb1ff453c2d96a3ebd4ec91a66e05b32553a59708f6d4cb58ad9e2eb4d4f",
          "sha256": "f27792de238e803c8aa7667fa669366dc11ebd68810f72a5b4fbcc895f300a6a",
          "sha1": "6bdceeac7d230600a4aa5147853aeee10aac24c6",
          "md5": "09dcb598d5fdc960d45ffec7fd245d48"
        }
      ]
    }
  ]
}
