{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6td4tx6r4vgjnizjuoyabpxdke"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "32255e20b1ad5990d059563276906f2a9cdf8f60c607ab4ee65dac5975de29e1f0399f60bef1b2ca082058789add5a3c1708e52246ae96bbc6f8dbbd66ca44db",
          "sha256": "5864f59c26343fafa3dc7a7949a16e54a1c060f8d207728e434a027855e84563",
          "sha1": "4802272a3a94f08d1e133f771abe8f7e8525c20d",
          "md5": "761f54aab761a1c4d4edc2e98fac23c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "32255e20b1ad5990d059563276906f2a9cdf8f60c607ab4ee65dac5975de29e1f0399f60bef1b2ca082058789add5a3c1708e52246ae96bbc6f8dbbd66ca44db",
          "sha256": "5864f59c26343fafa3dc7a7949a16e54a1c060f8d207728e434a027855e84563",
          "sha1": "4802272a3a94f08d1e133f771abe8f7e8525c20d",
          "md5": "761f54aab761a1c4d4edc2e98fac23c9"
        }
      ]
    }
  ]
}
