{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.12.0-SNAPSHOT/util-1.12.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.12.0-SNAPSHOT.jar",
          "url": "util-jvm-1.12.0-SNAPSHOT.jar",
          "size": 15532,
          "sha512": "d48d703b3de8d8f9c22f70a4e0525eb9f9b6393912b2673b97a9bb8e8786f81511408e522469644a4ce08f9d595d93484c5fa959d9508014449e3ef30bc09a25",
          "sha256": "cb407675e95733ca28748aa4ee23bf865e8947306bea0be04d4d6382bae5104d",
          "sha1": "3e0d417a6450ad3c71cc57a00767f683c2d0c09b",
          "md5": "0990abbf4e7ab1cf24ad2328663d71c7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.12.0-SNAPSHOT.jar",
          "url": "util-jvm-1.12.0-SNAPSHOT.jar",
          "size": 15532,
          "sha512": "d48d703b3de8d8f9c22f70a4e0525eb9f9b6393912b2673b97a9bb8e8786f81511408e522469644a4ce08f9d595d93484c5fa959d9508014449e3ef30bc09a25",
          "sha256": "cb407675e95733ca28748aa4ee23bf865e8947306bea0be04d4d6382bae5104d",
          "sha1": "3e0d417a6450ad3c71cc57a00767f683c2d0c09b",
          "md5": "0990abbf4e7ab1cf24ad2328663d71c7"
        }
      ]
    }
  ]
}
