{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "2977192",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "l2dfpflk7bgankgfihmc46sw24"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-2977192.jar",
          "url": "test-util-ktor-2977192.jar",
          "size": 3186,
          "sha512": "482126ddf681462178d07b2c5fc7897017897e58d2c0145762eaae93ede8663373bef5dbe6da51ca5a6f11c8f97afc41fe3ea93d0211b9e8ea4e6595785846c6",
          "sha256": "cd7dc5869f8a0b37221aef5e0336f63b641a7daa5fef443c803ffaa3d4731ca6",
          "sha1": "1c0b46ae9c31c8eedf168ccceb8b9a9140c05969",
          "md5": "531e80e6b62f9f2d674a40eff6407acf"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/2977192/test-util-ktor-android-debug-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "2977192"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/2977192/test-util-ktor-android-debug-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "2977192"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/2977192/test-util-ktor-android-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "2977192"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/2977192/test-util-ktor-android-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "2977192"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosarm64/2977192/test-util-ktor-iosarm64-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosarm64",
        "version": "2977192"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosx64/2977192/test-util-ktor-iosx64-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosx64",
        "version": "2977192"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/2977192/test-util-ktor-jvm-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "2977192"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/2977192/test-util-ktor-jvm-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "2977192"
      }
    }
  ]
}
