{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.14.0-SNAPSHOT/auth-1.14.0-SNAPSHOT.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.14.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "auth-debug.aar",
          "url": "auth-android-debug-1.14.0-SNAPSHOT.aar",
          "size": 50272,
          "sha512": "48ffcd35b740b4952b53113ca93b3f07e14250f21d8421e965849e435c32d5b197025547e6ba63e8a53ae700783d436b69e916d61d6312dbc40fcb4025e2c8c5",
          "sha256": "b948734bb2fd59b7dd783ea560a3aa3084d977c0fdd32c60eddcebb88eeadeab",
          "sha1": "68182c6c429e7cdb7d49e4f1b9e74a7cf4766541",
          "md5": "b05d7cfcfdc832232d9b5ac3d50716c9"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "net.openid",
          "module": "appauth",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-debug.aar",
          "url": "auth-android-debug-1.14.0-SNAPSHOT.aar",
          "size": 50272,
          "sha512": "48ffcd35b740b4952b53113ca93b3f07e14250f21d8421e965849e435c32d5b197025547e6ba63e8a53ae700783d436b69e916d61d6312dbc40fcb4025e2c8c5",
          "sha256": "b948734bb2fd59b7dd783ea560a3aa3084d977c0fdd32c60eddcebb88eeadeab",
          "sha1": "68182c6c429e7cdb7d49e4f1b9e74a7cf4766541",
          "md5": "b05d7cfcfdc832232d9b5ac3d50716c9"
        }
      ]
    }
  ]
}
