{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.13.0-SNAPSHOT/error-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "error-jvm-1.13.0-SNAPSHOT.jar",
          "url": "error-jvm-1.13.0-SNAPSHOT.jar",
          "size": 3259,
          "sha512": "e510f498a86e0cd4337d14f14568eab8062d2579e2a41cf332151f1303cbdb8fd2f02320c831dcdc5ec2844b37810407a63db2367a741097853aefd9a8e594d5",
          "sha256": "f00ef5db840d7aed870738c6eb752a20525922b710115ebcf9d2cbc7554c7398",
          "sha1": "5e2aa45b03d5404d7d5eb580ce07aa18c428f652",
          "md5": "ada970fdc6337a1934ee1e55065857da"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-jvm-1.13.0-SNAPSHOT.jar",
          "url": "error-jvm-1.13.0-SNAPSHOT.jar",
          "size": 3259,
          "sha512": "e510f498a86e0cd4337d14f14568eab8062d2579e2a41cf332151f1303cbdb8fd2f02320c831dcdc5ec2844b37810407a63db2367a741097853aefd9a8e594d5",
          "sha256": "f00ef5db840d7aed870738c6eb752a20525922b710115ebcf9d2cbc7554c7398",
          "sha1": "5e2aa45b03d5404d7d5eb580ce07aa18c428f652",
          "md5": "ada970fdc6337a1934ee1e55065857da"
        }
      ]
    }
  ]
}
