{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bm5rghhf3jhsjoc52gph46k66a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.1-SNAPSHOT.jar",
          "url": "crypto-common-1.13.1-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7f20af81710f38891ef9d14c0165993e56d5a8632392abcf47c613bc6362d66b141bf64df549297537e851ec01237196333749b12fad605d617cd87d6e5e5dac",
          "sha256": "432c2ad3ed6551b0ace4430a81c4638151461b1bc40c7414b0daaeacd17b19ac",
          "sha1": "ec3ded8bc1fcf17b99cb964cd9aa1c900152bdc7",
          "md5": "1ab900cfd379f1599a25e97fba5cf696"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.1-SNAPSHOT.jar",
          "url": "crypto-common-1.13.1-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7f20af81710f38891ef9d14c0165993e56d5a8632392abcf47c613bc6362d66b141bf64df549297537e851ec01237196333749b12fad605d617cd87d6e5e5dac",
          "sha256": "432c2ad3ed6551b0ace4430a81c4638151461b1bc40c7414b0daaeacd17b19ac",
          "sha1": "ec3ded8bc1fcf17b99cb964cd9aa1c900152bdc7",
          "md5": "1ab900cfd379f1599a25e97fba5cf696"
        }
      ]
    }
  ]
}
