{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ex6wcqgazjfklhprdf67prhaoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.1-SNAPSHOT.jar",
          "url": "crypto-common-1.13.1-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "75b1f181180611627ef5f6ba9bf06afad2265d4dfdcbb99d2e1c8b3a252845c835f608d7213cb1653e4b12f94b41540cafe288ae0898b4bfcc330abfc0b71eec",
          "sha256": "ce1d97fea5bc69e39fb1e67e9030f6cb355328409cc2ea5d617ade658dd3108e",
          "sha1": "565e726312c5f0a0a406987387c4ea03a987082d",
          "md5": "beffbe4f0fff5667305162b63005632e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.1-SNAPSHOT.jar",
          "url": "crypto-common-1.13.1-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "75b1f181180611627ef5f6ba9bf06afad2265d4dfdcbb99d2e1c8b3a252845c835f608d7213cb1653e4b12f94b41540cafe288ae0898b4bfcc330abfc0b71eec",
          "sha256": "ce1d97fea5bc69e39fb1e67e9030f6cb355328409cc2ea5d617ade658dd3108e",
          "sha1": "565e726312c5f0a0a406987387c4ea03a987082d",
          "md5": "beffbe4f0fff5667305162b63005632e"
        }
      ]
    }
  ]
}
