{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "vyvxvbs5ljdwfckcf3iszub6xy"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "coroutine-util-release.aar",
          "url": "coroutine-util-android-0.1.0-SNAPSHOT.aar",
          "size": 5249,
          "sha512": "983ed0bbf05ef51ebdd65e5aab28df4759b62bdaefbc5a863d675a9066720e131f03293853ba221e735378b5e983f73b5b3cb4ff717e85d505234bcc8e33f383",
          "sha256": "a34e9ac0c799e999befbdb276e5c5843f36115a003ea4673580a243153961581",
          "sha1": "d50ebed0ad3175a5c94555652488c1b7f870a217",
          "md5": "3a17d3f4ac8a3e494cdb734a324b61fb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-release.aar",
          "url": "coroutine-util-android-0.1.0-SNAPSHOT.aar",
          "size": 5249,
          "sha512": "983ed0bbf05ef51ebdd65e5aab28df4759b62bdaefbc5a863d675a9066720e131f03293853ba221e735378b5e983f73b5b3cb4ff717e85d505234bcc8e33f383",
          "sha256": "a34e9ac0c799e999befbdb276e5c5843f36115a003ea4673580a243153961581",
          "sha1": "d50ebed0ad3175a5c94555652488c1b7f870a217",
          "md5": "3a17d3f4ac8a3e494cdb734a324b61fb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
