{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n2g3z3c4ejfnpmwgn7cyvo5rmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "73776e9b83f735a62ba152e963c6a2d014fb25baa5abd8a364b6ca2afaaae08038dfadaaf011b3f88d7c58ab7a7b15b4bdd14a830a6dcc41dc2f11ef5b040dae",
          "sha256": "78260b71e095ecbb76781649bd048c25db9ad7215f08941b100b6b01d190b5b7",
          "sha1": "a5066719303e74e22dbf48761eb68206f361ba56",
          "md5": "21f2c6dceeb529ad9efd4f69a0e2a319"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "73776e9b83f735a62ba152e963c6a2d014fb25baa5abd8a364b6ca2afaaae08038dfadaaf011b3f88d7c58ab7a7b15b4bdd14a830a6dcc41dc2f11ef5b040dae",
          "sha256": "78260b71e095ecbb76781649bd048c25db9ad7215f08941b100b6b01d190b5b7",
          "sha1": "a5066719303e74e22dbf48761eb68206f361ba56",
          "md5": "21f2c6dceeb529ad9efd4f69a0e2a319"
        }
      ]
    }
  ]
}
