{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ki5rrqvevg35gxnl4d7fcljl4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "58fac1d4fa62a65935752a42ee95a35358e85d75d50fe2a273053cae04fabb65072dd6b9057313e84eb473333b95eab4cfb5c1653950f36aff565e3256bd6fbb",
          "sha256": "4d60eb381812c9647f784bb8a09c34c1824afaa9006eb5c5f6ac94cacc50616a",
          "sha1": "7492661795baf5e2f083809d77a8ccea86a6193d",
          "md5": "d15825bb8705719138d66ab82d69c5ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "58fac1d4fa62a65935752a42ee95a35358e85d75d50fe2a273053cae04fabb65072dd6b9057313e84eb473333b95eab4cfb5c1653950f36aff565e3256bd6fbb",
          "sha256": "4d60eb381812c9647f784bb8a09c34c1824afaa9006eb5c5f6ac94cacc50616a",
          "sha1": "7492661795baf5e2f083809d77a8ccea86a6193d",
          "md5": "d15825bb8705719138d66ab82d69c5ae"
        }
      ]
    }
  ]
}
