{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hi6ofeo65fdubak2f6hbnlywha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1ab55759afe3c5884d9e61f315163dd9bb5838647597cfe45869872662723e5b2da142a4c773990ec1d456b8d643545cd3f88d91d16d712ee7fb8fd23936c3b5",
          "sha256": "28597778ab7e6d8da62e69c24418d0447b8c783ab0e3a06e200c3d1273991bfc",
          "sha1": "57cc2cfe199443862eac974dc70ae8add02cb4b5",
          "md5": "ba0db2e4ef19d8a39b741701a38ff981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1ab55759afe3c5884d9e61f315163dd9bb5838647597cfe45869872662723e5b2da142a4c773990ec1d456b8d643545cd3f88d91d16d712ee7fb8fd23936c3b5",
          "sha256": "28597778ab7e6d8da62e69c24418d0447b8c783ab0e3a06e200c3d1273991bfc",
          "sha1": "57cc2cfe199443862eac974dc70ae8add02cb4b5",
          "md5": "ba0db2e4ef19d8a39b741701a38ff981"
        }
      ]
    }
  ]
}
