{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "iqkv7nodajdefi77rmcs7jjt2i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "e2c5764b6f991d6f9484e61fde9b360741edd22c25bea4e4860fdb5b38a783a6a7f75db05b1bdfe0be336c38daf312ca2f80c74a4658e32aaafb0d030e94ab97",
          "sha256": "24ed657270087d3ff615587a2eea2c27ba269e50037e2d309fae23ba8b8c3df4",
          "sha1": "fa183fae7dd56850eae5d408d80c231f3c7570b1",
          "md5": "a090d01d6e2b8157a1945453ed78eb13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "e2c5764b6f991d6f9484e61fde9b360741edd22c25bea4e4860fdb5b38a783a6a7f75db05b1bdfe0be336c38daf312ca2f80c74a4658e32aaafb0d030e94ab97",
          "sha256": "24ed657270087d3ff615587a2eea2c27ba269e50037e2d309fae23ba8b8c3df4",
          "sha1": "fa183fae7dd56850eae5d408d80c231f3c7570b1",
          "md5": "a090d01d6e2b8157a1945453ed78eb13"
        }
      ]
    }
  ]
}
