{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m2pydfawtvgrhdpvxqkou5byxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "bdda68c0ecbc7a485f95771af61c27fbb3b52d53df8b92657494b7abbd85b6a878d9c725c403a4f3b2cf37b1e335a7cb7ab4f78a3d8b857914dd236bd7969985",
          "sha256": "73a6f8b7b6059156a2ca9bb193564679bed074c8d0d2fb2335c06b845e3c1071",
          "sha1": "c5a525e3e1f82f7cba3959aae156583524e0b872",
          "md5": "f67d25f61c3eab195a1fb50dd05be584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "bdda68c0ecbc7a485f95771af61c27fbb3b52d53df8b92657494b7abbd85b6a878d9c725c403a4f3b2cf37b1e335a7cb7ab4f78a3d8b857914dd236bd7969985",
          "sha256": "73a6f8b7b6059156a2ca9bb193564679bed074c8d0d2fb2335c06b845e3c1071",
          "sha1": "c5a525e3e1f82f7cba3959aae156583524e0b872",
          "md5": "f67d25f61c3eab195a1fb50dd05be584"
        }
      ]
    }
  ]
}
