{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.4.0-SNAPSHOT/test-util-coroutine-0.4.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT.klib",
          "size": 8255,
          "sha512": "f231a1f9d018cded691e9bc8fe2521645760430f5aa993d9207391980986637f28adab29c89d8da5afb78377792340be6fa9d28449b29506be13a41779c68d51",
          "sha256": "14a68739caebb5636199d693141b4d0050742a0023c54578d28356560ccaada2",
          "sha1": "1a7a1215637d716351a81897a5ca3671a5100035",
          "md5": "e99f25ac6e60ef2276590ac6a573bc0c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "2d01929aeb54869bea43581eed6b14bd7530e31f97289a8ec60131a62804113c2dea2eea5ede469d293369164d55e103345862170e44b2d53b11622e7406bbf9",
          "sha256": "ff77c7ab294f2bdf48934240dfabbdab41025b151edc0a5d75b1e4640eebb7fb",
          "sha1": "82a9dad852c22c0439585a887a6368cc48c8610c",
          "md5": "025ba3215d4e9cbec271f528cbcf42be"
        }
      ]
    }
  ]
}
