{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0-SNAPSHOT/util-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.13.0-SNAPSHOT.klib",
          "size": 25794,
          "sha512": "6ac58d5a9bea013c82f76e95424752bc3eeb2624c3ff220e805665c0788a49cb7b9e4faa3f556f61699401cc9e6b487f4ecdf712d1d299ad6403440e85855401",
          "sha256": "796531085200bcb6577a78ebb4e1336c2ded111d8901bab0f9c28a0aeec36577",
          "sha1": "6d4d0cdff904288483d5bd1df72a2bec7d098b66",
          "md5": "28fd600ecbb451fb4bc45e5b42e61b50"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.13.0-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.13.0-SNAPSHOT-metadata.jar",
          "size": 6142,
          "sha512": "cf4f9c9f9d9ca9b60afd611c50f79546abdb1ab345bfdb8f4704ff5d9a6319b45767230fb5b3fb9b874b26919bcfd6d115132cd537fccd630c5d7ece1d6fa317",
          "sha256": "e158c864c3e96f5467ca9b7644beff713bb37f2dffef05110fd6632112df23cc",
          "sha1": "f992a173eb2ff36c44085fab4c12f6ccdc89cb4b",
          "md5": "31f8d6dce8d883a5cb6cd221c05ef54c"
        }
      ]
    }
  ]
}
