{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-SNAPSHOT/util-test-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ybkt5re4ijar5butixmu6czoey"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19528,
          "sha512": "628022e7af0051071b6fe714457aaf06b1089bd385016b8018005e598ccd14504b2109f8b92dd3328f524f2c9c0ac30966a98760a2a3bafc62a0e8ca51192a09",
          "sha256": "5779bafabd538ccae9118b572f5b6d924664bb48a0a1ba3177497cc5b1ee0f89",
          "sha1": "b1afb8902fada238fcfb7d004be0fa70d0bef173",
          "md5": "60fd565e38c178c2ba8445a709b0f7ec"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19528,
          "sha512": "628022e7af0051071b6fe714457aaf06b1089bd385016b8018005e598ccd14504b2109f8b92dd3328f524f2c9c0ac30966a98760a2a3bafc62a0e8ca51192a09",
          "sha256": "5779bafabd538ccae9118b572f5b6d924664bb48a0a1ba3177497cc5b1ee0f89",
          "sha1": "b1afb8902fada238fcfb7d004be0fa70d0bef173",
          "md5": "60fd565e38c178c2ba8445a709b0f7ec"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-SNAPSHOT/util-test-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
