{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-SNAPSHOT/util-test-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "o7x552nqarhb5g27r4i3vzsh4i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "da0bffc3a113a13dbb78fc6600f87abec8d2b0cc2d0401d3552245151cceaca0812788336f9e8d27fde7799ce193565180415cf6a33cff18bb064917349b99f9",
          "sha256": "3ed490b89dbdd91761813aad44110ce88923e8f91a71ba93246a8af1022a6b88",
          "sha1": "a59f21cf3d08f6893b71776324467b71539bb8a0",
          "md5": "a31b3e2d993c30039654c45c08e7066b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "da0bffc3a113a13dbb78fc6600f87abec8d2b0cc2d0401d3552245151cceaca0812788336f9e8d27fde7799ce193565180415cf6a33cff18bb064917349b99f9",
          "sha256": "3ed490b89dbdd91761813aad44110ce88923e8f91a71ba93246a8af1022a6b88",
          "sha1": "a59f21cf3d08f6893b71776324467b71539bb8a0",
          "md5": "a31b3e2d993c30039654c45c08e7066b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-SNAPSHOT/util-test-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
