{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hi6ofeo65fdubak2f6hbnlywha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a327d61c1759311573b2e6748b71b9b66d15664d4c5c14b5710dd33c7fb4a567ed6ced2a0ad8974a595707e93c69fdb5f7120740fe95e52bc300a5867e6ca622",
          "sha256": "542abad4e6816ccc6eb9fd9eea34ba77b0c305fa39c096f099006bc4c7a063ac",
          "sha1": "374ecc3a8426b2cf70f80940fdbac87f71453b14",
          "md5": "50361e8e801b702e20111496e8ac80c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a327d61c1759311573b2e6748b71b9b66d15664d4c5c14b5710dd33c7fb4a567ed6ced2a0ad8974a595707e93c69fdb5f7120740fe95e52bc300a5867e6ca622",
          "sha256": "542abad4e6816ccc6eb9fd9eea34ba77b0c305fa39c096f099006bc4c7a063ac",
          "sha1": "374ecc3a8426b2cf70f80940fdbac87f71453b14",
          "md5": "50361e8e801b702e20111496e8ac80c1"
        }
      ]
    }
  ]
}
