{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "auqklhvfwjbcppg4sdkxl2tqjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "56272ce1ae65f4870dca3d552ac763f6b8959fd79c82310d09577044784879cb360429c4f5897036c625a0aba29c3703353d5a5143dbad1bddb8edb9a632f3b6",
          "sha256": "f81686472ff7e21fe2a17c8776c71de5086702ffa7bf23a06d231105719385e9",
          "sha1": "5fdf92f65d9f359309baea1dc77520b33e079459",
          "md5": "0a54b119ac605bae70b79dfac10bd255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "56272ce1ae65f4870dca3d552ac763f6b8959fd79c82310d09577044784879cb360429c4f5897036c625a0aba29c3703353d5a5143dbad1bddb8edb9a632f3b6",
          "sha256": "f81686472ff7e21fe2a17c8776c71de5086702ffa7bf23a06d231105719385e9",
          "sha1": "5fdf92f65d9f359309baea1dc77520b33e079459",
          "md5": "0a54b119ac605bae70b79dfac10bd255"
        }
      ]
    }
  ]
}
