{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m2pydfawtvgrhdpvxqkou5byxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e7a6c82825f6a86cfdf1d4ad95dc968d606d80a22fd37fc08d9e237451f5bc251b39a8d684ffa991f6ed5cbcc88ea23136ae85a151fc2ff88171347ed5c96cf9",
          "sha256": "8d3e6c49e2051c99ce3a0aa709cd8646a7cea10eb195a62d9b25c27018c65489",
          "sha1": "8d68b9d61935c1a9b4bfdc7974a5faecc23ef0ff",
          "md5": "c5a545adebffdcf7f4e42e778fce945a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e7a6c82825f6a86cfdf1d4ad95dc968d606d80a22fd37fc08d9e237451f5bc251b39a8d684ffa991f6ed5cbcc88ea23136ae85a151fc2ff88171347ed5c96cf9",
          "sha256": "8d3e6c49e2051c99ce3a0aa709cd8646a7cea10eb195a62d9b25c27018c65489",
          "sha1": "8d68b9d61935c1a9b4bfdc7974a5faecc23ef0ff",
          "md5": "c5a545adebffdcf7f4e42e778fce945a"
        }
      ]
    }
  ]
}
