{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ztmzf4nvkbaw7cjeluvubv6w6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "5622098818c0d6eb38c166f89a3d7ae2174eff389d1afe322d1571e37513bd8d1bd9a3f56f32d49a47367023fc65c5cbfaa6d59cba87e1764a7c56040c361aa3",
          "sha256": "f7939581ae5d2b7618630550f494e442b0ca85aac2d1bbc8f57ae2611d38e251",
          "sha1": "55de433fed091d13df5fb3997a21655ea8cb086e",
          "md5": "76ff4c92379ecf78da6892f93a0ec244"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "5622098818c0d6eb38c166f89a3d7ae2174eff389d1afe322d1571e37513bd8d1bd9a3f56f32d49a47367023fc65c5cbfaa6d59cba87e1764a7c56040c361aa3",
          "sha256": "f7939581ae5d2b7618630550f494e442b0ca85aac2d1bbc8f57ae2611d38e251",
          "sha1": "55de433fed091d13df5fb3997a21655ea8cb086e",
          "md5": "76ff4c92379ecf78da6892f93a0ec244"
        }
      ]
    }
  ]
}
