{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2fykjxuc6vf33k272qokyyctfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a8db20ebf0b8407846dacc6eea24aa7cd0dd0f22802eeca2c8b41315a94001b1c4b27070177ec71003a7bac5fe4445203e8020712717fd9505957a585bcfe6aa",
          "sha256": "49b091fc43bce3b61dc336d94cb0f0a1fd359a0f9dac108fbfca2641299c2d3b",
          "sha1": "d0cb3d7adad6b811d941b1c28f5be75bf72efd79",
          "md5": "781c1bf89475900d265617a96a2c3a70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a8db20ebf0b8407846dacc6eea24aa7cd0dd0f22802eeca2c8b41315a94001b1c4b27070177ec71003a7bac5fe4445203e8020712717fd9505957a585bcfe6aa",
          "sha256": "49b091fc43bce3b61dc336d94cb0f0a1fd359a0f9dac108fbfca2641299c2d3b",
          "sha1": "d0cb3d7adad6b811d941b1c28f5be75bf72efd79",
          "md5": "781c1bf89475900d265617a96a2c3a70"
        }
      ]
    }
  ]
}
