{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ga7ai7sd5rg2zdxgfsfxdlo5n4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f0a8d30ff2dbdd17b328e25d904091db53af5f4cf1723b17d0674dd7afcffcbdf52342cb5830ba254966bff18fd0950d6479f0e0db29d51b3eaca731764948c3",
          "sha256": "a7a469dde5db69692531d90b7bd3822153daa937a0947e8a483b7a90c202bac4",
          "sha1": "1585271841c56537a31e0da3958aaf20d3af5f22",
          "md5": "8617c7234e2f07ed49bab3f750ea949f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f0a8d30ff2dbdd17b328e25d904091db53af5f4cf1723b17d0674dd7afcffcbdf52342cb5830ba254966bff18fd0950d6479f0e0db29d51b3eaca731764948c3",
          "sha256": "a7a469dde5db69692531d90b7bd3822153daa937a0947e8a483b7a90c202bac4",
          "sha1": "1585271841c56537a31e0da3958aaf20d3af5f22",
          "md5": "8617c7234e2f07ed49bab3f750ea949f"
        }
      ]
    }
  ]
}
