{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n2g3z3c4ejfnpmwgn7cyvo5rmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "aaf36c81ae5e88d4fc1bc7f349bbc84cfe065bf8cd01db2b377d6fba6a633e7d192b526474c623cf33c31da4af3203b2ed9c74b557e716666efd2e68b01a6575",
          "sha256": "63784f061917c52385be63991c2f3013422917f0235369bd69504187c73be919",
          "sha1": "6c3e83aa1e3812de6caff2220b2709e02a6ebfbf",
          "md5": "0c86feecca4b2c3b4c2ad9b77b88ec53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "aaf36c81ae5e88d4fc1bc7f349bbc84cfe065bf8cd01db2b377d6fba6a633e7d192b526474c623cf33c31da4af3203b2ed9c74b557e716666efd2e68b01a6575",
          "sha256": "63784f061917c52385be63991c2f3013422917f0235369bd69504187c73be919",
          "sha1": "6c3e83aa1e3812de6caff2220b2709e02a6ebfbf",
          "md5": "0c86feecca4b2c3b4c2ad9b77b88ec53"
        }
      ]
    }
  ]
}
