{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.9.0-SNAPSHOT/util-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "63qqs5p2h5ehja6n7z7pbn5fru"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test.klib",
          "url": "util-test-iosx64-1.9.0-SNAPSHOT.klib",
          "size": 12279,
          "sha512": "0292de34bab411c5a964a653e6d9d61c2529b5440f6dafe45099d11cf23a302089bb1e36b5600ca79b9c8ba76ea908de15d11ac70321f53bc0ca7ffeb58850e9",
          "sha256": "7d219c2c2e03a74b70982fb0586e66406b11af28f57cbca3843e0a51c0836b9f",
          "sha1": "c83d82fb7b7836ec97b4e834cd5272deab470a55",
          "md5": "6963d240cd1b7723cb5f4f099c31908a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.9.0-SNAPSHOT/util-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
