{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.14.0-SNAPSHOT/util-1.14.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.14.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.14.0-SNAPSHOT.klib",
          "size": 25777,
          "sha512": "16cb6b3d4c0358d1c86af62f9c60b2aa8e5f06115b0269395bb932d02ae20aae773446fd74029b166c704c5c08cb6e717e66c65671e2817c54b15e0d5c22bc2d",
          "sha256": "7fcad917d96aac0a9d0c3628ba1bbf05e52dd4848cb8117c6a094cc8adb32c19",
          "sha1": "a7c0e9f653edf1accf9f72b0b91d74bc883304d9",
          "md5": "5bc051454ae306770f82ccf14ccb765d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.14.0-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.14.0-SNAPSHOT-metadata.jar",
          "size": 6142,
          "sha512": "b4d94fa5eaedcbac851cad37ebe15f6a688dd2584f8a61eb70cf148f1345982d4bbe8a0be371b557e07e1859fb69921e0a7efe051fd4da13d178b7c452d4545d",
          "sha256": "52e40c99ffd7e17e5f50ce454cd40a611df6ee2d2fb9105461270459a3513ccb",
          "sha1": "2bc3c58228f8b3a8c45f2a8159b911f136bd193b",
          "md5": "76a297599363b73abede1a69231ac541"
        }
      ]
    }
  ]
}
