{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cdfwhwvegvgfnmhtly3plx3hyy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.13.2-SNAPSHOT.aar",
          "url": "securestore-android-1.13.2-SNAPSHOT.aar",
          "size": 41905,
          "sha512": "43d0d47ae45576ce1f9895b5f2ef6ba3fba3ff546d93b553f6296ecceb512c0750838f1e7c99e7a3a4181c7301865d0cabc5e9c4e6b8e1a3e78e42736c8eaf7f",
          "sha256": "be67167af3369a94b210cc963a507d5ff3666df1633c9042d4115de551e6df12",
          "sha1": "fd350b9cc27c5bce07917441276dda9d6b5fc506",
          "md5": "9a1db4fddaadc0f89a34b78641e9ff24"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.13.2-SNAPSHOT.aar",
          "url": "securestore-android-1.13.2-SNAPSHOT.aar",
          "size": 41905,
          "sha512": "43d0d47ae45576ce1f9895b5f2ef6ba3fba3ff546d93b553f6296ecceb512c0750838f1e7c99e7a3a4181c7301865d0cabc5e9c4e6b8e1a3e78e42736c8eaf7f",
          "sha256": "be67167af3369a94b210cc963a507d5ff3666df1633c9042d4115de551e6df12",
          "sha1": "fd350b9cc27c5bce07917441276dda9d6b5fc506",
          "md5": "9a1db4fddaadc0f89a34b78641e9ff24"
        }
      ]
    }
  ]
}
