{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-SNAPSHOT/util-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lyzjzny7rvfyfggh2niazgzxai"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "db1c469ced12ce92034e4b81540e8399214a3e8042ca5b2b1cee0db9775b16882f77090b18527c79e4abc6814a6fec07527cc149adf25bcd4d9781a35d858435",
          "sha256": "5d6481340649f9cba7b3deccd9b07b55764843e78927290854cb5922a7bf8089",
          "sha1": "051d73db631770d3e91275839a7e7d0a5fa525e4",
          "md5": "06a3dbf426814813f43ac56495080a32"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "db1c469ced12ce92034e4b81540e8399214a3e8042ca5b2b1cee0db9775b16882f77090b18527c79e4abc6814a6fec07527cc149adf25bcd4d9781a35d858435",
          "sha256": "5d6481340649f9cba7b3deccd9b07b55764843e78927290854cb5922a7bf8089",
          "sha1": "051d73db631770d3e91275839a7e7d0a5fa525e4",
          "md5": "06a3dbf426814813f43ac56495080a32"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-SNAPSHOT/util-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
