{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-SNAPSHOT/util-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ukgokpauvjdrlafbmd4tlsjq7e"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20085,
          "sha512": "e416c6cd5ff274e84b0eaf876987793c06f5ac2595e5c15bde4ca080f05094f4ff89ff60d32737f925b73b4c0661cabc6377dd2183af3b119d5ecdd9c66fa47d",
          "sha256": "e0d23225af84b236ca1de2c28a3b1e9f3691b8acf78f8082242e9d18a8db549d",
          "sha1": "3a140a4dd658512414db153ec69168f8c4a81cda",
          "md5": "c6cd54492b792285ba293ee261095d0f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20085,
          "sha512": "e416c6cd5ff274e84b0eaf876987793c06f5ac2595e5c15bde4ca080f05094f4ff89ff60d32737f925b73b4c0661cabc6377dd2183af3b119d5ecdd9c66fa47d",
          "sha256": "e0d23225af84b236ca1de2c28a3b1e9f3691b8acf78f8082242e9d18a8db549d",
          "sha1": "3a140a4dd658512414db153ec69168f8c4a81cda",
          "md5": "c6cd54492b792285ba293ee261095d0f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-SNAPSHOT/util-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
