{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-metadata-0.1.0-SNAPSHOT-all.jar",
          "url": "coroutine-util-0.1.0-SNAPSHOT-all.jar",
          "size": 5074,
          "sha512": "c1aede57c23a320c8acabed62de307c7d5dea71fe25d527a9db234090252affe4ba4f1f4c92c2ce263d7643b4548b774fa7620b3f9761c1082ae2bdf691df9d9",
          "sha256": "a6db268ecd8e760c1573b0c0c05e74fc638344ecd6d0f27d9a3878bc63c2eb98",
          "sha1": "4feb3bc3badf5e1dcab9d6ce51828b9c5b3ba00a",
          "md5": "c9b7a1f0d877020880492fe4f20bca0f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coroutine-util-0.1.0-SNAPSHOT.jar",
          "url": "coroutine-util-0.1.0-SNAPSHOT.jar",
          "size": 2631,
          "sha512": "0854a3081fd82921149ffe4b17105b285dcca38fc924e1c9ae56ff889c0b0b3cc2c745ec9df8a03b35209aba0fc3a275a460c713c8a94cc39f4f50376cb272a9",
          "sha256": "053ac10218444eda5601ad1fefeae58922493326a329b485df5a281392f217e2",
          "sha1": "04ebf8564842bd594a13f858a7f505e080e96595",
          "md5": "e90e8d7f11f8d6981c2c1a9e660e2f1f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-SNAPSHOT/coroutine-util-android-debug-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-SNAPSHOT/coroutine-util-android-debug-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-SNAPSHOT/coroutine-util-android-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-SNAPSHOT/coroutine-util-android-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-SNAPSHOT/coroutine-util-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-SNAPSHOT/coroutine-util-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-SNAPSHOT/coroutine-util-iosx64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-SNAPSHOT/coroutine-util-iosx64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-SNAPSHOT/coroutine-util-jvm-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-SNAPSHOT/coroutine-util-jvm-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
