{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-metadata-0.1.0-SNAPSHOT-all.jar",
          "url": "coroutine-util-0.1.0-SNAPSHOT-all.jar",
          "size": 5074,
          "sha512": "c4b46e72f2324b9eca1da4187469e4c1bc71659c33a10db757c91bb3137a185c54721e26d7a82cadf7a0295a0d8a26952dc7419a1bffb009d9ea474a1ac9a39c",
          "sha256": "85fdeddb4a04891e66efc404df2c37aa8e892b0e09ba8ce7b79d67086d2275be",
          "sha1": "91a2bcffd149f81b05c4a7fb23870a731ef9a84a",
          "md5": "79b0e278e465cba0074f86628a0ae8ee"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coroutine-util-0.1.0-SNAPSHOT.jar",
          "url": "coroutine-util-0.1.0-SNAPSHOT.jar",
          "size": 2631,
          "sha512": "c436748fc2859ba11f4c62fa8b48f55b4043fa9757b79f508df5e2446ab6742a3fbec4d86b70d767da09700ed8f740c9dc0d0ef1449bf142944315bcdc0b9b04",
          "sha256": "a2523151cafb4df0f114eaf9f1d37bf39cb733323fed9fc9ad31ff3ce1f79db0",
          "sha1": "72b6adf9089128bcd5b61bc80e09591226587568",
          "md5": "e7567d4053fcf1b9d0cc2a122d0897c6"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-SNAPSHOT/coroutine-util-android-debug-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-SNAPSHOT/coroutine-util-android-debug-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-SNAPSHOT/coroutine-util-android-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-SNAPSHOT/coroutine-util-android-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-SNAPSHOT/coroutine-util-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-SNAPSHOT/coroutine-util-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-SNAPSHOT/coroutine-util-iosx64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-SNAPSHOT/coroutine-util-iosx64-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-SNAPSHOT/coroutine-util-jvm-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-SNAPSHOT/coroutine-util-jvm-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
