{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-SNAPSHOT/test-util-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-util-release.aar",
          "url": "test-util-android-0.2.0-SNAPSHOT.aar",
          "size": 7917,
          "sha512": "ba6bb410b27a19961d4e891eaf33a7ce726536198eb76ee99f80e2ac6b5c4a02cec86f2400fdbd6692065d545a9af9d50364006d6b2c64c2952f4dd5d6d46802",
          "sha256": "8ddd93f48c0083e3e294a126711bbf4addb32a6da77cf5b0e1ecc0777243bcac",
          "sha1": "53423c9bac1aadf159bcb3ac81ff0d6baa251e24",
          "md5": "8314deead6b9f087f962b8f68e5b456e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-release.aar",
          "url": "test-util-android-0.2.0-SNAPSHOT.aar",
          "size": 7917,
          "sha512": "ba6bb410b27a19961d4e891eaf33a7ce726536198eb76ee99f80e2ac6b5c4a02cec86f2400fdbd6692065d545a9af9d50364006d6b2c64c2952f4dd5d6d46802",
          "sha256": "8ddd93f48c0083e3e294a126711bbf4addb32a6da77cf5b0e1ecc0777243bcac",
          "sha1": "53423c9bac1aadf159bcb3ac81ff0d6baa251e24",
          "md5": "8314deead6b9f087f962b8f68e5b456e"
        }
      ]
    }
  ]
}
