{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vhtne7ae6nez5mkqslirii3ifm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "426e2d4f9608911ef754dfa8c08886e9733307909c646b447a49ee7969f908b777e3c6e71e87f945443aac121f9f3ac9e606ed14a101c59c0a46cb57e05111b2",
          "sha256": "3b62aa6635f9f6ed9cf81e5285eddbc1e8bd66b15b97a551765450feddbf677d",
          "sha1": "97fbc72ceae9721ce8e44cd821d0001dd5269c66",
          "md5": "43d50064d28418df353ed79a41c35b65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "426e2d4f9608911ef754dfa8c08886e9733307909c646b447a49ee7969f908b777e3c6e71e87f945443aac121f9f3ac9e606ed14a101c59c0a46cb57e05111b2",
          "sha256": "3b62aa6635f9f6ed9cf81e5285eddbc1e8bd66b15b97a551765450feddbf677d",
          "sha1": "97fbc72ceae9721ce8e44cd821d0001dd5269c66",
          "md5": "43d50064d28418df353ed79a41c35b65"
        }
      ]
    }
  ]
}
