{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ex6wcqgazjfklhprdf67prhaoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "24e3e1840dd24f3ae3b377d8da6acfd3e5ca0f5485623fcb93949f386a40ac6a153b6c81411beb56c4be644af7a181ee552c4a9cbbdc30c7ce58121795c9b12b",
          "sha256": "d7794aa7e00c0653dc9218b1ee02c7c7d5fc55c3facd2b269ab820afcc7b7cda",
          "sha1": "86aa7817f54083aefa28521530f49003e5322d9e",
          "md5": "8d32d3c2a108e09c258f65ba2f6578d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "24e3e1840dd24f3ae3b377d8da6acfd3e5ca0f5485623fcb93949f386a40ac6a153b6c81411beb56c4be644af7a181ee552c4a9cbbdc30c7ce58121795c9b12b",
          "sha256": "d7794aa7e00c0653dc9218b1ee02c7c7d5fc55c3facd2b269ab820afcc7b7cda",
          "sha1": "86aa7817f54083aefa28521530f49003e5322d9e",
          "md5": "8d32d3c2a108e09c258f65ba2f6578d1"
        }
      ]
    }
  ]
}
