{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bm5rghhf3jhsjoc52gph46k66a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "11eb5b276151e33f0f850a9e743a447e1396f417cda21f8764d26fb0ed8e8fbd7a3a89d868aeea2590e9b067d4dfe9258f228d3d2e84f262e948c52834c34932",
          "sha256": "f4373f8aa06b5e0836c192c9b579f0d5de1aa7ff89905c2574c45ad013b91a85",
          "sha1": "0a24c320f5ca1437f31943b659ef54c5239e8120",
          "md5": "f876a96c0cc705a29062869ec652f7f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "11eb5b276151e33f0f850a9e743a447e1396f417cda21f8764d26fb0ed8e8fbd7a3a89d868aeea2590e9b067d4dfe9258f228d3d2e84f262e948c52834c34932",
          "sha256": "f4373f8aa06b5e0836c192c9b579f0d5de1aa7ff89905c2574c45ad013b91a85",
          "sha1": "0a24c320f5ca1437f31943b659ef54c5239e8120",
          "md5": "f876a96c0cc705a29062869ec652f7f2"
        }
      ]
    }
  ]
}
