{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hrphzlccjref7k3o6a7cm7lnry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "983b232348d712339a54f503d6373d8e5d11cdad2e1e44867995b65b940b04abb85fefb686a5bc147c5a16dcb669617b27e9f76e5f66f185431b7ad8d122a1ec",
          "sha256": "a32d183c64927a26bb154ea98967da7686cb0fac78d7aa7785ed55f72f199cb1",
          "sha1": "ade113c9dd966b8578bcb357cca08db02938f800",
          "md5": "cbce732f19d2b1c50f5223ffab0f8827"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "983b232348d712339a54f503d6373d8e5d11cdad2e1e44867995b65b940b04abb85fefb686a5bc147c5a16dcb669617b27e9f76e5f66f185431b7ad8d122a1ec",
          "sha256": "a32d183c64927a26bb154ea98967da7686cb0fac78d7aa7785ed55f72f199cb1",
          "sha1": "ade113c9dd966b8578bcb357cca08db02938f800",
          "md5": "cbce732f19d2b1c50f5223ffab0f8827"
        }
      ]
    }
  ]
}
