{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v7c5s6v2vjg5rppvy5jghwttee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "86a8b35338fea147c5a9656be87dec89e3a84372a78613f56911efafcd7fc7b5ca72881e88830895598e30e8eda719c43c75931aa651b07bd6d93e2c7ebabb84",
          "sha256": "94fe646719658af4b9ea88f0f259fbe0b0bdf7dcdf3a38198ffac53f89f0fdee",
          "sha1": "e8503c1658be467191a11e89788264d01df92d92",
          "md5": "44e3b5ca122eacb9984f4492321cd885"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "86a8b35338fea147c5a9656be87dec89e3a84372a78613f56911efafcd7fc7b5ca72881e88830895598e30e8eda719c43c75931aa651b07bd6d93e2c7ebabb84",
          "sha256": "94fe646719658af4b9ea88f0f259fbe0b0bdf7dcdf3a38198ffac53f89f0fdee",
          "sha1": "e8503c1658be467191a11e89788264d01df92d92",
          "md5": "44e3b5ca122eacb9984f4492321cd885"
        }
      ]
    }
  ]
}
