{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "maqnzeqddzckreymvhto56jcxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "fad64bf8275b4f8daa6b33a6fb12f47dbf86a5825955a09105e4f3346db6b0fb544824b962023adfc7bdd1ccb6815c518fa494776cd9a2ecf52d51b13867229d",
          "sha256": "2039e07bd99a4290f8619c1a736c11cd4b75ba3c8c99399d4f6430ed651039ea",
          "sha1": "84e88e80110cba7fb708355b235760bd7cb7ffd1",
          "md5": "4bfddece46f1cabc545e8ba7bb72fb10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "fad64bf8275b4f8daa6b33a6fb12f47dbf86a5825955a09105e4f3346db6b0fb544824b962023adfc7bdd1ccb6815c518fa494776cd9a2ecf52d51b13867229d",
          "sha256": "2039e07bd99a4290f8619c1a736c11cd4b75ba3c8c99399d4f6430ed651039ea",
          "sha1": "84e88e80110cba7fb708355b235760bd7cb7ffd1",
          "md5": "4bfddece46f1cabc545e8ba7bb72fb10"
        }
      ]
    }
  ]
}
