{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.6.0-SNAPSHOT/fhir-helper-1.6.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4bufh77a4negzg37kel6ux4jty"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.6.0-SNAPSHOT.aar",
          "size": 111842,
          "sha512": "2d03f0b8dd972455b85ca06aa43b782055fc45db52a0e8bb1ef0adef33d6e8f71031c6f747a89dfab2eff9ae7019c9ede3b1b9130af46eecd49366877d5e34d7",
          "sha256": "3b9fa86af81596d9a13d2d0bcee03c0737df218f6d3bde9476dcf06de8b76b4a",
          "sha1": "4ababf7ee84ff39a3662e8678f09712d8d8cf2bc",
          "md5": "27b2be0e4418cfe2db1fae9d573472c3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.6.0-SNAPSHOT.aar",
          "size": 111842,
          "sha512": "2d03f0b8dd972455b85ca06aa43b782055fc45db52a0e8bb1ef0adef33d6e8f71031c6f747a89dfab2eff9ae7019c9ede3b1b9130af46eecd49366877d5e34d7",
          "sha256": "3b9fa86af81596d9a13d2d0bcee03c0737df218f6d3bde9476dcf06de8b76b4a",
          "sha1": "4ababf7ee84ff39a3662e8678f09712d8d8cf2bc",
          "md5": "27b2be0e4418cfe2db1fae9d573472c3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.6.0-SNAPSHOT/fhir-helper-metadata-1.6.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
