{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.6.0-SNAPSHOT/fhir-helper-1.6.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "x3qntpbatbejzhgfqoucstgame"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.6.0-SNAPSHOT.aar",
          "size": 111820,
          "sha512": "cf06c799ed1a1f18fa389fcbca9911c0040e8e1c60ebc5e4f8c42099a9e544772b33774d00ce6cc6393d0e9cc5b93c99630b78759b762b89408897992c7d6f1a",
          "sha256": "7548ed0b12cbc8c4c36af609bd6191da7e76c5942861a590b343e981a34927bd",
          "sha1": "3b6696632336b3adecac007acbdd543f48ff75b5",
          "md5": "c9c81b6bc1eb7c261815b8445b4e84c3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.6.0-SNAPSHOT.aar",
          "size": 111820,
          "sha512": "cf06c799ed1a1f18fa389fcbca9911c0040e8e1c60ebc5e4f8c42099a9e544772b33774d00ce6cc6393d0e9cc5b93c99630b78759b762b89408897992c7d6f1a",
          "sha256": "7548ed0b12cbc8c4c36af609bd6191da7e76c5942861a590b343e981a34927bd",
          "sha1": "3b6696632336b3adecac007acbdd543f48ff75b5",
          "md5": "c9c81b6bc1eb7c261815b8445b4e84c3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.6.0-SNAPSHOT/fhir-helper-metadata-1.6.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
