{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.0-SNAPSHOT/util-1.8.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xx4b4whzuregrcn7lvalqkdfse"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.0-SNAPSHOT.jar",
          "url": "util-jvm-1.8.0-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "284e5d113a2ea2bdacc86de02f556429f21068387d383012864e53c268d7cb565ce078d6b49c5a2746f06082ea647760644bd1332d0bcfae4ddb48ce23102b08",
          "sha256": "df8143db9eddc29d31382e085ddde487ebfba29e914b71ada357058ad2531429",
          "sha1": "56c5d5f4f7120df54303eaadf942a4664585d2ae",
          "md5": "d9bf5bf723c1933ba506eccc688be033"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.0-SNAPSHOT.jar",
          "url": "util-jvm-1.8.0-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "284e5d113a2ea2bdacc86de02f556429f21068387d383012864e53c268d7cb565ce078d6b49c5a2746f06082ea647760644bd1332d0bcfae4ddb48ce23102b08",
          "sha256": "df8143db9eddc29d31382e085ddde487ebfba29e914b71ada357058ad2531429",
          "sha1": "56c5d5f4f7120df54303eaadf942a4664585d2ae",
          "md5": "d9bf5bf723c1933ba506eccc688be033"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.0-SNAPSHOT/util-metadata-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.0-SNAPSHOT"
      }
    }
  ]
}
