{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.1.0-SNAPSHOT/test-util-ktor-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "uqu5rbeh55dxbdgbgwttrpeoqi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "151399078d6b049b045343018883c2dcb013822089dfa3bf547cfe71f3a463abed7105603414aa01510a52b62f8f4a8e8c2a853b3581d895d75aa9dda64d3dc9",
          "sha256": "9f5ef48232c7c313463ba3d8a8bc8a1c297cc00093a356f79d3090102a3cff19",
          "sha1": "e67f953edcb08e02c81d52687dd3f1e810b3bf7f",
          "md5": "91327cc4cab3193234cdb0538133babc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "151399078d6b049b045343018883c2dcb013822089dfa3bf547cfe71f3a463abed7105603414aa01510a52b62f8f4a8e8c2a853b3581d895d75aa9dda64d3dc9",
          "sha256": "9f5ef48232c7c313463ba3d8a8bc8a1c297cc00093a356f79d3090102a3cff19",
          "sha1": "e67f953edcb08e02c81d52687dd3f1e810b3bf7f",
          "md5": "91327cc4cab3193234cdb0538133babc"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.1.0-SNAPSHOT/test-util-ktor-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
