{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.1.0-SNAPSHOT/test-util-ktor-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "6kz66mlrc5hfvnffjln5cjz5lm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "41b7f4fc4893e42e34b6d5c66569d755993aba03688282ddfe93570db4f4ec8d3df190734373fc26be2714fc50585fc5052de22964b1b92e9394916e0b69544a",
          "sha256": "fc60aff07438d6f0de123fc09bb260c106ccf7b16f3e4d3180d92dad8a06e348",
          "sha1": "a8a8575e52923e3fd1e7a76fde45f1bc6126257e",
          "md5": "72fab413deea11d28ac8f85b88abc330"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "41b7f4fc4893e42e34b6d5c66569d755993aba03688282ddfe93570db4f4ec8d3df190734373fc26be2714fc50585fc5052de22964b1b92e9394916e0b69544a",
          "sha256": "fc60aff07438d6f0de123fc09bb260c106ccf7b16f3e4d3180d92dad8a06e348",
          "sha1": "a8a8575e52923e3fd1e7a76fde45f1bc6126257e",
          "md5": "72fab413deea11d28ac8f85b88abc330"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.1.0-SNAPSHOT/test-util-ktor-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
