{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.1.0-SNAPSHOT/test-util-ktor-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "wvmegi33jnghnejebyykh7a7si"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "764e270f3e393c655010b84e7788b99fd8ebfd830f631193ea9b58b0baca275c516cdc0f2f75c8f66b8e7e13917b7b596d088bbccc02a7b38b9d04649f7dc2f8",
          "sha256": "909aacbd62e62b418d2b443420813441d4e76f69b8dd243500b036b50098ca0f",
          "sha1": "f2dd333b47ca2ae398f7004f51a7f75712527b90",
          "md5": "ba7c2d1313965fd21ce8566f6b4a6b91"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "764e270f3e393c655010b84e7788b99fd8ebfd830f631193ea9b58b0baca275c516cdc0f2f75c8f66b8e7e13917b7b596d088bbccc02a7b38b9d04649f7dc2f8",
          "sha256": "909aacbd62e62b418d2b443420813441d4e76f69b8dd243500b036b50098ca0f",
          "sha1": "f2dd333b47ca2ae398f7004f51a7f75712527b90",
          "md5": "ba7c2d1313965fd21ce8566f6b4a6b91"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.1.0-SNAPSHOT/test-util-ktor-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
