{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-SNAPSHOT/util-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cn7y7pbly5dqffluewyd5ncn5e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "f1df26b48d8ff7a105bc43f7a47161b6b19f6075f92ca8fa318f9865cbeda4cb74ba66efb7da8c956c1d1dc606a05539478e8e59d3b936ee0a563183b6266cd7",
          "sha256": "1be37f457fddda4ada8674aa3f959cbd4a298a6c7b3c0ec795c505ec0107bbde",
          "sha1": "43c8236677c413cf31910dcccb54129b9f9409e7",
          "md5": "10c86aba73d4d5bb64979a03fe5d3077"
        }
      ]
    }
  ]
}
