{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-SNAPSHOT/util-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kwd3npjy6nbmpkyxjt5wxiv2ae"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "0cf9353feceeeacf98f016a360ad77c52a907e19dc6347be2012d1337e817ee450cca6d6bd1980e4c32f711ef001a2678bd3b9c39d38bb5d645c47d177cb9fc5",
          "sha256": "c4d1e68ba06ecc8adf83b77687b13d0adef1520266b37c0bafa92693754ecaa6",
          "sha1": "3593bc34667eccb990f62382a079aa692e4f3143",
          "md5": "42813ce559644fafefc16bdd336e7891"
        }
      ]
    }
  ]
}
