{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-SNAPSHOT/util-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vzdwddbgzrddta7pfbonknl3wm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "99741aa17ad2b1913fda36f490638ca6c3925f9226244279c923f0405e56f38e6f4934122366c4699ae7c12a73a0c4d6414735855b5e1a26285f1a1f7826d585",
          "sha256": "f1ba6e7216de0a5f209401c223cb2398937a7d379d5416b5fc27e68efd9f16c7",
          "sha1": "3102e6e251978c34908d44bf5f42f1fa2b676813",
          "md5": "545226e56bd274d6b766d32d5b864647"
        }
      ]
    }
  ]
}
