{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-SNAPSHOT/util-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7cjvcm2wxfazdlmoedzu3lam7q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "2a6284c7a78ae3bb0de80c974c9b6e78ff603ea91aebcea032cfee6e7472c64836c49c704ff69be4b64cb5b4f0cd1083903628780ff1aa4676ee8f65efe0cbab",
          "sha256": "bdf72fafd5ce5d75b2c76c5bf2f3570232ed0351914c6ace270c44b79aa17bf4",
          "sha1": "06be36b47154b4751ab14dfcc913e6e4ec10ca5e",
          "md5": "67e85d8f9a2db5eec0a80d4547ab0118"
        }
      ]
    }
  ]
}
