{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto-jvm/1.13.2-SNAPSHOT/crypto-jvm-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "uhtto4g4lvghjijzwgdccgkxge"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.13.2-SNAPSHOT.jar",
          "url": "crypto-metadata-1.13.2-SNAPSHOT.jar",
          "size": 11995,
          "sha512": "786c3b79f7176b4a83cda306e27ab6d992f4f38b4b449fe60651fafa1dc8d57f4bc9c83a5143c658cf5920e866af91ac54c981b4e4f570a3be23363cc02d8f53",
          "sha256": "c7f4b3aa647fc1a9145506eeabbbe8d8ef4f3039be185557badad85bc9873bc4",
          "sha1": "6b9b7d9a983a71f09f90a5b2ca1373e6a1839da3",
          "md5": "680dceb63bba761c4e953c096a7e3705"
        }
      ]
    }
  ]
}
