{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/91f5616/crypto-91f5616.module",
    "group": "care.data4life.hc-crypto-kmp",
    "module": "crypto",
    "version": "91f5616",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "vyvng5utczgy7p5escs4xhono4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-91f5616.jar",
          "url": "crypto-jvm-91f5616.jar",
          "size": 56992,
          "sha512": "ee3804012c8b1df49c249d31dc0dcb7389bb0c299ca044b3ad268647b5c2cc93f246ae9ab97a641a3b7e79c7370823df5e302a3d99e34a17155d4a020ebb2c75",
          "sha256": "357a9940e3a619bedf5dc54e96733c641b579c69378a31dc2d743bd229a0d8ec",
          "sha1": "da052e008e8130cf18d44d7b44f13d3546b53925",
          "md5": "f8d314b159ca40429cb67ece5a971647"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-91f5616.jar",
          "url": "crypto-jvm-91f5616.jar",
          "size": 56992,
          "sha512": "ee3804012c8b1df49c249d31dc0dcb7389bb0c299ca044b3ad268647b5c2cc93f246ae9ab97a641a3b7e79c7370823df5e302a3d99e34a17155d4a020ebb2c75",
          "sha256": "357a9940e3a619bedf5dc54e96733c641b579c69378a31dc2d743bd229a0d8ec",
          "sha1": "da052e008e8130cf18d44d7b44f13d3546b53925",
          "md5": "f8d314b159ca40429cb67ece5a971647"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/91f5616/crypto-metadata-91f5616.module",
        "group": "care.data4life.hc-crypto-kmp",
        "module": "crypto-metadata",
        "version": "91f5616"
      }
    }
  ]
}
