{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-SNAPSHOT/util-1.11.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-debug.aar",
          "url": "util-android-debug-1.11.0-SNAPSHOT.aar",
          "size": 15000,
          "sha512": "5b929fc283ebf9d552bacb886ceaed0832504d0411e9e20389ac8e264e8066ad046631eebb91f827dc92215c8605f848254898c50f251c6345c0222b72d44c2d",
          "sha256": "d716c32f97f5386c217f616d25aff00ececfe64171879e5c0fd7377ebde0da85",
          "sha1": "fc5e102cd4b6bfe45751848ed08e13fc1560908b",
          "md5": "6e6b186d170bc6bfa9fb65bb6a7a87e8"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-debug.aar",
          "url": "util-android-debug-1.11.0-SNAPSHOT.aar",
          "size": 15000,
          "sha512": "5b929fc283ebf9d552bacb886ceaed0832504d0411e9e20389ac8e264e8066ad046631eebb91f827dc92215c8605f848254898c50f251c6345c0222b72d44c2d",
          "sha256": "d716c32f97f5386c217f616d25aff00ececfe64171879e5c0fd7377ebde0da85",
          "sha1": "fc5e102cd4b6bfe45751848ed08e13fc1560908b",
          "md5": "6e6b186d170bc6bfa9fb65bb6a7a87e8"
        }
      ]
    }
  ]
}
