{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cx65bhetunaoxfxltujfxjmqbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "27b0999f5a71c0df6a2f29b97d249429b5c5cd19620717e5fc3c549ebeca0430d3a532189417de5e0e5e04cad1671de825a4f8b61bdb389c0972ace0e1a52640",
          "sha256": "294f72ed63ea4f508429e999da38a6804631f1083aa2b1d70e1983d8d1f53ab8",
          "sha1": "93ebe3ed39ccd40aa51a2effcf363b5e069d6376",
          "md5": "5db4e975f4a18a5ed5e8538e5ea14a5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "27b0999f5a71c0df6a2f29b97d249429b5c5cd19620717e5fc3c549ebeca0430d3a532189417de5e0e5e04cad1671de825a4f8b61bdb389c0972ace0e1a52640",
          "sha256": "294f72ed63ea4f508429e999da38a6804631f1083aa2b1d70e1983d8d1f53ab8",
          "sha1": "93ebe3ed39ccd40aa51a2effcf363b5e069d6376",
          "md5": "5db4e975f4a18a5ed5e8538e5ea14a5e"
        }
      ]
    }
  ]
}
