{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5qeooh42f5ac7eixzuagb4hx2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "710fb91f17f0e40444c83ee930474b3008b04fbf33b87cc90595dad5d658f79ddad49d3fecfa1e9ad28be241b59ef2a150c30501201a09b0e20c08dcf2277d43",
          "sha256": "71932f78fd2aea273766832dc9812bc1566cd6b0a11ad1711bfb2b335a43a2ba",
          "sha1": "d49a8f64a8c0566363df616ff50264afd1f7d159",
          "md5": "bdb61bf39ceb2710b375bd24130f5a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "710fb91f17f0e40444c83ee930474b3008b04fbf33b87cc90595dad5d658f79ddad49d3fecfa1e9ad28be241b59ef2a150c30501201a09b0e20c08dcf2277d43",
          "sha256": "71932f78fd2aea273766832dc9812bc1566cd6b0a11ad1711bfb2b335a43a2ba",
          "sha1": "d49a8f64a8c0566363df616ff50264afd1f7d159",
          "md5": "bdb61bf39ceb2710b375bd24130f5a38"
        }
      ]
    }
  ]
}
