{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qlgearrk4vexthlm7fxtai5hci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "69fb3fef6ec25ab00e90d3f1bb073c0132590c8589abf4b1c998c747eed1a80be6415f016ebe4411fec08e64fb30eb73c3531d8324653a38149b85a38e4b6cc4",
          "sha256": "9397661668cd679d18cc010b39835014966a4f266ebcb867931e1e0068d1ec41",
          "sha1": "0eeed41eb8355ab3f016c5aa0cd4ea5513f62eb2",
          "md5": "aefd489e85da3ad0ee0f5529c2199357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "69fb3fef6ec25ab00e90d3f1bb073c0132590c8589abf4b1c998c747eed1a80be6415f016ebe4411fec08e64fb30eb73c3531d8324653a38149b85a38e4b6cc4",
          "sha256": "9397661668cd679d18cc010b39835014966a4f266ebcb867931e1e0068d1ec41",
          "sha1": "0eeed41eb8355ab3f016c5aa0cd4ea5513f62eb2",
          "md5": "aefd489e85da3ad0ee0f5529c2199357"
        }
      ]
    }
  ]
}
