{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.6.3-SNAPSHOT.jar",
          "url": "fhir-java-1.6.3-SNAPSHOT.jar",
          "size": 1012286,
          "sha512": "96fb8750fa4fc82d1e285a985cf91b93f0908088265d452c3e3a7855909f1a1f90f8b0b1732b13bd1acb1bb2d29189b5bfd6c9cea06c08d031eedf8f05271cce",
          "sha256": "981c0885bea55356ce15526ae3bcefea87bac747e691feb1a5380c201a16cb3b",
          "sha1": "37aa34ca08864a53ebe62612a77a757e5cafadd6",
          "md5": "460b0ad7ac37a1b514f1bbe0f5a47c8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.6.3-SNAPSHOT.jar",
          "url": "fhir-java-1.6.3-SNAPSHOT.jar",
          "size": 1012286,
          "sha512": "96fb8750fa4fc82d1e285a985cf91b93f0908088265d452c3e3a7855909f1a1f90f8b0b1732b13bd1acb1bb2d29189b5bfd6c9cea06c08d031eedf8f05271cce",
          "sha256": "981c0885bea55356ce15526ae3bcefea87bac747e691feb1a5380c201a16cb3b",
          "sha1": "37aa34ca08864a53ebe62612a77a757e5cafadd6",
          "md5": "460b0ad7ac37a1b514f1bbe0f5a47c8a"
        }
      ]
    }
  ]
}
