{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-SNAPSHOT/test-util-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "spphud3arfeypnlnwvilthgfrq"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.2.0-SNAPSHOT.klib",
          "size": 14823,
          "sha512": "2313fbb7accfa1d35cd23a85f9f44fd0242a81fd4815adf43d4dbbe1614c71fb19a4a51e20ead9ac84ab80db62b34d6c0d7adb45728cc1a4afd7504b2a83c6f9",
          "sha256": "8232cebad6c20a85bed038debb5c01a6ac75225a520d476d1a7d97765845e0c3",
          "sha1": "fce30b2bd7681c3c0f7f7eaadbbbb5c1c8b79de1",
          "md5": "35372df27223d5cae7c6c5bbfd7f11a0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/0.2.0-SNAPSHOT/test-util-metadata-0.2.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "0.2.0-SNAPSHOT"
      }
    }
  ]
}
