{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-SNAPSHOT/test-util-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.2.0-SNAPSHOT.klib",
          "size": 16564,
          "sha512": "8960e586d765f9deea7c3cf39719c4158174eaf73c9ed3a65d940587f810255ba6564417fda14053c1408d346f678e61fd1844091426c84d50301ed8c4c89255",
          "sha256": "12eb2c43fe5e275fdab2bc7d2a7f43ddab0bd72706314379164bc4491538da6b",
          "sha1": "da13985eea5e66c11571c21ef792d8f60f036d0f",
          "md5": "910cf550bac1f51c612225e64de375fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "test-util-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 7055,
          "sha512": "f21475fb2771c867630e319972ec5bcf84d7bbc49bfa456644f0ca3e9268aa3b96c5cbbe2d44657a1fc525d6e581ad0774574739c27e85dbd728c6f3c6cf8aab",
          "sha256": "42ab30de6b8cdbec75ebea169b5bbf130f276ea116197e25c06a456f4dc4d26c",
          "sha1": "60b10d9e5c8c492552d8e348553735aab1540287",
          "md5": "a893248d0e18d110d98ee65459d35676"
        }
      ]
    }
  ]
}
