{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "na63yrchpvcdtb4r5giuarm5sa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.0-SNAPSHOT.jar",
          "url": "securestore-common-1.13.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "29a3688446dc5625de3550710259fb763c208b14debbc0ce042aee7ab0d976c740c5e2c0776b92134ca8c5a51872fc438262bb3ddb18fd507181881f5bd457fc",
          "sha256": "28c607ccfea571c321891738982021eff111c48d6760b5e704c72c7285373426",
          "sha1": "8894d7205d80bd0212fbc7cec97f3cdd051d37db",
          "md5": "410d77922124ded9510d0a5c432a96f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.0-SNAPSHOT.jar",
          "url": "securestore-common-1.13.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "29a3688446dc5625de3550710259fb763c208b14debbc0ce042aee7ab0d976c740c5e2c0776b92134ca8c5a51872fc438262bb3ddb18fd507181881f5bd457fc",
          "sha256": "28c607ccfea571c321891738982021eff111c48d6760b5e704c72c7285373426",
          "sha1": "8894d7205d80bd0212fbc7cec97f3cdd051d37db",
          "md5": "410d77922124ded9510d0a5c432a96f6"
        }
      ]
    }
  ]
}
