{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "vyvxvbs5ljdwfckcf3iszub6xy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coroutine-util-jvm-0.1.0-SNAPSHOT.jar",
          "url": "coroutine-util-jvm-0.1.0-SNAPSHOT.jar",
          "size": 5205,
          "sha512": "b2216c63c9b55c29632fca08cad591453f5e42121fbd904602127adf2403c143d8a4130811e678f33cfa3a5b1215ba7b6d0d1d7ef355dd429de2f745b263cc99",
          "sha256": "f694a2ca64026430ac57cdf9e302d70b3fcb17b045e3c83708de8b8a48e38751",
          "sha1": "6bc2ccae77ca2cac20b048939caebe0a165e13cf",
          "md5": "54ec4b9f7afb0081e4e6e67311240744"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-jvm-0.1.0-SNAPSHOT.jar",
          "url": "coroutine-util-jvm-0.1.0-SNAPSHOT.jar",
          "size": 5205,
          "sha512": "b2216c63c9b55c29632fca08cad591453f5e42121fbd904602127adf2403c143d8a4130811e678f33cfa3a5b1215ba7b6d0d1d7ef355dd429de2f745b263cc99",
          "sha256": "f694a2ca64026430ac57cdf9e302d70b3fcb17b045e3c83708de8b8a48e38751",
          "sha1": "6bc2ccae77ca2cac20b048939caebe0a165e13cf",
          "md5": "54ec4b9f7afb0081e4e6e67311240744"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
