{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "frww6tbtmngozdpq62odvmnrma"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "5bc932e1ccb38d41b06eef4e345cda2c0c3f3e08f626ae13106f3dacc99f531565ecbadece5c4ce67f15dfa9881b91f1a3ee659456242d4fb55ec1e618cc4fde",
          "sha256": "b984650b33d3cc9bff69f390184b84dba2e880d64db0b1faf2f3b7a3c95c4ddd",
          "sha1": "099b13ad3a380edf14b506447ea6f2e242ceb40e",
          "md5": "580d9d55f2c595a9dcf4c36c9b2d3a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "5bc932e1ccb38d41b06eef4e345cda2c0c3f3e08f626ae13106f3dacc99f531565ecbadece5c4ce67f15dfa9881b91f1a3ee659456242d4fb55ec1e618cc4fde",
          "sha256": "b984650b33d3cc9bff69f390184b84dba2e880d64db0b1faf2f3b7a3c95c4ddd",
          "sha1": "099b13ad3a380edf14b506447ea6f2e242ceb40e",
          "md5": "580d9d55f2c595a9dcf4c36c9b2d3a0b"
        }
      ]
    }
  ]
}
