{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jupbzt5jpzelfhghzkqlld2fme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "e4eedc10bdf405f79c65156a76e9bcf0b21a027968cdd5af6dd58be40ef8dff3788c1c4be4097fe1e28002e5fad48d58dcd511aa6082939def3159b5a96081d9",
          "sha256": "e5273c04761e98976c8052f7e9c1faf0f12a26273e781559d49d436b56aa7f47",
          "sha1": "5baf5b35ab241e7e8d19c3bcddd1c2a587742f1c",
          "md5": "82094a746f3dfb001caa11d82dda39a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "e4eedc10bdf405f79c65156a76e9bcf0b21a027968cdd5af6dd58be40ef8dff3788c1c4be4097fe1e28002e5fad48d58dcd511aa6082939def3159b5a96081d9",
          "sha256": "e5273c04761e98976c8052f7e9c1faf0f12a26273e781559d49d436b56aa7f47",
          "sha1": "5baf5b35ab241e7e8d19c3bcddd1c2a587742f1c",
          "md5": "82094a746f3dfb001caa11d82dda39a5"
        }
      ]
    }
  ]
}
