{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sivb2qegtvd4zomr64qwvu6v7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "28b2a0c93c22bce397f38c98520aa4f5c63df1409dc7c7a20b0dadb3793fafd131edab4f77575de3746724fced67b4b3d6d666716550a3c88310911aab9dc78e",
          "sha256": "78c38455ac80f17ba1b176862f6297b3ff7f91c35a84aef252f39617c957f630",
          "sha1": "4f9a0e0b2e2e10aee6cf340b6ad8457f9a805f04",
          "md5": "8192079a04f7f74fc2ac3adebf514b3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "28b2a0c93c22bce397f38c98520aa4f5c63df1409dc7c7a20b0dadb3793fafd131edab4f77575de3746724fced67b4b3d6d666716550a3c88310911aab9dc78e",
          "sha256": "78c38455ac80f17ba1b176862f6297b3ff7f91c35a84aef252f39617c957f630",
          "sha1": "4f9a0e0b2e2e10aee6cf340b6ad8457f9a805f04",
          "md5": "8192079a04f7f74fc2ac3adebf514b3f"
        }
      ]
    }
  ]
}
