{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tavioprourgytfqzcbnqqmdeuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "3d379b17e2a2389ca0c501742c401ac40e9e52cc9d53e7109dca39e4c91b4f35b6e90cf73354cb059c1110d0cedd5402b800404231153f1d402a372cacefb818",
          "sha256": "0979e0d15eef66750cbafe05ee3896dd824fa8b7431eb8563117f24c29dec77d",
          "sha1": "104959c664804818f99d6405b00f0b4a68dc16a1",
          "md5": "def4e1e1b5ebf988e57745a235914679"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "3d379b17e2a2389ca0c501742c401ac40e9e52cc9d53e7109dca39e4c91b4f35b6e90cf73354cb059c1110d0cedd5402b800404231153f1d402a372cacefb818",
          "sha256": "0979e0d15eef66750cbafe05ee3896dd824fa8b7431eb8563117f24c29dec77d",
          "sha1": "104959c664804818f99d6405b00f0b4a68dc16a1",
          "md5": "def4e1e1b5ebf988e57745a235914679"
        }
      ]
    }
  ]
}
