{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m2pydfawtvgrhdpvxqkou5byxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "2d239f349c8715fb553173cce05bf04958f420c0055fbea2fc5d5f7dd93f550cf5d8927b6df8b26a28a66cd21c33fed756236b60f683db138099499253267f82",
          "sha256": "2e402bc13dd378eaff523a90368d5e92dbac79234bbd6736f31f53994046f78a",
          "sha1": "cb7e9a25d0fb81553e02e8d24736bc77eb9545de",
          "md5": "459883ce811c77433cf4c8ac0d418d1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "2d239f349c8715fb553173cce05bf04958f420c0055fbea2fc5d5f7dd93f550cf5d8927b6df8b26a28a66cd21c33fed756236b60f683db138099499253267f82",
          "sha256": "2e402bc13dd378eaff523a90368d5e92dbac79234bbd6736f31f53994046f78a",
          "sha1": "cb7e9a25d0fb81553e02e8d24736bc77eb9545de",
          "md5": "459883ce811c77433cf4c8ac0d418d1f"
        }
      ]
    }
  ]
}
