{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "73txki5cyfed7nskjjw3qrjhca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "97afa7a5beacde12b272e8b6431c7c94cfbb31f006a0b1566bd84271ab4f66a06ad01cc730c18b3360e6992ba52d51c5135e85a3974ceb5b0c044adcd9f54c78",
          "sha256": "36bbc9df00bfbc191dd0cdc6d03ebf0b351c3633089a7deeef26f3eedd7a0b99",
          "sha1": "ad38e98564a783d1683de41549388e8292a95f0d",
          "md5": "b15a5b419e4a106a9f3fa733d1947ea9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "97afa7a5beacde12b272e8b6431c7c94cfbb31f006a0b1566bd84271ab4f66a06ad01cc730c18b3360e6992ba52d51c5135e85a3974ceb5b0c044adcd9f54c78",
          "sha256": "36bbc9df00bfbc191dd0cdc6d03ebf0b351c3633089a7deeef26f3eedd7a0b99",
          "sha1": "ad38e98564a783d1683de41549388e8292a95f0d",
          "md5": "b15a5b419e4a106a9f3fa733d1947ea9"
        }
      ]
    }
  ]
}
