{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "auqklhvfwjbcppg4sdkxl2tqjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "b1d34638834af2a77f4ab4b68e785ad3e9c9e839733e8ac19518b323b104b99f8c118119ac541d330c377b9cdb71a619b034de1d2a35b483687c06ce8376d0fe",
          "sha256": "fd4f6f707316cad190f2039a31629319b3b0a6a7ede4ac63d2d027615c743721",
          "sha1": "20c97ffafe9ab43c34e47ee442785ed8e1223689",
          "md5": "3a0f2d85a24307bdb39d0cb2c2aae7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "b1d34638834af2a77f4ab4b68e785ad3e9c9e839733e8ac19518b323b104b99f8c118119ac541d330c377b9cdb71a619b034de1d2a35b483687c06ce8376d0fe",
          "sha256": "fd4f6f707316cad190f2039a31629319b3b0a6a7ede4ac63d2d027615c743721",
          "sha1": "20c97ffafe9ab43c34e47ee442785ed8e1223689",
          "md5": "3a0f2d85a24307bdb39d0cb2c2aae7c7"
        }
      ]
    }
  ]
}
