{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ga7ai7sd5rg2zdxgfsfxdlo5n4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "8bd6c70a65290b7868d724fb3f7240380163cb7dbf3c77d943c095aea81f6f112be187a0e82feea526cc407918b86136e16b4b6d6ebe64516b4a51c3019d4d04",
          "sha256": "04d34021054d873d62e8f759ecf2b7335cdba876c0c6d1405cbc1d24ffa5c07a",
          "sha1": "009ba881efa6f91dc474542c15f37f3ae67ffab6",
          "md5": "9f452e9cafd2526e07c645e955214983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "8bd6c70a65290b7868d724fb3f7240380163cb7dbf3c77d943c095aea81f6f112be187a0e82feea526cc407918b86136e16b4b6d6ebe64516b4a51c3019d4d04",
          "sha256": "04d34021054d873d62e8f759ecf2b7335cdba876c0c6d1405cbc1d24ffa5c07a",
          "sha1": "009ba881efa6f91dc474542c15f37f3ae67ffab6",
          "md5": "9f452e9cafd2526e07c645e955214983"
        }
      ]
    }
  ]
}
