{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ki5rrqvevg35gxnl4d7fcljl4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "f8a7906a9ed7b924370496994709817fb6eb7ccabe0a702d5ba32a8a3c21a88815a33d36312c786fa133fa8727d27711637cd10ffba0cdde07e6ca4a32fed04e",
          "sha256": "0716546b7388fceafdc8a154d4fb4072abcf9a29f017ae60d8955feb436d6fda",
          "sha1": "57ca5e8bc818eb591ff35f3ef5e07bed600fd5ee",
          "md5": "786777a90a0da2f7a0a9f443ec889838"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "f8a7906a9ed7b924370496994709817fb6eb7ccabe0a702d5ba32a8a3c21a88815a33d36312c786fa133fa8727d27711637cd10ffba0cdde07e6ca4a32fed04e",
          "sha256": "0716546b7388fceafdc8a154d4fb4072abcf9a29f017ae60d8955feb436d6fda",
          "sha1": "57ca5e8bc818eb591ff35f3ef5e07bed600fd5ee",
          "md5": "786777a90a0da2f7a0a9f443ec889838"
        }
      ]
    }
  ]
}
