{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ztmzf4nvkbaw7cjeluvubv6w6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "af64368666e91e4ab192e27a7111292d070d01add1d8b0290fc6471f83347f41aa2cd0eed7de791fe2f7f250e4710618db3123de939129b24c81e8efdd551c4a",
          "sha256": "29d5fd31aa4761172130de18af21add66194cc3aa4e61d569fef4353ddd34f8f",
          "sha1": "465a90a65bce2a5666b3f341b9cfc942ec653060",
          "md5": "2f789624fca467d5ae7389ea0869165e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "af64368666e91e4ab192e27a7111292d070d01add1d8b0290fc6471f83347f41aa2cd0eed7de791fe2f7f250e4710618db3123de939129b24c81e8efdd551c4a",
          "sha256": "29d5fd31aa4761172130de18af21add66194cc3aa4e61d569fef4353ddd34f8f",
          "sha1": "465a90a65bce2a5666b3f341b9cfc942ec653060",
          "md5": "2f789624fca467d5ae7389ea0869165e"
        }
      ]
    }
  ]
}
