{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4mrmanz6vzdhff6lk6wmolp3py"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "726c785e3f8a39dc52f5a246096f4ee0b51587288f94aa10c3b5780d88b2cf90f203db11cdaf89c7c713c53ab7adedc098d8af8b14d21af37db7dec1f996b0b5",
          "sha256": "fe0ea0bd658d907ae4aa90a05a4c0944bfa8f6283541206b493a07c8225b9fa1",
          "sha1": "5b4211bef83a9c62c58dcb16c62559e9db11837b",
          "md5": "6933ab6760e3e8015bc0d83f6f9e3e98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "726c785e3f8a39dc52f5a246096f4ee0b51587288f94aa10c3b5780d88b2cf90f203db11cdaf89c7c713c53ab7adedc098d8af8b14d21af37db7dec1f996b0b5",
          "sha256": "fe0ea0bd658d907ae4aa90a05a4c0944bfa8f6283541206b493a07c8225b9fa1",
          "sha1": "5b4211bef83a9c62c58dcb16c62559e9db11837b",
          "md5": "6933ab6760e3e8015bc0d83f6f9e3e98"
        }
      ]
    }
  ]
}
