{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "crtran7la5esrcopaux2puf4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a3eb6937fcc862416700b475b46a4c14056c6cfcf7ed50c1be66024041024a26bd74f33184b297fed00f60b1181ed09e2d859b77a50263b405e764ec8a92b70a",
          "sha256": "8d94aac3e3e2655677b97a1cda003eb1fcaae93d66b4e27c6113d58b1ea4d6f9",
          "sha1": "2226e7775ff775a72c58f6df83155abd6d7a46e8",
          "md5": "42e17da999d5760628ad4ecb92c06ef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a3eb6937fcc862416700b475b46a4c14056c6cfcf7ed50c1be66024041024a26bd74f33184b297fed00f60b1181ed09e2d859b77a50263b405e764ec8a92b70a",
          "sha256": "8d94aac3e3e2655677b97a1cda003eb1fcaae93d66b4e27c6113d58b1ea4d6f9",
          "sha1": "2226e7775ff775a72c58f6df83155abd6d7a46e8",
          "md5": "42e17da999d5760628ad4ecb92c06ef5"
        }
      ]
    }
  ]
}
