{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gmosjtalmzhnxbkkehus55gdcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a92607914b2136d89178dc6680d6c6e53f3b0807fdab73366728aeb86edb86af502e8d138800025acef2c739bbef1a9a5deb6cd4beb98295f3f60a2e567efbfb",
          "sha256": "5dea2f51bdb69fb2160d4d77a994852de754ff92fbaacc8beaa22fae9504e705",
          "sha1": "32b2fd5e8a2fe6743fbcecfe5a074f8acb49c1b8",
          "md5": "7941140bfe78db05bebcca5110c67993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "a92607914b2136d89178dc6680d6c6e53f3b0807fdab73366728aeb86edb86af502e8d138800025acef2c739bbef1a9a5deb6cd4beb98295f3f60a2e567efbfb",
          "sha256": "5dea2f51bdb69fb2160d4d77a994852de754ff92fbaacc8beaa22fae9504e705",
          "sha1": "32b2fd5e8a2fe6743fbcecfe5a074f8acb49c1b8",
          "md5": "7941140bfe78db05bebcca5110c67993"
        }
      ]
    }
  ]
}
