{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hicci6e6mnbatnxajb3zug2w7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "dc2bade3fc850b83d7015106f2c0f880f2094f28e3266bf9f37f715b40b6ca0cd448f3b4aa958a841005516865a6d98d5f43c198ad327bcf69a24052057f9432",
          "sha256": "1bc8902efdb7f9669c2be265615d06803d2e09a20ad1f908052e45aa1062f8de",
          "sha1": "94b565347ffb124924065b09705a7ae332e7c03c",
          "md5": "71a09805b25d6b351966843fe47b72f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "dc2bade3fc850b83d7015106f2c0f880f2094f28e3266bf9f37f715b40b6ca0cd448f3b4aa958a841005516865a6d98d5f43c198ad327bcf69a24052057f9432",
          "sha256": "1bc8902efdb7f9669c2be265615d06803d2e09a20ad1f908052e45aa1062f8de",
          "sha1": "94b565347ffb124924065b09705a7ae332e7c03c",
          "md5": "71a09805b25d6b351966843fe47b72f8"
        }
      ]
    }
  ]
}
