{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dduojoxfnzb5li74ou3gg4mzcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "9bd514bbc8fa33b78c4e10d153d60cbbf07affa1b245e48f7db3da55af524985cba1e82d4f23c6eabbe0ebc6c47000bf7393558f032ac69a88fe8cec562ef7bf",
          "sha256": "2a4cf73f5150e5da1cf97b0c065cefe999fd041c2447d4039760bd2dc5ccade4",
          "sha1": "ebbbf10593ba6b430442c466779b3a61af861c02",
          "md5": "9501e40df2dbff62da42e7942b1449d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "9bd514bbc8fa33b78c4e10d153d60cbbf07affa1b245e48f7db3da55af524985cba1e82d4f23c6eabbe0ebc6c47000bf7393558f032ac69a88fe8cec562ef7bf",
          "sha256": "2a4cf73f5150e5da1cf97b0c065cefe999fd041c2447d4039760bd2dc5ccade4",
          "sha1": "ebbbf10593ba6b430442c466779b3a61af861c02",
          "md5": "9501e40df2dbff62da42e7942b1449d9"
        }
      ]
    }
  ]
}
