{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqserunt6beknasoh3kvcuiywa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "faf02729afb72530a35d062067831a05459f76fa70f48425ae5737f0ae3c3ce359db0e410b8fc62224c7efbeeb5a12f844ec03cd2325cf17f3d17276558b3f2b",
          "sha256": "532e2e75dfe63751d795144fc3c18e244ea5c2298d19076276e50aeaa8df0b64",
          "sha1": "32e2328680eb38b852fc364e42e37272101ef753",
          "md5": "94b5520c0307f046268097d9cde2553c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "faf02729afb72530a35d062067831a05459f76fa70f48425ae5737f0ae3c3ce359db0e410b8fc62224c7efbeeb5a12f844ec03cd2325cf17f3d17276558b3f2b",
          "sha256": "532e2e75dfe63751d795144fc3c18e244ea5c2298d19076276e50aeaa8df0b64",
          "sha1": "32e2328680eb38b852fc364e42e37272101ef753",
          "md5": "94b5520c0307f046268097d9cde2553c"
        }
      ]
    }
  ]
}
