{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yqeqg75cbnhxtjhlowdprk37de"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "b960aa82fc59df4a40394376aec1361b703fc51273ed54d3132ce1fc2d7790b20b803cc462fd70b2d5d8eaf778c9d5dd81e098647259daae0a35d88829ecbb39",
          "sha256": "3b09de3b7b06c1a0c09ac1a50ab8949fea82fcfc428d071c039bfee8b17bec62",
          "sha1": "15442a0649689f4c0dba3a705dadca67e43fff7b",
          "md5": "f01c4e5df574bf934291c21eb3cf8969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "b960aa82fc59df4a40394376aec1361b703fc51273ed54d3132ce1fc2d7790b20b803cc462fd70b2d5d8eaf778c9d5dd81e098647259daae0a35d88829ecbb39",
          "sha256": "3b09de3b7b06c1a0c09ac1a50ab8949fea82fcfc428d071c039bfee8b17bec62",
          "sha1": "15442a0649689f4c0dba3a705dadca67e43fff7b",
          "md5": "f01c4e5df574bf934291c21eb3cf8969"
        }
      ]
    }
  ]
}
