{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nzdlny3vq5gmbk5z5jgjueypsy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7b78049d0a7bdfc8ef38a9fdd61375e320bbe215085a3c23ef06f1c029ee5de68d7162ea15aedd8a0d5b2012d85c29c97cacc7a377a35e577f6ab10919c0a6e3",
          "sha256": "6ef4fbec317465e4b3b54a941f1745d426bcc69c1585f1bb6c65b71b0b13d93e",
          "sha1": "919dae72ab79c68695fc54eefec02bf1c4d7ead4",
          "md5": "cc0c60b2978ffc5f6d30fc14bc559ee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7b78049d0a7bdfc8ef38a9fdd61375e320bbe215085a3c23ef06f1c029ee5de68d7162ea15aedd8a0d5b2012d85c29c97cacc7a377a35e577f6ab10919c0a6e3",
          "sha256": "6ef4fbec317465e4b3b54a941f1745d426bcc69c1585f1bb6c65b71b0b13d93e",
          "sha1": "919dae72ab79c68695fc54eefec02bf1c4d7ead4",
          "md5": "cc0c60b2978ffc5f6d30fc14bc559ee9"
        }
      ]
    }
  ]
}
