{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g4x2o3g47fflfm7puixnhoc67m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4678d7ddc203a7e6a88bfde3120c44ed1bc5747c6c06d12c84f41c23ec2975ec2d1470d710551ea05da258ccc626e406f78d5e79099ab930cc476883cee8b1d4",
          "sha256": "af30d92e911e3700a09f4e93facacbcb2461c4a3eeb14dacd9474203755bc3f7",
          "sha1": "02d60a4ee9493c9c986603b23eb1a8468f4fa9e2",
          "md5": "2dcf2f1c0c82993e519658d95ad4fdbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4678d7ddc203a7e6a88bfde3120c44ed1bc5747c6c06d12c84f41c23ec2975ec2d1470d710551ea05da258ccc626e406f78d5e79099ab930cc476883cee8b1d4",
          "sha256": "af30d92e911e3700a09f4e93facacbcb2461c4a3eeb14dacd9474203755bc3f7",
          "sha1": "02d60a4ee9493c9c986603b23eb1a8468f4fa9e2",
          "md5": "2dcf2f1c0c82993e519658d95ad4fdbe"
        }
      ]
    }
  ]
}
