{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hwutcwczk5farpgy42pen3pvfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "bb0360057b0b268244184bf5c8f2ebfa9cc02531c956d1267dbed5301e85f4b5781bfc38303ae0325b03c0ffc8318fd88f8b503f5f4d91e9e7b8ea33a9f68a52",
          "sha256": "8c9cb9cc2cf9338e921353051e14092ddeb9e3a5c6ea5b157a924440fb16d53a",
          "sha1": "773faf0992dae419be22a91998617b3ca1584da6",
          "md5": "66633659958e01262099947bbf834791"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "bb0360057b0b268244184bf5c8f2ebfa9cc02531c956d1267dbed5301e85f4b5781bfc38303ae0325b03c0ffc8318fd88f8b503f5f4d91e9e7b8ea33a9f68a52",
          "sha256": "8c9cb9cc2cf9338e921353051e14092ddeb9e3a5c6ea5b157a924440fb16d53a",
          "sha1": "773faf0992dae419be22a91998617b3ca1584da6",
          "md5": "66633659958e01262099947bbf834791"
        }
      ]
    }
  ]
}
