{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nsat3wzucfgbtpnq772fkmpbvq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "da7aa8b1de567dff79af5f3ec8de4cc6a1a4f1687414b6fe03d87e996195a1ca403eda55e5cc3f2fe5a89785217b677fc7fd9f24d55eedbfd2110b0376fef24c",
          "sha256": "a9c353598de12cc7e4d67832818ed1d03d1d58a3306f7d50198e6819dce9d06f",
          "sha1": "7ce4b719d2a0fc40dde43154b11d3354e646e622",
          "md5": "675de77ece1274090797c81c4a3a56a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "da7aa8b1de567dff79af5f3ec8de4cc6a1a4f1687414b6fe03d87e996195a1ca403eda55e5cc3f2fe5a89785217b677fc7fd9f24d55eedbfd2110b0376fef24c",
          "sha256": "a9c353598de12cc7e4d67832818ed1d03d1d58a3306f7d50198e6819dce9d06f",
          "sha1": "7ce4b719d2a0fc40dde43154b11d3354e646e622",
          "md5": "675de77ece1274090797c81c4a3a56a3"
        }
      ]
    }
  ]
}
