{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.8.1-SNAPSHOT/util-coroutine-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cn7y7pbly5dqffluewyd5ncn5e"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine.klib",
          "url": "util-coroutine-iosx64-1.8.1-SNAPSHOT.klib",
          "size": 8928,
          "sha512": "295415b69c6e0c12c94389a2124aba3f8c2d023034981423eb165fbd4fa02b66dfb3d495ad948799ed23cb0ec440f4a57cf2badea96103fe9cbc8a3e06ec2f3b",
          "sha256": "04c21c560031608416f313740d09b15440e0eaadf829fc95b686363d099668b2",
          "sha1": "862fddae7c575d4a03b888fd128915785c9f6d76",
          "md5": "430cb44bd7ae4574a03c0b5f2b069733"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.8.1-SNAPSHOT/util-coroutine-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
