{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.10.0-SNAPSHOT/util-1.10.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.10.0-SNAPSHOT.klib",
          "size": 24845,
          "sha512": "419f9e4dafd0913783e4a960a540b05a01e94810531221d6d5fd6c13fe7ac3dd624270e9750a17e6a209e8fd8732239f02d2118d4a713cf328ef88dfbab95ff6",
          "sha256": "1294e3a1cc79cea637b4998cb696c2a124f8fbbd8215942214e01e7f1f7bbd26",
          "sha1": "89061742449222c9b0a3d019baabfd8b05ecd9c9",
          "md5": "8a1f027a68249b7da90ec8bbf90f9dc2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.10.0-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.10.0-SNAPSHOT-metadata.jar",
          "size": 6110,
          "sha512": "25c12652dcfdb41f52fd620cf29dbae7432d0cfce9aedac0726f80a35ff1c7f2894089ce0c4eba5605d22e5fc98c079d26421e47940f95912349d0650e1910ea",
          "sha256": "f79fafcbcc71db41f27c158da385a1fa45dd4ff71e03dd9a088c6aaaffae9757",
          "sha1": "97be466eb24616426931ca6ab998b2f286352bec",
          "md5": "b56e3b356e4ac587d9f11e89c5348c3b"
        }
      ]
    }
  ]
}
