{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.10.0-SNAPSHOT/util-1.10.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "h653kn6sdjfgllphgseatgx72i"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.10.0-SNAPSHOT.klib",
          "size": 23663,
          "sha512": "0021b4dd4d39f2994b96d742da225da4e5fc5c1059283874d59261b92883b6bbe44c66092a2c79c0037ce62877b21d17a856f250db055538f4bf11fb53104cd4",
          "sha256": "4c9aac6876e28ba22edd80931bfb77f93066928bec4dc2319cf92809ab3baf13",
          "sha1": "fb1a2e220f1d8ac9d83cd3318300ea05324c68b5",
          "md5": "ed958b6682828e92a2b023218e962c26"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.10.0-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.10.0-SNAPSHOT-metadata.jar",
          "size": 5483,
          "sha512": "2881d98a51b4f61a8108277d5b58dee1623dce422230695c116851a4bc3f9f1cacf4f3878aaf1e0543879a14311db239c83b2f52e2be775cdcd95568850945bb",
          "sha256": "2c79e7cf36241f70524db79c38ef1738291c97d916afba84a4f18ec339dcea45",
          "sha1": "a0c5512e8b5977c6ad650e49c7181fea421e1e2b",
          "md5": "1c6a1e66ef31c8cf50f4f5da2590a3a4"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util/1.10.0-SNAPSHOT/util-1.10.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util",
        "version": "1.10.0-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util/1.10.0-SNAPSHOT/util-1.10.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util",
        "version": "1.10.0-SNAPSHOT"
      }
    }
  ]
}
