{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.14.0-SNAPSHOT/securestore-1.14.0-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.14.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.14.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-SNAPSHOT.jar",
          "size": 16695,
          "sha512": "efe7a11b1f9be1760348b7e123885ed898240b72977fac0e1b33d90f1c9659969d3f868165763111bb1a83b3c2e3cbcef7e3d6d4d80ea2cf22559dbf41e42cd8",
          "sha256": "24205dc5e988ce8961cd5ad169848d42c44882669f342dc5fb477b2754cf7eb0",
          "sha1": "557529f79d8e6a56f7fb98cb616023455b130d52",
          "md5": "a491959f85dce0d72eff94708e28fec4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-SNAPSHOT.jar",
          "size": 16695,
          "sha512": "efe7a11b1f9be1760348b7e123885ed898240b72977fac0e1b33d90f1c9659969d3f868165763111bb1a83b3c2e3cbcef7e3d6d4d80ea2cf22559dbf41e42cd8",
          "sha256": "24205dc5e988ce8961cd5ad169848d42c44882669f342dc5fb477b2754cf7eb0",
          "sha1": "557529f79d8e6a56f7fb98cb616023455b130d52",
          "md5": "a491959f85dce0d72eff94708e28fec4"
        }
      ]
    }
  ]
}
