{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.13.0-SNAPSHOT/error-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.13.0-SNAPSHOT.klib",
          "size": 7092,
          "sha512": "bd0613db2bcda7b4cf0f99630a2518c764b1928ccc62939e7765e388ff55281200b050e0ab975ab740c005772420b50ade6882069ef2d0a5c1b79166ba710f6e",
          "sha256": "907f86960b0b76a972fe76771d1506d917ec0bed02f01d1aab16dbaad1c360cc",
          "sha1": "25a74c3e0b97b8ad7fb8974cf0c9d389fd2ae237",
          "md5": "f8a076466dce6f04d75cbeb50784d893"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.13.0-SNAPSHOT-metadata.jar",
          "url": "error-iosarm64-1.13.0-SNAPSHOT-metadata.jar",
          "size": 5050,
          "sha512": "d36cf463f8409a854e58221fe6513ef686f536d83c4854889ec434d7eb301d1863df4b1294ca4e71d0ba9dfc66da03e7eb9c7ff7844be1e34bb0a2b6397c39ae",
          "sha256": "61aab03a7780c3966e7adf943b4390200450035974b4d881ac238c6b2436ce06",
          "sha1": "aa9017f1e4491de63bc989c781ced3b1049b7706",
          "md5": "118b012b8d40df1a7c4882ef70338816"
        }
      ]
    }
  ]
}
