{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "na63yrchpvcdtb4r5giuarm5sa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "7fc244d42487f582e8bc3d7ac540f9f26698de9dbb2eb75e5531cb812b09c5c7a6b12e8bd0e99220c5186ac078236a3d275b2d7dba35bc1c3a6d772aec84ef83",
          "sha256": "5c60e0a352c63395a24c7ca383d2990aaf7b4f1cb2162d6c0c8a6b3bf920cda4",
          "sha1": "0e676f12ebc57a3af78c1a3de4ab3da844b3b0db",
          "md5": "3cd165c9378dd4a1008cb31185c55c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "7fc244d42487f582e8bc3d7ac540f9f26698de9dbb2eb75e5531cb812b09c5c7a6b12e8bd0e99220c5186ac078236a3d275b2d7dba35bc1c3a6d772aec84ef83",
          "sha256": "5c60e0a352c63395a24c7ca383d2990aaf7b4f1cb2162d6c0c8a6b3bf920cda4",
          "sha1": "0e676f12ebc57a3af78c1a3de4ab3da844b3b0db",
          "md5": "3cd165c9378dd4a1008cb31185c55c0b"
        }
      ]
    }
  ]
}
