{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor-jvm/0.1.0-SNAPSHOT/test-util-ktor-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "o6qgyozkmvccnoqpwowe5wuqmu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-metadata-0.1.0-SNAPSHOT.jar",
          "size": 3186,
          "sha512": "e53a38ef58a3daed02e128d8ed6a7259c0f945b2c64b94cd22dd6d95c9da2e198e2933c3dc70a01a1310be5eba66d8c7de28843bc3b55368df091dff1a0ad496",
          "sha256": "74c9f8b9b24f960e67b72b5a5431c6a8b2e74d3794f0a0bcb326a5ee4c6111ab",
          "sha1": "fa4336a051dc8ace8d8b8e3b28535c19504868cf",
          "md5": "f8f791414067fd338c3147e3dc89986f"
        }
      ]
    }
  ]
}
