{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor-jvm/0.1.0-SNAPSHOT/test-util-ktor-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bot2frffn5g77hogmls7z2hq4i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-0.1.0-SNAPSHOT.jar",
          "url": "test-util-ktor-metadata-0.1.0-SNAPSHOT.jar",
          "size": 3186,
          "sha512": "4106ceecba73890771b32f4b69ff8245114d12d382fac76fb4bdf1c0407984a40970c5189ea8f8435eda3ee6d0db8b1b1f080813537f4b575b862a55ee5bb42d",
          "sha256": "20b3bbce3e3c4207ab7517029d7899bedc8968224259a5b852f461aa553c6dfc",
          "sha1": "f67a429296e14760dc6b312e55ee35f36c7ff958",
          "md5": "db9e712cb2bfde2fe796f62d35c9a11e"
        }
      ]
    }
  ]
}
