{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.14.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-metadata-1.14.0-SNAPSHOT.jar",
          "url": "auth-1.14.0-SNAPSHOT.jar",
          "size": 3762,
          "sha512": "00f82aa3ec7ed5b77a228528ccb834dfa5e11b668e8160b05b454965571e747b1e78bd8d1f00a6952c2cdf2d19931ca64d74128a120d30c568390864bebf222d",
          "sha256": "e4816fa194f6b1e1cc1346a84c63b81e724568df0d2f557a03254416831e4f09",
          "sha1": "f6b12157d09475f24da6ae82b17050fec8af6569",
          "md5": "9c89a2dc431495debef30394d798a813"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.14.0-SNAPSHOT/auth-android-debug-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.14.0-SNAPSHOT/auth-android-debug-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.14.0-SNAPSHOT/auth-android-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.14.0-SNAPSHOT/auth-android-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.14.0-SNAPSHOT/auth-jvm-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.14.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.14.0-SNAPSHOT/auth-jvm-1.14.0-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.14.0-SNAPSHOT"
      }
    }
  ]
}
