{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qlgearrk4vexthlm7fxtai5hci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "b39eaad7da6b598637c95c5469bd03071180aa29341fd52325dad163937731ced5d4655afed670dfbcd91c65c33d371f366495b1a67290ee08ec690192825392",
          "sha256": "7194de8577ea6aa7f8b7ecebc785159c6e7dd647230b01f1ee798e7b664b03a9",
          "sha1": "98a6d1fcfbedb8944239a1185e9eb76c96e6d234",
          "md5": "f7f78a098ddcc1e95f3ceb4100807f06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "b39eaad7da6b598637c95c5469bd03071180aa29341fd52325dad163937731ced5d4655afed670dfbcd91c65c33d371f366495b1a67290ee08ec690192825392",
          "sha256": "7194de8577ea6aa7f8b7ecebc785159c6e7dd647230b01f1ee798e7b664b03a9",
          "sha1": "98a6d1fcfbedb8944239a1185e9eb76c96e6d234",
          "md5": "f7f78a098ddcc1e95f3ceb4100807f06"
        }
      ]
    }
  ]
}
