{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cdfwhwvegvgfnmhtly3plx3hyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "e8d5652c7ef1c69145ce2f89557c52888598512a94329c8da3004aa0e5e4a3e37570baa7a7b6767a2fadb760b6c8faab77efd234b10b24b87f6efd328d3dd2b1",
          "sha256": "227be1f74a1d5a15ec369304a9aea68fd1969b34dbf47b52a9b2de7403b86ca1",
          "sha1": "4cadd2d0ae0c0a45d29d7e1e854d0b222210c857",
          "md5": "8465bc0513bcd12715ddcf7b0c4250a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "e8d5652c7ef1c69145ce2f89557c52888598512a94329c8da3004aa0e5e4a3e37570baa7a7b6767a2fadb760b6c8faab77efd234b10b24b87f6efd328d3dd2b1",
          "sha256": "227be1f74a1d5a15ec369304a9aea68fd1969b34dbf47b52a9b2de7403b86ca1",
          "sha1": "4cadd2d0ae0c0a45d29d7e1e854d0b222210c857",
          "md5": "8465bc0513bcd12715ddcf7b0c4250a4"
        }
      ]
    }
  ]
}
