{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-SNAPSHOT/util-ktor-test-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "o7x552nqarhb5g27r4i3vzsh4i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "4ae457f916e144949f09ffee73cca4a9eb9bdaf4c7a29583a5232fa23340968287ffee920e686a350b282717e8ccac2003f061116748a4d9ceb01a3b7326a3e5",
          "sha256": "f5916e88e012dcf72059f06cc84d238c6306011c390d376a9e5b688539cebb48",
          "sha1": "a7a8a7608366f8721d1bc9f33fa868fa0fa48079",
          "md5": "0e8f39f1c40483932a2801f0bdb15e3c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "4ae457f916e144949f09ffee73cca4a9eb9bdaf4c7a29583a5232fa23340968287ffee920e686a350b282717e8ccac2003f061116748a4d9ceb01a3b7326a3e5",
          "sha256": "f5916e88e012dcf72059f06cc84d238c6306011c390d376a9e5b688539cebb48",
          "sha1": "a7a8a7608366f8721d1bc9f33fa868fa0fa48079",
          "md5": "0e8f39f1c40483932a2801f0bdb15e3c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-SNAPSHOT/util-ktor-test-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
