{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-SNAPSHOT/util-ktor-test-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cn7y7pbly5dqffluewyd5ncn5e"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "f46e4acf4c0ae4e509999279faa686136fae210233b7355e49de9cea2591967bd3b7ee8fea25b1396ddf2c2136cb92bea2dd5fc877063354b46622c8d2db8efe",
          "sha256": "a0350e9c0a1044e2e5324dc1810e4d5424cf159e02d23cf3164e9fb93b9a380d",
          "sha1": "289abcb95c5f4eadb8d429f22bd16582b3efd4df",
          "md5": "eb66cbc78c2e8cde6734ddd79182f963"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "f46e4acf4c0ae4e509999279faa686136fae210233b7355e49de9cea2591967bd3b7ee8fea25b1396ddf2c2136cb92bea2dd5fc877063354b46622c8d2db8efe",
          "sha256": "a0350e9c0a1044e2e5324dc1810e4d5424cf159e02d23cf3164e9fb93b9a380d",
          "sha1": "289abcb95c5f4eadb8d429f22bd16582b3efd4df",
          "md5": "eb66cbc78c2e8cde6734ddd79182f963"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-SNAPSHOT/util-ktor-test-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
