{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bqk6vzudjrhuzk3twx7xlzfexi"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "example-kmp-library-release.aar",
          "url": "example-kmp-library-android-0.0.1-SNAPSHOT.aar",
          "size": 14865,
          "sha512": "a31835e29cd73044c4fa678402c86b6d41f1f6644f066f24004a2f8e2666b8d7868158da474eb7f347161de4338589f3228063847b998ee573fdf9f2ad1e17c6",
          "sha256": "e9dcdfbca5061543e5907e5b7f24b5b56a62a836ce55756121ac551e6cd2aa09",
          "sha1": "727c138618b6504e601c6653dbd70dd838842667",
          "md5": "fca3b54782b1e538217cacacb082432b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-release.aar",
          "url": "example-kmp-library-android-0.0.1-SNAPSHOT.aar",
          "size": 14865,
          "sha512": "a31835e29cd73044c4fa678402c86b6d41f1f6644f066f24004a2f8e2666b8d7868158da474eb7f347161de4338589f3228063847b998ee573fdf9f2ad1e17c6",
          "sha256": "e9dcdfbca5061543e5907e5b7f24b5b56a62a836ce55756121ac551e6cd2aa09",
          "sha1": "727c138618b6504e601c6653dbd70dd838842667",
          "md5": "fca3b54782b1e538217cacacb082432b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
