{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "example-kmp-library-release.aar",
          "url": "example-kmp-library-android-0.0.1-SNAPSHOT.aar",
          "size": 14770,
          "sha512": "c0586a7ae1d75f47b6639ba277c4d4eb5676f8277d85537503254ad9973e6e74b9b1fcf941e2ad8f55a4a9a5448d052ccf9be367624e402c6764e6d6028479fa",
          "sha256": "28bc69b270d241e85bac124d259ca6f493f6a0f5ebf28c379dca705dc5a6109f",
          "sha1": "532c0c4a246e1c47fc34f35ccabc20f6cb0159f0",
          "md5": "633aaf52e3555eea62db53c8312b7839"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-release.aar",
          "url": "example-kmp-library-android-0.0.1-SNAPSHOT.aar",
          "size": 14770,
          "sha512": "c0586a7ae1d75f47b6639ba277c4d4eb5676f8277d85537503254ad9973e6e74b9b1fcf941e2ad8f55a4a9a5448d052ccf9be367624e402c6764e6d6028479fa",
          "sha256": "28bc69b270d241e85bac124d259ca6f493f6a0f5ebf28c379dca705dc5a6109f",
          "sha1": "532c0c4a246e1c47fc34f35ccabc20f6cb0159f0",
          "md5": "633aaf52e3555eea62db53c8312b7839"
        }
      ]
    }
  ]
}
