{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0-SNAPSHOT/test-util-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.3.0-SNAPSHOT.jar",
          "size": 12827,
          "sha512": "20f5f9501b9976bb374d405228b11172f534c64a282a96c96f6b36088a7ba3ad8754a0a487b38485296bce1d8ccc7e05d53b8550fd1bc6b93168c7ef5c517aa7",
          "sha256": "fc83bf30fab97506a73151c29b8abebdb4e18c6e5b65f095d01bb739f4778060",
          "sha1": "c2cf85fdc42e71dcb2e9fab8ce24ac431c9af58d",
          "md5": "1f499eba43bfacf347b063ae98acf907"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.3.0-SNAPSHOT.jar",
          "size": 12827,
          "sha512": "20f5f9501b9976bb374d405228b11172f534c64a282a96c96f6b36088a7ba3ad8754a0a487b38485296bce1d8ccc7e05d53b8550fd1bc6b93168c7ef5c517aa7",
          "sha256": "fc83bf30fab97506a73151c29b8abebdb4e18c6e5b65f095d01bb739f4778060",
          "sha1": "c2cf85fdc42e71dcb2e9fab8ce24ac431c9af58d",
          "md5": "1f499eba43bfacf347b063ae98acf907"
        }
      ]
    }
  ]
}
