{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fkqubytb45fzxjhcu6mjqio2ui"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "size": 39147,
          "sha512": "945bbdf3dc55fff4454dfdf54929c9615063062e7ba2506a258cc617802ee6ef98dfdb9c355472db004c289781cdb62f1768e79a53ed3ee598e0030fc692f56b",
          "sha256": "176e51ad350853171ef11a2ce0c80ed92296e2bc1e559b3de96509059688eee8",
          "sha1": "eab3755d40aefcce055b47040ba54b775f455c99",
          "md5": "c7c7cd366b6ae243976a9c5f20c654bf"
        }
      ]
    }
  ]
}
