{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "coll5sb6d5c7pk54ebar4sqf6i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "abfaffc9fd76879bfb4d9814ae58d67f8b58df7e7235ed10a94d42504621a7c14b473e84514ab932ab720466d2d986cfaa7fa10423c514fbaeecca5a7a2b704f",
          "sha256": "d4904f504310b2732cc57d212b791750491ef20654f7603ff350f6a8f8f254fa",
          "sha1": "086d9d1e9be7760c41c6879be327f342ceb9212d",
          "md5": "f8b2c1df64387aa7920e923ff911f12e"
        }
      ]
    }
  ]
}
