{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5mdom3gqzrb5lkkn3by5xnbkgq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "size": 39250,
          "sha512": "472b99f4c600b8e2965359efdfe34f033573a4d94a8cb66d0383b7d6100286ad7903303661586e32b08fd6f972d9e8fecc15ff173994ed71fbcabc0fc860d5c3",
          "sha256": "b50f4f9f054aac1573eee9296de18dea98e818ebed1433b968085a1e6905eda8",
          "sha1": "0ea23f5e49bdf9ba60b64ab3496d466d8dec4edf",
          "md5": "7dabe6dfc98c21cd923d8b85160473c6"
        }
      ]
    }
  ]
}
