{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wk76drgjqjcw7pj3vrt6akhz3y"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "size": 39250,
          "sha512": "4c059170ee307c724d61150f3293ae337613afabc0e9dc2d4b66a005c68d7806652c921373be895c7282c6ae5835001e887550f48f13bf5c6421b8352d7d0400",
          "sha256": "ed5782d0033274b2e5b3a77c23d9d681c0fde512034763e3865ae240427c2574",
          "sha1": "83b6e9a2fa4ba81f67603b77ecb9a1665c94addc",
          "md5": "96a1c384258a6f49de0276396f854f6b"
        }
      ]
    }
  ]
}
