{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.4.1-SNAPSHOT/test-util-ktor-0.4.1-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT.klib",
          "size": 15772,
          "sha512": "e8cfcf34869e3bbd205bf4871362cae0f70555f3fc2a203063f6f80e29b47e7cbed06ef904c18027610a779232f65f46ad32f0c788101d1178af0133399a0497",
          "sha256": "640de9ad2f664cc8515e5992d5600f8ee9428442f762b32ad2afc7cc9c12c616",
          "sha1": "835dde8e84698a54ef79ba4aa97355da630f6e07",
          "md5": "eeab497d7bac5d84b3a32b75402288fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6bf0c98e739c113121eef952c6a4a26441358a5e784059da8a9f8760c0c36130079c3843ed5f0a7766343e593c07627630549d182de65c142dc05aab073984d6",
          "sha256": "92cd0359d7c8cd25f565db599c65c99481f366d055a31b8b22831b02ef09c6f8",
          "sha1": "30acd3628edf2715afc5cd7654c6cb3c827ddf6e",
          "md5": "183679e3e34b2f1e8ef7fa6f756324b7"
        }
      ]
    }
  ]
}
