{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.4.1-SNAPSHOT/test-util-ktor-0.4.1-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT.klib",
          "size": 15772,
          "sha512": "e8cfcf34869e3bbd205bf4871362cae0f70555f3fc2a203063f6f80e29b47e7cbed06ef904c18027610a779232f65f46ad32f0c788101d1178af0133399a0497",
          "sha256": "640de9ad2f664cc8515e5992d5600f8ee9428442f762b32ad2afc7cc9c12c616",
          "sha1": "835dde8e84698a54ef79ba4aa97355da630f6e07",
          "md5": "eeab497d7bac5d84b3a32b75402288fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c271d80b0d82b03d2f2e2a71a21ea690c8a4ae6f10ca666c1635e241ea1f7856fd3363d0ebd97faf7467f2d22af3b91e63e3a13519ef254a15237132d5d5c25d",
          "sha256": "7dddb87f03687664b8081bfb7d99d44dad7d68091218b9acce1b5b7c9386d7f6",
          "sha1": "1f949233b2261b14d90f3aaa647e072421744de9",
          "md5": "b829dab22d38f6b59a3bdf05c64d885a"
        }
      ]
    }
  ]
}
