{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cx65bhetunaoxfxltujfxjmqbu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.13.2-SNAPSHOT.aar",
          "url": "crypto-android-1.13.2-SNAPSHOT.aar",
          "size": 62239,
          "sha512": "1378df1ebbe06c058dee5e33f534990d6d5b0febe7a88d2718047ae3af588cf421e0c22abf9313538bf65d31477ec567e5044df416997b752ffcb8082e708000",
          "sha256": "1a912fd5942f10817659658ca9e53070272dd434660bc8855da4e6e97e2f055e",
          "sha1": "c95a94e5b41fc9799013face4503fedad3107540",
          "md5": "c7e37a26003c6bc0899b5abd0685ef5d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.13.2-SNAPSHOT.aar",
          "url": "crypto-android-1.13.2-SNAPSHOT.aar",
          "size": 62239,
          "sha512": "1378df1ebbe06c058dee5e33f534990d6d5b0febe7a88d2718047ae3af588cf421e0c22abf9313538bf65d31477ec567e5044df416997b752ffcb8082e708000",
          "sha256": "1a912fd5942f10817659658ca9e53070272dd434660bc8855da4e6e97e2f055e",
          "sha1": "c95a94e5b41fc9799013face4503fedad3107540",
          "md5": "c7e37a26003c6bc0899b5abd0685ef5d"
        }
      ]
    }
  ]
}
