{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-objc-util-kmp",
    "module": "objc-util",
    "version": "7d1124b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ahdv3iseczasdgttuivbnwh5tm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "objc-util-metadata-7d1124b.jar",
          "url": "objc-util-7d1124b.jar",
          "size": 261,
          "sha512": "994b4f1035fa0b5a02782fc023fa741594b4d9a9a7282799a49dfa1c6f78cabb39928b7082752f07093acc9cad7ce87e12498baa7ae505c444d9250bc50eb8d2",
          "sha256": "9d241570c8c733672c5fcab67f91587b82b5abbd819037a6c2f923d40de5125e",
          "sha1": "fd4c27f889fdb5cd925bed8181932addb3e0c251",
          "md5": "49724add0e229f26fc2cd538c647a9b6"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosarm64/7d1124b/objc-util-iosarm64-7d1124b.module",
        "group": "care.data4life.hc-objc-util-kmp",
        "module": "objc-util-iosarm64",
        "version": "7d1124b"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosx64/7d1124b/objc-util-iosx64-7d1124b.module",
        "group": "care.data4life.hc-objc-util-kmp",
        "module": "objc-util-iosx64",
        "version": "7d1124b"
      }
    }
  ]
}
