{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "256jr4mkzfav3h7gbgf2lkjlwu"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.1.0-SNAPSHOT.aar",
          "size": 2184089,
          "sha512": "0c3db9e912a7e24898b16ade49f50c5b7a76e8a5d0f790186211ec776e564b6cca797690b2259cda470c26197dee402fa2c4f17a67b569ba3a986a95cb84348f",
          "sha256": "32f575542c5ca9db6c24db6c242114ff872133e58020bb680c5f98161b314093",
          "sha1": "685a326718ae94d0459b78bc79406c6c91e3e711",
          "md5": "4b14d943f8e673d282b4d3b7888c54d2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.1.0-SNAPSHOT.aar",
          "size": 2184089,
          "sha512": "0c3db9e912a7e24898b16ade49f50c5b7a76e8a5d0f790186211ec776e564b6cca797690b2259cda470c26197dee402fa2c4f17a67b569ba3a986a95cb84348f",
          "sha256": "32f575542c5ca9db6c24db6c242114ff872133e58020bb680c5f98161b314093",
          "sha1": "685a326718ae94d0459b78bc79406c6c91e3e711",
          "md5": "4b14d943f8e673d282b4d3b7888c54d2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
