{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.1.0-SNAPSHOT.aar",
          "size": 14484912,
          "sha512": "aa63a0ba31ba89e617978a225f2fcff82f784a9c285ce8b7580d83a040b4d231c1aa2a538f5a739ba889e5e4164f9db19aac3b6bcd59d41666db17a99ae79b16",
          "sha256": "ddcb66d793aaab61c3e471ed2e37f8a02db3316e446f95a30305b0e764930727",
          "sha1": "43a31b937a30e0431d96e21d081b632d1e4f9e6b",
          "md5": "f1ff8c2da8ca32097bdfcba43f681a00"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.1.0-SNAPSHOT.aar",
          "size": 14484912,
          "sha512": "aa63a0ba31ba89e617978a225f2fcff82f784a9c285ce8b7580d83a040b4d231c1aa2a538f5a739ba889e5e4164f9db19aac3b6bcd59d41666db17a99ae79b16",
          "sha256": "ddcb66d793aaab61c3e471ed2e37f8a02db3316e446f95a30305b0e764930727",
          "sha1": "43a31b937a30e0431d96e21d081b632d1e4f9e6b",
          "md5": "f1ff8c2da8ca32097bdfcba43f681a00"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
