{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.5.0-SNAPSHOT/fhir-helper-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gndhex6c6rci5pvscc5m523zlq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113561,
          "sha512": "266402504fc767f960090c812599efb32fcfe154abe575adc8d5c9edeb0b9c2682fdfc2a4f24edc608fcf0b84a25021fba688b57ea99cbced3cba222b819e35a",
          "sha256": "7dbed30b6917e6f55b487be1966d35e8b0c648e87501d78b004438eb7b2119fa",
          "sha1": "31904e30f7efa13e05352ab6362000d8685f5541",
          "md5": "de96bd8ac05a1ae16e4c69a15fad3c1e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113561,
          "sha512": "266402504fc767f960090c812599efb32fcfe154abe575adc8d5c9edeb0b9c2682fdfc2a4f24edc608fcf0b84a25021fba688b57ea99cbced3cba222b819e35a",
          "sha256": "7dbed30b6917e6f55b487be1966d35e8b0c648e87501d78b004438eb7b2119fa",
          "sha1": "31904e30f7efa13e05352ab6362000d8685f5541",
          "md5": "de96bd8ac05a1ae16e4c69a15fad3c1e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.5.0-SNAPSHOT/fhir-helper-metadata-1.5.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
