{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.5.0-SNAPSHOT/fhir-helper-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "skgm4l26kve7finkndkfesclri"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113561,
          "sha512": "6eb4fa0b642366d957d7f9139ac0cab546fc1fc03dd3d08cb184db6ce5eb2c2d936562e48ac7a326ae6d064dbe0048085d9e0410804b3a106fd4ef92a7041557",
          "sha256": "62e9c6625ab7d0b6e770aeb88d876e5717f862995941a47287ed227d223a9b7e",
          "sha1": "c18a92a052bf9b5ee4d67ac7d066e82b4a2fc9ba",
          "md5": "0356970b51f4d140e1e78f43afd24fab"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113561,
          "sha512": "6eb4fa0b642366d957d7f9139ac0cab546fc1fc03dd3d08cb184db6ce5eb2c2d936562e48ac7a326ae6d064dbe0048085d9e0410804b3a106fd4ef92a7041557",
          "sha256": "62e9c6625ab7d0b6e770aeb88d876e5717f862995941a47287ed227d223a9b7e",
          "sha1": "c18a92a052bf9b5ee4d67ac7d066e82b4a2fc9ba",
          "md5": "0356970b51f4d140e1e78f43afd24fab"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.5.0-SNAPSHOT/fhir-helper-metadata-1.5.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
