{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0-SNAPSHOT/util-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.13.0-SNAPSHOT.jar",
          "url": "util-jvm-1.13.0-SNAPSHOT.jar",
          "size": 15430,
          "sha512": "161977b47256d6fd99df944c8040aea1eb5c6683365717c02be340699374aa726a59f62dbf9fbca6b1e95038fbaaa143f929378e149eb0daf5767c674ce00572",
          "sha256": "b77e7216aa43b1fca937c4b57677efc2ef68a2f90fb4796f9f18c4a3ef078428",
          "sha1": "01953301dd13a7b3ea72eb70f8a457030e24ff31",
          "md5": "8d004e6c7985b7efd7955d9ca4fcdd5f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.13.0-SNAPSHOT.jar",
          "url": "util-jvm-1.13.0-SNAPSHOT.jar",
          "size": 15430,
          "sha512": "161977b47256d6fd99df944c8040aea1eb5c6683365717c02be340699374aa726a59f62dbf9fbca6b1e95038fbaaa143f929378e149eb0daf5767c674ce00572",
          "sha256": "b77e7216aa43b1fca937c4b57677efc2ef68a2f90fb4796f9f18c4a3ef078428",
          "sha1": "01953301dd13a7b3ea72eb70f8a457030e24ff31",
          "md5": "8d004e6c7985b7efd7955d9ca4fcdd5f"
        }
      ]
    }
  ]
}
