{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0-SNAPSHOT/util-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.13.0-SNAPSHOT.jar",
          "url": "util-jvm-1.13.0-SNAPSHOT.jar",
          "size": 15430,
          "sha512": "8fea5dd6d422cd0309a24ff61115ff658148b06256a6bb02e252d6a4b8dd33a89e4099fe44333f22d3aff9e679c0e2c955d5cde37ac7504a81d9176b185d869a",
          "sha256": "323360b991bb3f107467f3b28e535914694ee5c740b93f5650d6f8d1de7533dd",
          "sha1": "45ddf01cdb8325098e5f7f34b37b1ab39e2ce622",
          "md5": "056d93b255a9d0c30f69cb915a88d62c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.13.0-SNAPSHOT.jar",
          "url": "util-jvm-1.13.0-SNAPSHOT.jar",
          "size": 15430,
          "sha512": "8fea5dd6d422cd0309a24ff61115ff658148b06256a6bb02e252d6a4b8dd33a89e4099fe44333f22d3aff9e679c0e2c955d5cde37ac7504a81d9176b185d869a",
          "sha256": "323360b991bb3f107467f3b28e535914694ee5c740b93f5650d6f8d1de7533dd",
          "sha1": "45ddf01cdb8325098e5f7f34b37b1ab39e2ce622",
          "md5": "056d93b255a9d0c30f69cb915a88d62c"
        }
      ]
    }
  ]
}
