{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.13.0-SNAPSHOT/error-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosx64-1.13.0-SNAPSHOT.klib",
          "size": 7076,
          "sha512": "b546aeca485ff79ce297f8e21621b9d09644d6d03f025d0fd2ffd3bfb8ebd100640cfa9104bb8c7ae9b90c53e89df9903151cd4d28dc94f0421ce830dbf4a716",
          "sha256": "fdc476c2d0f47659e23961b5303cd98e82b2f29d89ab5c73d1d5a2038aff2d14",
          "sha1": "1bdf29866dac1f9dee9c75b7f83382f529c920e6",
          "md5": "b9cb2fa35514ac6503837ab344fc834f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosx64-1.13.0-SNAPSHOT-metadata.jar",
          "url": "error-iosx64-1.13.0-SNAPSHOT-metadata.jar",
          "size": 5050,
          "sha512": "038576d68f22ee18d5786ac34100bc0d48cb13cbfa15926a53e1ca2fc7da34d3bea22467e2c384fb297719c0f9a99c752378d65d32ea35be24d73713db6197e3",
          "sha256": "1db553415230bd5092ee9f4ab1c41820716d78b9e756f36fa48b80cd7c18db93",
          "sha1": "6fd612bb18bf464b306bce4c0a8c5f16d0d39643",
          "md5": "edfe296d83c9d91b1da8ef122f202f3f"
        }
      ]
    }
  ]
}
