{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qlgearrk4vexthlm7fxtai5hci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "2f7593497facfaaac921d3e0b6fb523e1ff5b86129ce7ad94e8695eae0d5b736ca4bb8fc5f7f954e6dcde7d9cfca6efe090a9123708190e3d04887a0f935cffa",
          "sha256": "35ca19d38e88044392b026c809def9cf1c7894c20e4b7894aacfae8017ae1511",
          "sha1": "d0b149dd08fbd8f3866cdb0555385b3eec87fc48",
          "md5": "5febfb62bedd90bcdd767079baf59b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "2f7593497facfaaac921d3e0b6fb523e1ff5b86129ce7ad94e8695eae0d5b736ca4bb8fc5f7f954e6dcde7d9cfca6efe090a9123708190e3d04887a0f935cffa",
          "sha256": "35ca19d38e88044392b026c809def9cf1c7894c20e4b7894aacfae8017ae1511",
          "sha1": "d0b149dd08fbd8f3866cdb0555385b3eec87fc48",
          "md5": "5febfb62bedd90bcdd767079baf59b26"
        }
      ]
    }
  ]
}
