{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-SNAPSHOT/test-util-coroutine-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT.klib",
          "size": 8272,
          "sha512": "4c3c4a90602d30707b1eb3165a58fdf92a0ec63bbcdcbda20826d498049ad65d1696b02722ea05ca9b73ac70fbbc275042669ccdcb9b650cc395bc4cfb289fb3",
          "sha256": "a2b518d7a6d40a40e6f1e86c9f094ede222be6f1b9d7d640988e0f471f0b1029",
          "sha1": "361236d351c6a2be889f858eafc5c692bfe5821d",
          "md5": "16df4621e58ddbf50aa30316055997b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "932d95a2da9505ece10a77ead213349a3ddfdc9e6cc75079c098d04d99be8db4ca478eaa5b1395f6d02f158545a19a8e3fff9cf97d0a81c8b53c91c2fd347808",
          "sha256": "53772d2f1ab1f0b8221a2c07d5c8328f26ef125783a45d866814e916444d4c51",
          "sha1": "fc7cab8e83719bd88200551eccf8fbe19d9f39e8",
          "md5": "96fd0b2df65f63fb485989206a27cade"
        }
      ]
    }
  ]
}
