{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-SNAPSHOT/test-util-coroutine-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT.klib",
          "size": 8272,
          "sha512": "4c3c4a90602d30707b1eb3165a58fdf92a0ec63bbcdcbda20826d498049ad65d1696b02722ea05ca9b73ac70fbbc275042669ccdcb9b650cc395bc4cfb289fb3",
          "sha256": "a2b518d7a6d40a40e6f1e86c9f094ede222be6f1b9d7d640988e0f471f0b1029",
          "sha1": "361236d351c6a2be889f858eafc5c692bfe5821d",
          "md5": "16df4621e58ddbf50aa30316055997b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "c25579ffc90756a8c9fe2877843bc197e9f9b9aa8b68aaf9a4b4489451938017353dac4fcccd239c29efb5f1196545c5d58870de0402a0465db88349dcc168cf",
          "sha256": "0541bd997399262c7a1af551eabb636e58d73c6f5e96a2f36b5f2a11794dd734",
          "sha1": "09183a97e0178190a67513babc24a99c6b0803f3",
          "md5": "4e9d4297d367a32c5bcfe57167657d1b"
        }
      ]
    }
  ]
}
