{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.7.0-SNAPSHOT/util-test-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g4wfrskl5bd47goxnsdrkrp45i"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "util-test.klib",
          "url": "util-test-iosarm64-1.7.0-SNAPSHOT.klib",
          "size": 7066,
          "sha512": "7fd92c03c1694f893bc92dde20536b844104d68d45367b212f87b6dd19bc464fdcdf0d295220a759c0d853ac5b60534a75e87de2fb09a0aa74134a2dd21b1a1b",
          "sha256": "33513ddd7919b60a80bcaf0798c95722cb4f1448bbdcb290b4ff97b5edf3fb76",
          "sha1": "c3bf1e59a79c75d29aae25a7addb35e665323015",
          "md5": "2f7705bcd08ee5ff285550e3dc464c96"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.7.0-SNAPSHOT/util-test-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
