{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine-jvm/0.1.0-SNAPSHOT/test-util-coroutine-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "wvmegi33jnghnejebyykh7a7si"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.1.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-metadata-0.1.0-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "6d26f5968f248cb932960bfdf45656ffcd29c360f83890f54207bb7d26dfe4833089d78152532694e2ba23f4ec20b207603bad7d38bf2e88f5f44a8d83e82593",
          "sha256": "61f3c567eba0e58f4e54e5da8643dcfcd1d5668e3ccec82162f267143f5a027e",
          "sha1": "7215d4bdb34ce8f682ce8b86debc2cf6fdb53d4d",
          "md5": "d1b33675fd170b48080104c9f91b777a"
        }
      ]
    }
  ]
}
