{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n2g3z3c4ejfnpmwgn7cyvo5rmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ed08239af439b94fd6182a3340e5e32595586035e49094093fb69b6e04c121226ae25b4833efdace8af09265125d3e6f2288d8831c278c7ebdc2b656297e157f",
          "sha256": "ef04f4aa988d6398b1756603dea15dad93d4609ee9d29a4193c17189b76671d4",
          "sha1": "f48d801e19298258107ec5d4c4f8b981eaf52d4f",
          "md5": "8d09140fd3ecf6f9c4244153a8305246"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ed08239af439b94fd6182a3340e5e32595586035e49094093fb69b6e04c121226ae25b4833efdace8af09265125d3e6f2288d8831c278c7ebdc2b656297e157f",
          "sha256": "ef04f4aa988d6398b1756603dea15dad93d4609ee9d29a4193c17189b76671d4",
          "sha1": "f48d801e19298258107ec5d4c4f8b981eaf52d4f",
          "md5": "8d09140fd3ecf6f9c4244153a8305246"
        }
      ]
    }
  ]
}
