{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ki5rrqvevg35gxnl4d7fcljl4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "813f864ec3966f16e2e3097fa126b44e8882b0cef1b3f46e38e7b46dac185adf034e453a603d00f39b46f4fc1722a407c631c4f29399f4dcc14efd6af0a51a18",
          "sha256": "67aea67fdcb5724dff3decc3a9fd4903dc06202d8930112aa046d11d5b3be9e6",
          "sha1": "70117ffe027cefdb9dea05bfa72e7786abc6ea15",
          "md5": "190714b348282cfbef8d876bf84ca200"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "813f864ec3966f16e2e3097fa126b44e8882b0cef1b3f46e38e7b46dac185adf034e453a603d00f39b46f4fc1722a407c631c4f29399f4dcc14efd6af0a51a18",
          "sha256": "67aea67fdcb5724dff3decc3a9fd4903dc06202d8930112aa046d11d5b3be9e6",
          "sha1": "70117ffe027cefdb9dea05bfa72e7786abc6ea15",
          "md5": "190714b348282cfbef8d876bf84ca200"
        }
      ]
    }
  ]
}
