{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lenvfmshubfgpfcwxttldlaas4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "597c62563b60add97a3824e20e096c53ead423989b9c60b5c309638d0e0fc7e70684b2181e78e478394c4b9f000de0893ccc5f9bc02e5c6531200b1b1f82b23e",
          "sha256": "20d97c3a7731eb29e283f97b5d294c04257e31822e7f7f343e7ab92eb3640fe1",
          "sha1": "0ba5b1d123f14db8a892799f4c84e890b27aee5b",
          "md5": "acfa0a2f606f08ca4b5144168b1a1470"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "597c62563b60add97a3824e20e096c53ead423989b9c60b5c309638d0e0fc7e70684b2181e78e478394c4b9f000de0893ccc5f9bc02e5c6531200b1b1f82b23e",
          "sha256": "20d97c3a7731eb29e283f97b5d294c04257e31822e7f7f343e7ab92eb3640fe1",
          "sha1": "0ba5b1d123f14db8a892799f4c84e890b27aee5b",
          "md5": "acfa0a2f606f08ca4b5144168b1a1470"
        }
      ]
    }
  ]
}
