{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/2977192/test-util-2977192.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "2977192",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "l2dfpflk7bgankgfihmc46sw24"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-2977192.jar",
          "url": "test-util-jvm-2977192.jar",
          "size": 6557,
          "sha512": "7058ff16f67e1701924a305dacb29dccc835af8382f3a684c8613472e259d4a21dfe394575ff5eee049bc2667f2a9bac5f426410c054229d82567d1f95506b1c",
          "sha256": "e187b45325bf16dc7d6572ac003b9d595252da3aa6b4af65a4c11f5a40ce30d6",
          "sha1": "48a15e23f270a99ccd834e1b66a8d6d9d62b1c04",
          "md5": "f515bf98b72d7785a5001a371408a497"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-2977192.jar",
          "url": "test-util-jvm-2977192.jar",
          "size": 6557,
          "sha512": "7058ff16f67e1701924a305dacb29dccc835af8382f3a684c8613472e259d4a21dfe394575ff5eee049bc2667f2a9bac5f426410c054229d82567d1f95506b1c",
          "sha256": "e187b45325bf16dc7d6572ac003b9d595252da3aa6b4af65a4c11f5a40ce30d6",
          "sha1": "48a15e23f270a99ccd834e1b66a8d6d9d62b1c04",
          "md5": "f515bf98b72d7785a5001a371408a497"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/2977192/test-util-metadata-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "2977192"
      }
    }
  ]
}
