{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosx64-0.1.0-SNAPSHOT.klib",
          "size": 8953,
          "sha512": "f848b3754903bc95b7de5e068a51e11753563d4872c2f7acacdd883d2d11ffebaadd8a7d2fd68519ba39922080265b214ba51870858ee6b29f3632d61a210b20",
          "sha256": "b33886b5284efd6d3a4cfc5f022440d406c8eac630c8d4b1165f7ab5f5ac0212",
          "sha1": "f9a0f26dfc9a618c971865d98d7ef2706e385c80",
          "md5": "fdd8963863e88989a3a800d03826eed0"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5803,
          "sha512": "79dae8dcfe984bd685d24f266bab116a1b27fa4ee03d3a866b697bc53d784a6593bd3ca3f478ec27844a8da50ab778e9c789dda1ae6f1110bc884ea8be641bc0",
          "sha256": "9dd95b4920827de7504d037d1b589181af296aeffe9618dbf57de38e34a89088",
          "sha1": "94e69e7180430edf7c3d2e83c4e78dbb1efa1a88",
          "md5": "d4225231113d06e85b2d41c9caf42d9c"
        }
      ]
    }
  ]
}
