{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "securestore-metadata-1.13.2-SNAPSHOT.jar",
          "url": "securestore-1.13.2-SNAPSHOT.jar",
          "size": 7274,
          "sha512": "d28d20f100c68e9f87d0156bbe8e601222d34f8f220f5cd33e8db75580feb5ff9edcac471a950b5a1d57d2ce6cfb3c97bf5abf6702b56fbb4813798ff652eeb1",
          "sha256": "b47920e7982f9931c4c15963094d954f4df564da8a6facd2ffc3cbd9d5f4819e",
          "sha1": "5008277006a72782466a97be4efa080e495529f5",
          "md5": "c9ce309830617461bf4ecaca381659cf"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.13.2-SNAPSHOT/securestore-android-debug-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.13.2-SNAPSHOT/securestore-android-debug-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.13.2-SNAPSHOT/securestore-android-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.13.2-SNAPSHOT/securestore-android-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.13.2-SNAPSHOT/securestore-jvm-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.13.2-SNAPSHOT/securestore-jvm-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.13.2-SNAPSHOT"
      }
    }
  ]
}
