{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ki5rrqvevg35gxnl4d7fcljl4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a37737c1a3ca719b2a20bae30fec27891c1c503c6343b255702b50283491aec8a440ee20915f696a0383b6afd2232a429771ec16cad1f46c1360b6c04fcc9121",
          "sha256": "6945505ce16042cca971306a109b9fae37fbb605482a4f0c8068b5255942dcfb",
          "sha1": "d6a396084ad5778079f3ba8e6d00323208f0bfec",
          "md5": "a5e84c778da8c05ef232989a4f305996"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a37737c1a3ca719b2a20bae30fec27891c1c503c6343b255702b50283491aec8a440ee20915f696a0383b6afd2232a429771ec16cad1f46c1360b6c04fcc9121",
          "sha256": "6945505ce16042cca971306a109b9fae37fbb605482a4f0c8068b5255942dcfb",
          "sha1": "d6a396084ad5778079f3ba8e6d00323208f0bfec",
          "md5": "a5e84c778da8c05ef232989a4f305996"
        }
      ]
    }
  ]
}
