{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lenvfmshubfgpfcwxttldlaas4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "c1d0634d4afb5d6da77ae9b9fd111cab4ecf696e79ae485c78021eb0db7602f9eeb0aa577032e2e27087dc874504231f70818fc6b032df736265beb9455d81bd",
          "sha256": "caf8fbd3080962ad338e15896cfc3f36ad4758c6fd716e8e82396a852dc0c9e7",
          "sha1": "a8907cc827e44d7b8276f1551c02f0a00a389d04",
          "md5": "1662d567709becb598474670fd831e68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "c1d0634d4afb5d6da77ae9b9fd111cab4ecf696e79ae485c78021eb0db7602f9eeb0aa577032e2e27087dc874504231f70818fc6b032df736265beb9455d81bd",
          "sha256": "caf8fbd3080962ad338e15896cfc3f36ad4758c6fd716e8e82396a852dc0c9e7",
          "sha1": "a8907cc827e44d7b8276f1551c02f0a00a389d04",
          "md5": "1662d567709becb598474670fd831e68"
        }
      ]
    }
  ]
}
