{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2fykjxuc6vf33k272qokyyctfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "0d3394d29437a15c6e63749c480649d2a526c21f7ab23f20a5e57e3b56f0f9cd680d456c98c73feba6b77f143c545e7cebc5971bc64abc73d182796a912c2372",
          "sha256": "90961b36a40339a65ed7468246cadb118b8b9f4e71ce2e3c43f85f789b3136c5",
          "sha1": "f8ad38f187a67f1278fe21be403e25949c92d0f1",
          "md5": "1d2005e8b31d1f91859608a067baf043"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "0d3394d29437a15c6e63749c480649d2a526c21f7ab23f20a5e57e3b56f0f9cd680d456c98c73feba6b77f143c545e7cebc5971bc64abc73d182796a912c2372",
          "sha256": "90961b36a40339a65ed7468246cadb118b8b9f4e71ce2e3c43f85f789b3136c5",
          "sha1": "f8ad38f187a67f1278fe21be403e25949c92d0f1",
          "md5": "1d2005e8b31d1f91859608a067baf043"
        }
      ]
    }
  ]
}
