{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hi6ofeo65fdubak2f6hbnlywha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "f2a01fd4c759928f25febb353e84c6c645e099030a79891c929261b83f811fa2bb04a843ad9abfe5e9cc35487a46021f8d2496d746138050d4f4628d3baa79eb",
          "sha256": "f9114cf6566e648cecd771ef9d7b0cf9828ed2d092f014ff77c707a502f0a49f",
          "sha1": "d9c66c45e24cdedf5c1aa177fd86897774c51dc7",
          "md5": "e7accfbe590ea1d939470a36ba0499b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "f2a01fd4c759928f25febb353e84c6c645e099030a79891c929261b83f811fa2bb04a843ad9abfe5e9cc35487a46021f8d2496d746138050d4f4628d3baa79eb",
          "sha256": "f9114cf6566e648cecd771ef9d7b0cf9828ed2d092f014ff77c707a502f0a49f",
          "sha1": "d9c66c45e24cdedf5c1aa177fd86897774c51dc7",
          "md5": "e7accfbe590ea1d939470a36ba0499b1"
        }
      ]
    }
  ]
}
