{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "73txki5cyfed7nskjjw3qrjhca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b8ad65f02dd34bc36988d59c63debba733bd449d2fafb32c864222dd362970f79a50452473eeb86f38207a7e346526e9c3247038d51412254592fd494809159a",
          "sha256": "e92effc203b8426061760fd5533aced6c6cebd8a6e4e27458849e9dd9694b1aa",
          "sha1": "fd4e46cab6e9d396736552fc0fce56e50b90c41f",
          "md5": "9f06ef432b770f843f1fd24c30e27cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b8ad65f02dd34bc36988d59c63debba733bd449d2fafb32c864222dd362970f79a50452473eeb86f38207a7e346526e9c3247038d51412254592fd494809159a",
          "sha256": "e92effc203b8426061760fd5533aced6c6cebd8a6e4e27458849e9dd9694b1aa",
          "sha1": "fd4e46cab6e9d396736552fc0fce56e50b90c41f",
          "md5": "9f06ef432b770f843f1fd24c30e27cda"
        }
      ]
    }
  ]
}
