{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ztmzf4nvkbaw7cjeluvubv6w6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "292e47a752fcecfc8dfe6526bb6302cfe193aae6c39c53f75ff9fba8f9f8a9315f1301766d65721e1443dc7aa196295258b036de38d986693a61beb4be3f86c9",
          "sha256": "f12d51c25ae743d527eab1d728e77d2843fc320d593abc7e3d5b64dbe393271d",
          "sha1": "fb5d738ec8c7d5263628ee2742137824f8f18f04",
          "md5": "5abeeefeb326d9d22a093101f23211a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "292e47a752fcecfc8dfe6526bb6302cfe193aae6c39c53f75ff9fba8f9f8a9315f1301766d65721e1443dc7aa196295258b036de38d986693a61beb4be3f86c9",
          "sha256": "f12d51c25ae743d527eab1d728e77d2843fc320d593abc7e3d5b64dbe393271d",
          "sha1": "fb5d738ec8c7d5263628ee2742137824f8f18f04",
          "md5": "5abeeefeb326d9d22a093101f23211a1"
        }
      ]
    }
  ]
}
