{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-SNAPSHOT/securestore-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "63bbd2582064e92c2a2288c5cce683c5f6ce4a425e2ed22115e42c3fd4b2528acb68123005015ef16ed7194c6fa3be274bc54fa4aecbf79b43e7eb309ed3e46d",
          "sha256": "334e4fffd8216ac2374845cfd80e5608f18711d8228ebb1377a9853984bef5c9",
          "sha1": "187a9546cc67f472341777043c347fe5bae1060d",
          "md5": "7aeb78b74c19ae9160d357e644cb9316"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "63bbd2582064e92c2a2288c5cce683c5f6ce4a425e2ed22115e42c3fd4b2528acb68123005015ef16ed7194c6fa3be274bc54fa4aecbf79b43e7eb309ed3e46d",
          "sha256": "334e4fffd8216ac2374845cfd80e5608f18711d8228ebb1377a9853984bef5c9",
          "sha1": "187a9546cc67f472341777043c347fe5bae1060d",
          "md5": "7aeb78b74c19ae9160d357e644cb9316"
        }
      ]
    }
  ]
}
