{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2-SNAPSHOT/crypto-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "4ysua4hckfhn7e5iclmyuxibxa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-debug.aar",
          "url": "crypto-android-debug-1.13.2-SNAPSHOT.aar",
          "size": 63394,
          "sha512": "90b450334d2604773512e7eca46ed2ace3c275aaab8ef45c25849a3d2470a6301fdb6c9de3e0e1ba9a6652673b57714273b00770a5e7eed8abd6bc1deebe83cc",
          "sha256": "5da55263b435cf069c5072b5937933b34a576bc8a2f174aedae60082b62fcda7",
          "sha1": "8f0fb893c2900b18683cde390769ede2240f7916",
          "md5": "3ce8f5a41f544382049b6e7bb28d9d3a"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-debug.aar",
          "url": "crypto-android-debug-1.13.2-SNAPSHOT.aar",
          "size": 63394,
          "sha512": "90b450334d2604773512e7eca46ed2ace3c275aaab8ef45c25849a3d2470a6301fdb6c9de3e0e1ba9a6652673b57714273b00770a5e7eed8abd6bc1deebe83cc",
          "sha256": "5da55263b435cf069c5072b5937933b34a576bc8a2f174aedae60082b62fcda7",
          "sha1": "8f0fb893c2900b18683cde390769ede2240f7916",
          "md5": "3ce8f5a41f544382049b6e7bb28d9d3a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2-SNAPSHOT/crypto-metadata-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2-SNAPSHOT"
      }
    }
  ]
}
