{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.4.1-SNAPSHOT/test-util-coroutine-0.4.1-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.4.1-SNAPSHOT.klib",
          "size": 8272,
          "sha512": "4c3c4a90602d30707b1eb3165a58fdf92a0ec63bbcdcbda20826d498049ad65d1696b02722ea05ca9b73ac70fbbc275042669ccdcb9b650cc395bc4cfb289fb3",
          "sha256": "a2b518d7a6d40a40e6f1e86c9f094ede222be6f1b9d7d640988e0f471f0b1029",
          "sha1": "361236d351c6a2be889f858eafc5c692bfe5821d",
          "md5": "16df4621e58ddbf50aa30316055997b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.4.1-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "c8e60681b4d41b837a80ce2e3353843039c4a3b64d89ab2c4082a46c39f0465f962c918ad3bb93486f2756f45c25d346eb49c7bba7f7ca4952f5a9937d1e54ec",
          "sha256": "433478c1a38416cf6ff7277df3bd900920ea893f16f103b2b630971a4e62de66",
          "sha1": "881ee65df63afb7aeeb9244388ddddee0c25befe",
          "md5": "22823d9d84c2e3d5fe4e79793546c841"
        }
      ]
    }
  ]
}
