{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-SNAPSHOT/test-util-ktor-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.2.0-SNAPSHOT.klib",
          "size": 15022,
          "sha512": "3d291c11e9b3f75aff17236fbc9623bcbd9894939c2c5c58271ea9ed864d3af7574bd604659172cdcd68edbff2799eecc27690cc720f694a93830d4bc7a32c5a",
          "sha256": "5af24856c803b8c3f286f499368335735a5e25dfd5d16b1f24efaaedc4578a73",
          "sha1": "3db797b886e28be5f28285ea0778f3e4075736b3",
          "md5": "18d3d1b0ae22b016473070a1ba810050"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.2.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5284818901465afe7dd80d8d92dd45cc61667400ad19fb0cccf75beb98a10a1b8bbf4c21e1e812e9df5d2f256bbc20a0fa14091cf90a5f5bcf434f63a05c0a9d",
          "sha256": "cc95c6b4bbf0cda86cbbf7138546fcb5cdc6a093f39573e8359f7d484c7e769c",
          "sha1": "f26b35377f58a911db98cc32c677537ac5a443c9",
          "md5": "f03f33961b5a6bd784ddb3c2db11e130"
        }
      ]
    }
  ]
}
