{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.1.0-SNAPSHOT/test-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "wvmegi33jnghnejebyykh7a7si"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.1.0-SNAPSHOT.jar",
          "size": 11761,
          "sha512": "d3820998b7421e0c0ca1739af8582972371bd1854e39d51adfa91ee3c9af83c2de292bd8e9d8293b8d990ee3e2260682841b6ee0e3ed145c7d6ab04f6cf9b689",
          "sha256": "eb9d20a78baf6426ce76a3742e89107f81deb483c20dc5b202f5174668cfacde",
          "sha1": "f434e41ba3eba6c126539dd0fcf996c82897ed51",
          "md5": "7f8bbb88993c9c8bc56daeb79abed72e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.1.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.1.0-SNAPSHOT.jar",
          "size": 11761,
          "sha512": "d3820998b7421e0c0ca1739af8582972371bd1854e39d51adfa91ee3c9af83c2de292bd8e9d8293b8d990ee3e2260682841b6ee0e3ed145c7d6ab04f6cf9b689",
          "sha256": "eb9d20a78baf6426ce76a3742e89107f81deb483c20dc5b202f5174668cfacde",
          "sha1": "f434e41ba3eba6c126539dd0fcf996c82897ed51",
          "md5": "7f8bbb88993c9c8bc56daeb79abed72e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/0.1.0-SNAPSHOT/test-util-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
