{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.1.0-SNAPSHOT/objc-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosx64-0.1.0-SNAPSHOT.klib",
          "size": 8882,
          "sha512": "ba9439706673c7bce71692adf48cb14c1056a107c7dacdf696d227e7f40d7b0bd875d6b5d13e711b81f0f836760266c51296208a666c69a2f691dd8a7710f7a0",
          "sha256": "1be2bdcfb0c3bdf00528903465345ccf5e0f9b5cffcbe284688ad14080fff55a",
          "sha1": "3927b4af7a5de28dee43fbdde2074d611f9ce2fe",
          "md5": "6680587c64d67f1afb31799b872d2972"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "objc-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5763,
          "sha512": "029f80329f4af71772d4add143a1617c1841ad4bdccf1316123f2207212214d76a6fd6014422cfc4556f530437f8a0562e8eec32095bdc9bc24d59b249f937c4",
          "sha256": "c13fcbd9bda3cffa965206d3e0316767b7a579654b108ef92a1cc237a80a0936",
          "sha1": "ccb180ec93103f2d29b3c68c7801031c7e10bf77",
          "md5": "8c5c463e449951e961ce89bc549e205d"
        }
      ]
    }
  ]
}
