{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.2-SNAPSHOT/data-donation-sdk-iosx64-0.0.2-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hpw5dezffnbzhdxkkbnayjkq6u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.2-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.2-SNAPSHOT.jar",
          "size": 63040,
          "sha512": "34995761f372193558cec934f6f92f9430bbb1dc995220a2b124c2aac40cd03a60c42338a5cf660e594ef6453d39ccb4cfa5893e267a14a8bf3540125ba27446",
          "sha256": "260add1520cdca0dba4ebf7b8dbaa63a9242759f444738527d356afc92b1e7fd",
          "sha1": "f8733fd62daea9e8797d9697b2daf51d1114600e",
          "md5": "799a3c16558a217228fe45b6bdbd79d1"
        }
      ]
    }
  ]
}
