{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test-jvm/1.9.0-SNAPSHOT/util-test-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "esrb7lawqzfnpgnbkhf22vkz64"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-test-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-test-metadata-1.9.0-SNAPSHOT.jar",
          "size": 3389,
          "sha512": "13df2435d569453850fddb0e33365871fb95261714e4b78ec4f608a8204294fa6e4c3ef4cbdaae445fea4f8a7cbb8e16a41baf9963105bb3d5748b0ac83714f5",
          "sha256": "4b6c16781fb7bd555e95ac3ac8b88179e9092a16236bec7ef2eed9b57ab9b893",
          "sha1": "104589fb3f642b2dcffa533f1fd88d15502666b9",
          "md5": "720ff7fc866ed99193d3260e5ad4b86f"
        }
      ]
    }
  ]
}
