{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.8.1-SNAPSHOT/util-coroutine-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "o7x552nqarhb5g27r4i3vzsh4i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.8.1-SNAPSHOT.jar",
          "size": 9394,
          "sha512": "465d0aab38996ea6db1723c9a1bb875a1aafbb62afa25f6b373a29ab36e8a9ffef6a579a8421645440c44a03fef7559903c7a7508b441b6ff7a51c4343af07f6",
          "sha256": "6ea9dc28d479c72a91287a7d68990f4d471941c3976ed555441a21dc866fea7f",
          "sha1": "3b6f0743ba9617dd17c25fdebae6ece5256640fc",
          "md5": "5de5ca019c550ce5446d821971dd9c02"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.8.1-SNAPSHOT.jar",
          "size": 9394,
          "sha512": "465d0aab38996ea6db1723c9a1bb875a1aafbb62afa25f6b373a29ab36e8a9ffef6a579a8421645440c44a03fef7559903c7a7508b441b6ff7a51c4343af07f6",
          "sha256": "6ea9dc28d479c72a91287a7d68990f4d471941c3976ed555441a21dc866fea7f",
          "sha1": "3b6f0743ba9617dd17c25fdebae6ece5256640fc",
          "md5": "5de5ca019c550ce5446d821971dd9c02"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.8.1-SNAPSHOT/util-coroutine-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
