{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto-jvm/1.13.2-SNAPSHOT/crypto-jvm-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.sdk.hc-crypto-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "gwv5m73w25bazd5u3bunutjzuu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.13.2-SNAPSHOT.jar",
          "url": "crypto-metadata-1.13.2-SNAPSHOT.jar",
          "size": 11505,
          "sha512": "98bcf85b89e14492bc35f2c494e62d01e9323048224c200a90c4a3d24c99a4701b61a89c9353bf906e5e9fae76629f92d112723e115cf2b048df201651bf2c7b",
          "sha256": "1c7598b1312f24262db5c01be9eb50e1344ef0608d818eb52ed8a603b1058c4f",
          "sha1": "9f4e065162ca909c0a504216eebaa1126fa6ee31",
          "md5": "53817d580e77fc44251be22ae86ac5c5"
        }
      ]
    }
  ]
}
