{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.12.0-SNAPSHOT/error-1.12.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.12.0-SNAPSHOT.klib",
          "size": 7100,
          "sha512": "6a4f00dfb2e9216859511612f28936ad8d04a46f89f7a35e065c792f2aebbbed129bc6e9fa6fd75be69976280c1af7bd9f7fa7b9da6b0b7a07a1d9e5bcb18f2a",
          "sha256": "0b55087a1d26b454ca975f26d916e1a2c1683541cac36e4bb3c83814aea82ef9",
          "sha1": "ae441be4e76b509af8a51da13be61d0a4466d154",
          "md5": "b4f80a90b3d3852b8bb6054d132887c1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.12.0-SNAPSHOT-metadata.jar",
          "url": "error-iosarm64-1.12.0-SNAPSHOT-metadata.jar",
          "size": 5010,
          "sha512": "cdb3df518f5d481ad7fcb25ec070376c70e936e9e58e7305a9541c51e3b4aa6724b59b87ddf6b5fd097161918aa42e2a9a424032694535c7a0731774fcbc56ef",
          "sha256": "5fa611ece5b4645bac68c3969ff42df93fb9c3403091f674892ae65210eccc09",
          "sha1": "c31f37e460f5d7799b9292e8eebceacb287be968",
          "md5": "6914a20a6a2a2507fa1fd018b8a17bec"
        }
      ]
    }
  ]
}
