{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.6.0-SNAPSHOT/fhir-helper-1.6.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "x3qntpbatbejzhgfqoucstgame"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "size": 113539,
          "sha512": "8788c06d8dcbf6122f217e32a47e432480a5c0fc1bce3772e16e4b0ab23d72455745e866e5d6e5440f3b0ce7e11b304d6e1f62c16f6a4f253c2a4a991d134468",
          "sha256": "dcbbd0bec2c09d88dc62db211002590f6d1392cf97ff8a8a2eb9fb37edf4cd7a",
          "sha1": "9c8b1b01b9bebaf96e66dc15cfc69879e5b447d3",
          "md5": "035891967c778f6b631aacdd19f80b6d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "size": 113539,
          "sha512": "8788c06d8dcbf6122f217e32a47e432480a5c0fc1bce3772e16e4b0ab23d72455745e866e5d6e5440f3b0ce7e11b304d6e1f62c16f6a4f253c2a4a991d134468",
          "sha256": "dcbbd0bec2c09d88dc62db211002590f6d1392cf97ff8a8a2eb9fb37edf4cd7a",
          "sha1": "9c8b1b01b9bebaf96e66dc15cfc69879e5b447d3",
          "md5": "035891967c778f6b631aacdd19f80b6d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.6.0-SNAPSHOT/fhir-helper-metadata-1.6.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
