{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.6.0-SNAPSHOT/fhir-helper-1.6.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gevivieqfzdx7ialpojdgwtkqq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "size": 116366,
          "sha512": "17af1b815e1fc79a95b71231951fefaca1a65565851448b0c9a844733f3acd157ef25e309be8fd26c501bf12247aa8f6770376d748939fb935fdcb9d35ddf476",
          "sha256": "a23da06a173e4ca5fb7d6c8814e1f1dcfd1cd65e1f0f11f163198b244b5d8ba5",
          "sha1": "5d4d0e19d4a92ee4a5f40624cf504a72efa96d14",
          "md5": "79a412873b6ccb58ddef67ff8c8515fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.6.0-SNAPSHOT.jar",
          "size": 116366,
          "sha512": "17af1b815e1fc79a95b71231951fefaca1a65565851448b0c9a844733f3acd157ef25e309be8fd26c501bf12247aa8f6770376d748939fb935fdcb9d35ddf476",
          "sha256": "a23da06a173e4ca5fb7d6c8814e1f1dcfd1cd65e1f0f11f163198b244b5d8ba5",
          "sha1": "5d4d0e19d4a92ee4a5f40624cf504a72efa96d14",
          "md5": "79a412873b6ccb58ddef67ff8c8515fb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.6.0-SNAPSHOT/fhir-helper-metadata-1.6.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
