{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.1.0-SNAPSHOT/fhir-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "s2ui67sngbe6faa7l4ww6y5mlm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-SNAPSHOT.jar",
          "url": "fhir-metadata-0.1.0-SNAPSHOT.jar",
          "size": 522472,
          "sha512": "3b7077d2807784e185d93d315ad62f510c42ec6b3402ab8e5da7404a66fe988af6adc0a4627b5558ea38797dc069ee7420a5b804dad9875721eaf519bc887e3f",
          "sha256": "874ee761a8d54e97893d85b13c703605140ed7884228bdf3d2a44a0ed1cac583",
          "sha1": "48fe96a3a6393c21c11dbc8bb444289fceccd812",
          "md5": "7e7ac1d0242460365a10ed38466e302e"
        }
      ]
    }
  ]
}
