{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.1.0-SNAPSHOT/fhir-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3o2qocmnbrgwlawdfkipx3mkxe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-SNAPSHOT.jar",
          "url": "fhir-metadata-0.1.0-SNAPSHOT.jar",
          "size": 998099,
          "sha512": "eed0ca03e42aa5505e78a6f9cd22751232a8c1f666b93c40d03e48f6d28002d5bce5ccfc530ab65f2cac4a0afc8a03ebd7b60b6d39176c5d9d402bc5bdd9a19f",
          "sha256": "bb9b30d2ac489dc49f8291755174984eac23d126738c8527a86c59800bdf9767",
          "sha1": "7288a5da456f0fea6ae269e76052be180702a873",
          "md5": "1426b0cb4e98f64e6f6ecccfc53a1ebf"
        }
      ]
    }
  ]
}
