{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "frww6tbtmngozdpq62odvmnrma"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "d7fbfbe1b5b12787cd3a2334b4b84531a673e32ba0ba6ab6a9ede6b9a47581cd8c9e3fa699738fc7879ee2782cd269dc902fa7a4cddada20737c389adc5cf4ce",
          "sha256": "c96a586112ebfcdc07f16e9acee507f93185b3c46700aff7c546cf1e58031108",
          "sha1": "5e5582aa394958827a42420c6762a1a3036d57d6",
          "md5": "df184511fff14685d7abb58cff765bde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "d7fbfbe1b5b12787cd3a2334b4b84531a673e32ba0ba6ab6a9ede6b9a47581cd8c9e3fa699738fc7879ee2782cd269dc902fa7a4cddada20737c389adc5cf4ce",
          "sha256": "c96a586112ebfcdc07f16e9acee507f93185b3c46700aff7c546cf1e58031108",
          "sha1": "5e5582aa394958827a42420c6762a1a3036d57d6",
          "md5": "df184511fff14685d7abb58cff765bde"
        }
      ]
    }
  ]
}
