{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gmosjtalmzhnxbkkehus55gdcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "646ff642c93ccc9ac31354ab0c9e5cc4a07bea1bdb9fc2c4bc6af157f78767f95cbd379c3bd37987bc55bf824a9136f52891a821c9c396befe614e97b18da0a3",
          "sha256": "5fc51383507a2898a90d593ab6c9cef606d7d70967d57908324b78896aa7dcfc",
          "sha1": "f84382a6c0578a43e05fe668bd881bf326ab00fa",
          "md5": "4855634cf6f149632d59013542e42245"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "646ff642c93ccc9ac31354ab0c9e5cc4a07bea1bdb9fc2c4bc6af157f78767f95cbd379c3bd37987bc55bf824a9136f52891a821c9c396befe614e97b18da0a3",
          "sha256": "5fc51383507a2898a90d593ab6c9cef606d7d70967d57908324b78896aa7dcfc",
          "sha1": "f84382a6c0578a43e05fe668bd881bf326ab00fa",
          "md5": "4855634cf6f149632d59013542e42245"
        }
      ]
    }
  ]
}
