{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hqserunt6beknasoh3kvcuiywa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "9117faf7e52dc9cf7fe567f04cea097823625ec64185a952c4d02c214be043321ccff2d51be98ce38b344c285406107d054febaff8e9169cd6fa867bb2d01671",
          "sha256": "2cfaf26da3eebc0fe74f4559695d45662e3cbb22ac444565f94491ec5fc300e2",
          "sha1": "b6c2453c91b746c51386c7ab3bda48c1ded14bf8",
          "md5": "e8ef194d7dd05d65a5866c17157a5cfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "9117faf7e52dc9cf7fe567f04cea097823625ec64185a952c4d02c214be043321ccff2d51be98ce38b344c285406107d054febaff8e9169cd6fa867bb2d01671",
          "sha256": "2cfaf26da3eebc0fe74f4559695d45662e3cbb22ac444565f94491ec5fc300e2",
          "sha1": "b6c2453c91b746c51386c7ab3bda48c1ded14bf8",
          "md5": "e8ef194d7dd05d65a5866c17157a5cfe"
        }
      ]
    }
  ]
}
