{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test-jvm/1.9.0-SNAPSHOT/util-coroutine-test-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2vy4lgcowjffdf4rz5cbiomaxy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-test-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-coroutine-test-metadata-1.9.0-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "175c33b13cd401c262101e3d0f1ea56a9ab5a49c45f2c399e1d2c37cc870c0d8ccfed0ed16e2da0eb001f8787360f39625dc693a95934b2e73bc9974bc91c57b",
          "sha256": "661724ae446ddd66532772320f5f59c5e6df74d5d29436be2738f445822fd357",
          "sha1": "6de8897c329219f9c7eb73d2d2d4b04ae4668e9b",
          "md5": "997d84aa07ad70d42f982704b75af218"
        }
      ]
    }
  ]
}
