{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ysbvs23a75eivlj2eoopdfv6na"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "size": 74879,
          "sha512": "21447c19190efdac48c9e2bc98f90d442715fa0b3ffcfb701df7055c3f4b7aae78f18ea1ab6bed3e8b837d57b3ca5473bc4119492d3432f03b28fcfa83950fdb",
          "sha256": "20e7e402bd17e146a9db765a7fef12d62e947002c341440d217122053fbdda05",
          "sha1": "756e42891f8a0a01920beff12e31e85ae5e26987",
          "md5": "adb7447ced7def9cce72a3fc4448d7b1"
        }
      ]
    }
  ]
}
