{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vdoyyuwyafeitmuixthadtcxma"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "size": 73678,
          "sha512": "b1a9054501a958b7b9d5a88d7924158758fc7bd1448136289bc411abf8b05bf13046fc6e4a89796645625bc22438251beaf32cbfe7230b2d8038262356a96dd5",
          "sha256": "f00dcb3a703101200b3986bcbd2c174ee7b6eba4dac1fb5a36c7fabd83c7581a",
          "sha1": "deabef5b530fc3b26c117955c980a505e34df722",
          "md5": "0884b11e62ffd35c1445705ec1efc918"
        }
      ]
    }
  ]
}
