{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bazwl6kfofcmviuhbu4sh4zrzm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "size": 79873,
          "sha512": "ddd00f7ed6e7b9daf6a83893e380a64aba13a0c9e004e8e221b7b7500675f0c3953c72a3e9229883f389d6c19079a92e7bc3d706c5d4d53e83d35c9e1084c33e",
          "sha256": "07c5dbe73a3be0471c6eb496a1eaad15473cdf11f23511de36f5ae1635e82399",
          "sha1": "e6b3c5c383b13667269e4806ca8c4e038bd425c9",
          "md5": "9cbb6c37ab1e831c29f598c4ab96541b"
        }
      ]
    }
  ]
}
