{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m3hqi3sqqzd77js37mtikidr5u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "size": 44856,
          "sha512": "a1763663cdaf4bbca8b6689df853575b4a6e740d7e0df4ddbf373d7c0ac96b488627f288477900d477df5dac1b9aa9a8f1b0f46bbe7e61b0f7cc1fa45b419043",
          "sha256": "cc2d66fd8e6d093c049eb4486c02c8ed58d64d042b8ac38b734f33cf5f67485b",
          "sha1": "ac69fcaa0a9bdb1b74d70049feeacc0be9d8ea3e",
          "md5": "ddf76fdf9ab46370f7737509b0fd3d79"
        }
      ]
    }
  ]
}
