{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v6gpl6thmvb5lo6uhontguh5ea"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-SNAPSHOT.jar",
          "size": 50020,
          "sha512": "c75e4443b529e161fced93b043dbc37b99e4cd007cb514fafac01c934a3a9970b4d43fa3967ad8c29f2ce02c6732e711bd7ec5a20a8fb31c86daaaaea1a12f2d",
          "sha256": "2b55b5d5895a59ba10b3aa0921c1d84a2f4f2c794db311deb923bc7afe326972",
          "sha1": "63c847e1e2da2b45f94ba948e88b91345e4948de",
          "md5": "d631e7386aa914413a3165891d9b84b9"
        }
      ]
    }
  ]
}
