{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-SNAPSHOT/test-util-coroutine-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "32f56f14d3aa497ca2249c24a1ed7c84837bec22514e0d7839619e457d6d3924d7686f582a909ad42fb0d7c40b8f954614ff493d4e7d6b57f646b1844df3e949",
          "sha256": "c1a955c1de793f68a13adef1c00a5bcba77a170725e78b83c7ff64d8b8987949",
          "sha1": "4903c8bf0d71a4d9875b4fab06ea3df8d8c2ed50",
          "md5": "70a61e49c2f10cadde3758fa48212b34"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "32f56f14d3aa497ca2249c24a1ed7c84837bec22514e0d7839619e457d6d3924d7686f582a909ad42fb0d7c40b8f954614ff493d4e7d6b57f646b1844df3e949",
          "sha256": "c1a955c1de793f68a13adef1c00a5bcba77a170725e78b83c7ff64d8b8987949",
          "sha1": "4903c8bf0d71a4d9875b4fab06ea3df8d8c2ed50",
          "md5": "70a61e49c2f10cadde3758fa48212b34"
        }
      ]
    }
  ]
}
