{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-SNAPSHOT/test-util-coroutine-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "027172445333b51248f769e9b4df47bc40904f2c062878db763ada41f50b3f5abe7442858eb1d48eed39bcac2ee7450b5b92021d1171f73e066ce659f68ea8a1",
          "sha256": "4c9ae6579a72c5f2888764879bd6df4c4c8b0b66eb2b45def6843fd155b2153b",
          "sha1": "96b434fe0af7377e66f974df5572596f522cd711",
          "md5": "9989b082156bd86d2841ded3183e645f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.3.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "027172445333b51248f769e9b4df47bc40904f2c062878db763ada41f50b3f5abe7442858eb1d48eed39bcac2ee7450b5b92021d1171f73e066ce659f68ea8a1",
          "sha256": "4c9ae6579a72c5f2888764879bd6df4c4c8b0b66eb2b45def6843fd155b2153b",
          "sha1": "96b434fe0af7377e66f974df5572596f522cd711",
          "md5": "9989b082156bd86d2841ded3183e645f"
        }
      ]
    }
  ]
}
