{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2/securestore-1.13.2.module",
    "group": "care.data4life.sdk.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "2tanu4f2jbe3jln3dgbnsr5jq4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-1.13.2.aar",
          "size": 31716,
          "sha512": "21352cffdef999a77c9aef28a37cbfd64a12511edf1a99d030c97a37cd02eec7e30d8096645576662915266172d80f0dbb91366eebccd15deecaa399ff641ceb",
          "sha256": "1ec2eca0f5837a2a9b502e0124647114c0569374de10736550fcb758c3482705",
          "sha1": "1c53e119e6bfe0360d760479004aa41a236f8526",
          "md5": "32db03944fd1bb2d9be1ef5107eb7e2c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-1.13.2.aar",
          "size": 31716,
          "sha512": "21352cffdef999a77c9aef28a37cbfd64a12511edf1a99d030c97a37cd02eec7e30d8096645576662915266172d80f0dbb91366eebccd15deecaa399ff641ceb",
          "sha256": "1ec2eca0f5837a2a9b502e0124647114c0569374de10736550fcb758c3482705",
          "sha1": "1c53e119e6bfe0360d760479004aa41a236f8526",
          "md5": "32db03944fd1bb2d9be1ef5107eb7e2c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../securestore-metadata/1.13.2/securestore-metadata-1.13.2.module",
        "group": "care.data4life.sdk.hc-securestore-sdk-kmp",
        "module": "securestore-metadata",
        "version": "1.13.2"
      }
    }
  ]
}
