{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bm5rghhf3jhsjoc52gph46k66a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "d8f63e27f7f90dce2fe0546df9fc3e46d8b438ff0ad114cbd6c2ecc24c30b35a3f00169c3f84fbbd4fa1b8d868ebb06d5370634aca4d9b242446143421446e66",
          "sha256": "3a8be81405fbec75a3dfc4bae5ee9ddef65ec3f967e62512a07a4dcff20f1a46",
          "sha1": "8413e965eb4d5e78efc57026c9d3b4103e0ddcde",
          "md5": "200d32ec0ea065a9cbf10b5947e6e303"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "d8f63e27f7f90dce2fe0546df9fc3e46d8b438ff0ad114cbd6c2ecc24c30b35a3f00169c3f84fbbd4fa1b8d868ebb06d5370634aca4d9b242446143421446e66",
          "sha256": "3a8be81405fbec75a3dfc4bae5ee9ddef65ec3f967e62512a07a4dcff20f1a46",
          "sha1": "8413e965eb4d5e78efc57026c9d3b4103e0ddcde",
          "md5": "200d32ec0ea065a9cbf10b5947e6e303"
        }
      ]
    }
  ]
}
