{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vhtne7ae6nez5mkqslirii3ifm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "711eb2a9458148e05dd158cb6853f5f63ec37b722b091cff1494781db48b6e792795a6eb08bbd51331e835bbcb381fb646be65712b1417be1c3ab15227ab9aac",
          "sha256": "29e8d2536f4e3a41250a9f64a95d7d41955ee5a42577af97581839ac201eb852",
          "sha1": "f8a178814c880fdbcaf39be0c2b3c33803cc5258",
          "md5": "75f1507e7018967e09576fc13471b40e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "711eb2a9458148e05dd158cb6853f5f63ec37b722b091cff1494781db48b6e792795a6eb08bbd51331e835bbcb381fb646be65712b1417be1c3ab15227ab9aac",
          "sha256": "29e8d2536f4e3a41250a9f64a95d7d41955ee5a42577af97581839ac201eb852",
          "sha1": "f8a178814c880fdbcaf39be0c2b3c33803cc5258",
          "md5": "75f1507e7018967e09576fc13471b40e"
        }
      ]
    }
  ]
}
