{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ex6wcqgazjfklhprdf67prhaoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "26edd9481baecdd053c597f269bbe35aa029d0753db797e60ede5b7cec51b21556acd515defe404a655c8cf0c53a9e00616e3ccc211e83faffd5df01644c7d70",
          "sha256": "6e30d59614bfdc2163041a2a9ae9c620982cfa5a913da882c246e5c6c71fde87",
          "sha1": "f8bc701acd51f1793bcc70ef3e3395368dcf8087",
          "md5": "1ba8c1875257a7de763ed968b75caa7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "26edd9481baecdd053c597f269bbe35aa029d0753db797e60ede5b7cec51b21556acd515defe404a655c8cf0c53a9e00616e3ccc211e83faffd5df01644c7d70",
          "sha256": "6e30d59614bfdc2163041a2a9ae9c620982cfa5a913da882c246e5c6c71fde87",
          "sha1": "f8bc701acd51f1793bcc70ef3e3395368dcf8087",
          "md5": "1ba8c1875257a7de763ed968b75caa7f"
        }
      ]
    }
  ]
}
