{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/6d5e126/test-util-6d5e126.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "6d5e126",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "r3yfwz52cjacvivcmhucyfzip4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-6d5e126.jar",
          "url": "test-util-jvm-6d5e126.jar",
          "size": 6557,
          "sha512": "0ed28b8dde4d8f0b2514fa053fbff8f57be89efb8cde31c085c9dda07ccbe9c7fbc0dd6180a8f82623adb7651f5a2791dccf53ca62bf3aa329ab4261f77ac132",
          "sha256": "1f40ee1a6c7550a577726e0897abe151cc2f14cac098b8fa86774ac532693771",
          "sha1": "7a841c410d21d7ed6c89a0e7394e83293bd9c2ca",
          "md5": "c62b11417c04332dc4649868e47eb117"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-6d5e126.jar",
          "url": "test-util-jvm-6d5e126.jar",
          "size": 6557,
          "sha512": "0ed28b8dde4d8f0b2514fa053fbff8f57be89efb8cde31c085c9dda07ccbe9c7fbc0dd6180a8f82623adb7651f5a2791dccf53ca62bf3aa329ab4261f77ac132",
          "sha256": "1f40ee1a6c7550a577726e0897abe151cc2f14cac098b8fa86774ac532693771",
          "sha1": "7a841c410d21d7ed6c89a0e7394e83293bd9c2ca",
          "md5": "c62b11417c04332dc4649868e47eb117"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/6d5e126/test-util-metadata-6d5e126.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "6d5e126"
      }
    }
  ]
}
