{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.8.0-SNAPSHOT/fhir-helper-1.8.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.8.0-SNAPSHOT.aar",
          "size": 112361,
          "sha512": "5f5ce2fa41035e51930d9b65fc368304c04146480d0a6fad768eea73b6a52af363d3e3f9e00fc1eb779c035fb3477954ede93fda9b98a61ef81f0dc11a9af795",
          "sha256": "6c1ebda451c767c6da2026163d1b756e8a05f6d32669ea2fcd098e8d457b5519",
          "sha1": "0cfb7bf9a2e871c3b5f4817d405350e9acae6963",
          "md5": "308140ae568cd60abc086dc62599ab9a"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fhir-helper-debug.aar",
          "url": "fhir-helper-android-debug-1.8.0-SNAPSHOT.aar",
          "size": 112361,
          "sha512": "5f5ce2fa41035e51930d9b65fc368304c04146480d0a6fad768eea73b6a52af363d3e3f9e00fc1eb779c035fb3477954ede93fda9b98a61ef81f0dc11a9af795",
          "sha256": "6c1ebda451c767c6da2026163d1b756e8a05f6d32669ea2fcd098e8d457b5519",
          "sha1": "0cfb7bf9a2e871c3b5f4817d405350e9acae6963",
          "md5": "308140ae568cd60abc086dc62599ab9a"
        }
      ]
    }
  ]
}
