{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-SNAPSHOT/test-util-ktor-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.3.0-SNAPSHOT.klib",
          "size": 15755,
          "sha512": "880d4cae6db0c73abca2ca2b38a7ba33a96d508adf205c8394e575fe0f7bd942cb4bdd4b573095778575f3c293b8a3d6f9facd4bf899e2f4fef48294ab20d31f",
          "sha256": "3b0f9dd9a65f38ed7f262eb03ec1a5af57d6abffdd5a9e871cbe4d3a284f07c0",
          "sha1": "00cd4a5ba77d94690846a40e9aa0deafb1fed1c5",
          "md5": "37037efa20d56d7bf04d7d5d2d16eebb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "804678bb2acb9cefdd563c059eac62b52e5063586538ae1f8c788a14a9c85a4af032b0f3f99fb0e5892c09c5cf95003f1c843ed3c36fdf4d64c71fba30278656",
          "sha256": "3284dd5f2017a076825f478f8296492779661044dc44ee4dbd5dea47b573353c",
          "sha1": "7ea5454a75fd1e5e6ea4cb77ff3ae1fb3e7c3d79",
          "md5": "2d71170033b2c98ea67094c502339645"
        }
      ]
    }
  ]
}
