{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "frww6tbtmngozdpq62odvmnrma"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.12.0-SNAPSHOT.aar",
          "url": "crypto-android-1.12.0-SNAPSHOT.aar",
          "size": 61890,
          "sha512": "481690bcda4f7b79daa89c197debdcbfe97f5c4841c697e7d15aaf43ee50cef1dc2051829161779290184df1bb78163b84d5b37f1c79ca361e918ddaccb9dc88",
          "sha256": "099d6e1f7fbc8496a44b6469a78f8c0096da21c4c9eac8e407831647dddc5bc1",
          "sha1": "56069ea1fa10f941e204e52aa091225310a48d12",
          "md5": "388232a68f64514b586ffaac670e205c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.12.0-SNAPSHOT.aar",
          "url": "crypto-android-1.12.0-SNAPSHOT.aar",
          "size": 61890,
          "sha512": "481690bcda4f7b79daa89c197debdcbfe97f5c4841c697e7d15aaf43ee50cef1dc2051829161779290184df1bb78163b84d5b37f1c79ca361e918ddaccb9dc88",
          "sha256": "099d6e1f7fbc8496a44b6469a78f8c0096da21c4c9eac8e407831647dddc5bc1",
          "sha1": "56069ea1fa10f941e204e52aa091225310a48d12",
          "md5": "388232a68f64514b586ffaac670e205c"
        }
      ]
    }
  ]
}
