{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2-SNAPSHOT/crypto-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gz4siyltafcldpkqgmdzp5c6cm"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-release.aar",
          "url": "crypto-android-1.13.2-SNAPSHOT.aar",
          "size": 61915,
          "sha512": "eccd32d6f2ac53cdd526e480e352785ececf0eae03c6df1d5c4d735fd2ffbdf36361264860bbbbcc00dae209b0ff537d75cd6627b7164c519ff0487b6444804e",
          "sha256": "878bc3ad8661d797ecc60345fd4c1f7c1c7299e26c3b8063e1f1213903944351",
          "sha1": "97e112685b860219f0a94240854b197fa5ed6273",
          "md5": "1e7c0300a0f37d3279224d683f2e5883"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-release.aar",
          "url": "crypto-android-1.13.2-SNAPSHOT.aar",
          "size": 61915,
          "sha512": "eccd32d6f2ac53cdd526e480e352785ececf0eae03c6df1d5c4d735fd2ffbdf36361264860bbbbcc00dae209b0ff537d75cd6627b7164c519ff0487b6444804e",
          "sha256": "878bc3ad8661d797ecc60345fd4c1f7c1c7299e26c3b8063e1f1213903944351",
          "sha1": "97e112685b860219f0a94240854b197fa5ed6273",
          "md5": "1e7c0300a0f37d3279224d683f2e5883"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2-SNAPSHOT/crypto-metadata-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2-SNAPSHOT"
      }
    }
  ]
}
