{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.15.0-SNAPSHOT/securestore-1.15.0-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.15.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.15.0-SNAPSHOT.jar",
          "size": 16628,
          "sha512": "df1485f7f81b758a1386f6edcfa777b9a4f322e9476b9f454e074227db35be6b7471f712fad1c73ba58d4de447d856897fb4491419d134e962394cfe93c93626",
          "sha256": "0e8d6b70c88365f5eca2eaa4769048b3704edb6c18d56f3a5820e9efa6a28f16",
          "sha1": "737297468660e64aa334869c8b77aad2c7b8a668",
          "md5": "d95189ab4a9d6660c606c40eaa078122"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.15.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.15.0-SNAPSHOT.jar",
          "size": 16628,
          "sha512": "df1485f7f81b758a1386f6edcfa777b9a4f322e9476b9f454e074227db35be6b7471f712fad1c73ba58d4de447d856897fb4491419d134e962394cfe93c93626",
          "sha256": "0e8d6b70c88365f5eca2eaa4769048b3704edb6c18d56f3a5820e9efa6a28f16",
          "sha1": "737297468660e64aa334869c8b77aad2c7b8a668",
          "md5": "d95189ab4a9d6660c606c40eaa078122"
        }
      ]
    }
  ]
}
