{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0-SNAPSHOT/test-util-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT.klib",
          "size": 17503,
          "sha512": "0ebbf039accc26124edbda27c1c0a81160f336de35371118be48dd916d30214b89a3c1cc56c95b255ce0cae6aafc41a34a3406505cd7951ff827203087a6cb56",
          "sha256": "9cf96d55785ecee6e6be3e72189d752084c03d43b276a96e012b6d7e76e85ef6",
          "sha1": "2ce1818a7f32894678b3d2b2310965c248c14c07",
          "md5": "a58c02e43e3c47743d97042664890cb7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 7055,
          "sha512": "161166834c02f30cda5466cdc9c49620fe3197273e522fe2f5ba7efe5b7ac5d1b6082a6381fa1e2c1ca2950450c2ffb8a6e6f7da88ee6519a0096f9a6d0a5863",
          "sha256": "f54ae68f7da68e9be523e3efb9607ae34f69c7ff40420999a45171f8df4cb51b",
          "sha1": "b24be56ecf7347b18d88dad3d5c3532eaae9bd24",
          "md5": "82d53effd1af78d7020855240e9ddbab"
        }
      ]
    }
  ]
}
