{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0-SNAPSHOT/test-util-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT.klib",
          "size": 17503,
          "sha512": "0ebbf039accc26124edbda27c1c0a81160f336de35371118be48dd916d30214b89a3c1cc56c95b255ce0cae6aafc41a34a3406505cd7951ff827203087a6cb56",
          "sha256": "9cf96d55785ecee6e6be3e72189d752084c03d43b276a96e012b6d7e76e85ef6",
          "sha1": "2ce1818a7f32894678b3d2b2310965c248c14c07",
          "md5": "a58c02e43e3c47743d97042664890cb7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 7055,
          "sha512": "7eccb4fd432be55b496b577aa485bdea0687f2fdbf3bc22d0f5ad93698c5ce5539b133606d4495e06e6f964f97f316ef1baf60a3307ee34226635c2cc031359b",
          "sha256": "226c628b91d3a5cb7af7f39713390bfedbc77456f8a696655b4fe3633817ba3f",
          "sha1": "adba5c9bcbc2371e7eb30d20e08808ce5da6fa2d",
          "md5": "bc82cc17f66af2df1837cb1af70c48da"
        }
      ]
    }
  ]
}
