{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0-SNAPSHOT/test-util-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT.klib",
          "size": 17503,
          "sha512": "0ebbf039accc26124edbda27c1c0a81160f336de35371118be48dd916d30214b89a3c1cc56c95b255ce0cae6aafc41a34a3406505cd7951ff827203087a6cb56",
          "sha256": "9cf96d55785ecee6e6be3e72189d752084c03d43b276a96e012b6d7e76e85ef6",
          "sha1": "2ce1818a7f32894678b3d2b2310965c248c14c07",
          "md5": "a58c02e43e3c47743d97042664890cb7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-iosx64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 7055,
          "sha512": "ce5e8a6ef50642eaedf1fa6506f37d78ea1d92b9682306b9e7dda6e60c311e8e056660b5e514c706ae16f39174ed83c80fbd0b58dd1004d8e1fb79174aa68dbd",
          "sha256": "5f54b767aa3b3b59452378776423a91f2e167d32f3268105acc5ec7bd77a7e67",
          "sha1": "451bae586ccb35f492a0c2b56681e0541998bc3a",
          "md5": "b2763b2bec4d57a9824eee45331370f5"
        }
      ]
    }
  ]
}
