{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vhtne7ae6nez5mkqslirii3ifm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "29e68bb43bc33dc303e98bf879cebcab5533b40414298c3c7480b146ad6df4cd37a5747f416b86816998f0cd64c1e338fc39ab7b2ede3433eaf1d0c09ed301a4",
          "sha256": "5aa8aa656f161417d14f1923de490baacb83e2407c058401a1b6157f4cce1736",
          "sha1": "57dd65ec4316f8dc7d716065a6b26a8b263a00cb",
          "md5": "c3f1ba7d5d9d71780b4f8338d8d81ecd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "29e68bb43bc33dc303e98bf879cebcab5533b40414298c3c7480b146ad6df4cd37a5747f416b86816998f0cd64c1e338fc39ab7b2ede3433eaf1d0c09ed301a4",
          "sha256": "5aa8aa656f161417d14f1923de490baacb83e2407c058401a1b6157f4cce1736",
          "sha1": "57dd65ec4316f8dc7d716065a6b26a8b263a00cb",
          "md5": "c3f1ba7d5d9d71780b4f8338d8d81ecd"
        }
      ]
    }
  ]
}
