{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cpdcf7xp3jhn5edl25yzy765oe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0b7c6962c1ba0a1ac1ed53ddf652a73f9601b075260020c81aea4e884a9ecb485cd36e1c3af66e26158acc012b7390b7105a84734a806031f6339e3a36da58d7",
          "sha256": "8eb9b30f5f4c87e65d51d141c542c62571871a5ef6fe72ac755ecd791891706d",
          "sha1": "a26b40f6caf649179f1931186483f62366377662",
          "md5": "3fc45de711d3b5c29bfa13f795a0cdd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0b7c6962c1ba0a1ac1ed53ddf652a73f9601b075260020c81aea4e884a9ecb485cd36e1c3af66e26158acc012b7390b7105a84734a806031f6339e3a36da58d7",
          "sha256": "8eb9b30f5f4c87e65d51d141c542c62571871a5ef6fe72ac755ecd791891706d",
          "sha1": "a26b40f6caf649179f1931186483f62366377662",
          "md5": "3fc45de711d3b5c29bfa13f795a0cdd5"
        }
      ]
    }
  ]
}
