{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hrphzlccjref7k3o6a7cm7lnry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1589733a2d5a0cacdae8aad4528d0302cd0fa89508195d993b272e557ccceca678825582f4959f5e55be8c30d5dbf02566f49c5ae4ec146c26dc2288ea5235a9",
          "sha256": "4175167369f533e7fad067f0f2e369e81e264b93bb7a9b9443b94b0c520dbefd",
          "sha1": "19a5c31396764099476c56564ec8253aa89cb696",
          "md5": "77beb4c3c9efd9b10ed9b2b4447ec5a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1589733a2d5a0cacdae8aad4528d0302cd0fa89508195d993b272e557ccceca678825582f4959f5e55be8c30d5dbf02566f49c5ae4ec146c26dc2288ea5235a9",
          "sha256": "4175167369f533e7fad067f0f2e369e81e264b93bb7a9b9443b94b0c520dbefd",
          "sha1": "19a5c31396764099476c56564ec8253aa89cb696",
          "md5": "77beb4c3c9efd9b10ed9b2b4447ec5a4"
        }
      ]
    }
  ]
}
