{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-SNAPSHOT/util-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kwd3npjy6nbmpkyxjt5wxiv2ae"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "1a46d017c9d55ebff277f6ac9fea3daeca4e3d6adfb4ba0d078edf42ccbf1e3c7c27190f828daeab0bc7738cad557716b0bfbdd72cd4a40d85adfdff6a4614dd",
          "sha256": "87b413e4ccfaf0042b44b61457c6cae2d0efcde90e463abeca6f38f181b33179",
          "sha1": "0c0415e93c0fb6895eb942e07a673b5f5ec85d7f",
          "md5": "95ea699d01df6d47b07ef5843e915a91"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "1a46d017c9d55ebff277f6ac9fea3daeca4e3d6adfb4ba0d078edf42ccbf1e3c7c27190f828daeab0bc7738cad557716b0bfbdd72cd4a40d85adfdff6a4614dd",
          "sha256": "87b413e4ccfaf0042b44b61457c6cae2d0efcde90e463abeca6f38f181b33179",
          "sha1": "0c0415e93c0fb6895eb942e07a673b5f5ec85d7f",
          "md5": "95ea699d01df6d47b07ef5843e915a91"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-SNAPSHOT/util-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
