{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-SNAPSHOT/util-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cn7y7pbly5dqffluewyd5ncn5e"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "da0796332cf269822c16709fca349445756271c570b1aded2e3d34cf6b11dadee1ff69c422923a243a3c8039e0f510a9c7ed462d4bab8033152a00cc624cc54c",
          "sha256": "12562f970e558ac250a23f9096108ad2264ce74f858ffcde3910c0569cc60184",
          "sha1": "bc5f5453adb3787b4fc2717da7e6b3b6b2405cce",
          "md5": "bcd8845d808f7ae0e7f1f475d9d88cbf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "da0796332cf269822c16709fca349445756271c570b1aded2e3d34cf6b11dadee1ff69c422923a243a3c8039e0f510a9c7ed462d4bab8033152a00cc624cc54c",
          "sha256": "12562f970e558ac250a23f9096108ad2264ce74f858ffcde3910c0569cc60184",
          "sha1": "bc5f5453adb3787b4fc2717da7e6b3b6b2405cce",
          "md5": "bcd8845d808f7ae0e7f1f475d9d88cbf"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-SNAPSHOT/util-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
