{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-SNAPSHOT/util-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qfxdttj5qnao3aqvaaugb32xmm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "445f77afe0a5c72554c8d65048103f3e7d1ac180db92d82cd4a330c2b6252a30057e6937725dadb426654e23b6e471afae5bfb6698676fb60eeafd397b9f4247",
          "sha256": "5b75bb87fccfbabfa48f9650d9cdb1b920be2388b41fefb550d0fa2f8d07bc3a",
          "sha1": "4e9c22959edec3dd728e4c69776f848bf1c2d83c",
          "md5": "73e6e6526703cf641c1ebc58f58878cb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "445f77afe0a5c72554c8d65048103f3e7d1ac180db92d82cd4a330c2b6252a30057e6937725dadb426654e23b6e471afae5bfb6698676fb60eeafd397b9f4247",
          "sha256": "5b75bb87fccfbabfa48f9650d9cdb1b920be2388b41fefb550d0fa2f8d07bc3a",
          "sha1": "4e9c22959edec3dd728e4c69776f848bf1c2d83c",
          "md5": "73e6e6526703cf641c1ebc58f58878cb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-SNAPSHOT/util-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
