{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "2977192",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "l2dfpflk7bgankgfihmc46sw24"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-metadata-2977192.jar",
          "url": "test-util-2977192.jar",
          "size": 3389,
          "sha512": "dd830ec87e5f5ad89be1a2535298dceb40f288b0d414905732037a914e1f38f86cbb96e18f1a2dd89df18443dab6d70c9d281ed038c4fcdded51cb6187f5ff64",
          "sha256": "968a749eaf11cbce3eb792f091214a320db8d0057c3e8db5b4175bbf01f2b273",
          "sha1": "b2b4808cc08ff213b25eeab6e76eb337112b3670",
          "md5": "a5f3bbe6d07d6d9eb88fc365fe64636b"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android-debug/2977192/test-util-android-debug-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android-debug",
        "version": "2977192"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android-debug/2977192/test-util-android-debug-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android-debug",
        "version": "2977192"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android/2977192/test-util-android-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android",
        "version": "2977192"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android/2977192/test-util-android-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android",
        "version": "2977192"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosarm64/2977192/test-util-iosarm64-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosarm64",
        "version": "2977192"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosx64/2977192/test-util-iosx64-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosx64",
        "version": "2977192"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-jvm/2977192/test-util-jvm-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-jvm",
        "version": "2977192"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-jvm/2977192/test-util-jvm-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-jvm",
        "version": "2977192"
      }
    }
  ]
}
