{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.7.0-SNAPSHOT.jar",
          "url": "fhir-java-1.7.0-SNAPSHOT.jar",
          "size": 1012286,
          "sha512": "5c20bfd23f3eaf922c37c9f96e46cbd4cdb8cb90b3ee990239c9c734f9172d0bbd0a826ff34d60c77ec354097ddfbf35e2922084f0585372456d774a90e94db7",
          "sha256": "3fd39d22b0b4893adf2c72a9451474cde1cba68ad2a821235b3ef2c619110279",
          "sha1": "3d8536978bab114bd4a022ea087c71a3daf354cf",
          "md5": "171c9e077990eb00ce6ecb6df2a713c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.7.0-SNAPSHOT.jar",
          "url": "fhir-java-1.7.0-SNAPSHOT.jar",
          "size": 1012286,
          "sha512": "5c20bfd23f3eaf922c37c9f96e46cbd4cdb8cb90b3ee990239c9c734f9172d0bbd0a826ff34d60c77ec354097ddfbf35e2922084f0585372456d774a90e94db7",
          "sha256": "3fd39d22b0b4893adf2c72a9451474cde1cba68ad2a821235b3ef2c619110279",
          "sha1": "3d8536978bab114bd4a022ea087c71a3daf354cf",
          "md5": "171c9e077990eb00ce6ecb6df2a713c1"
        }
      ]
    }
  ]
}
