{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-SNAPSHOT/test-util-coroutine-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "gmisvzmodbai7pe356hknw3ypi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "1648aa28836254bffe740baf2f9dc03a4a02df31200018dd0aad40a368eac06b90995a4bfe77d9da208acf6fb35f128ab63c11814e650aa4175b5e7f39433abb",
          "sha256": "07f522a06a7f5e05fb383075c09756f5e76f030b955c67f2cd118bc3716707c8",
          "sha1": "6f07375b9507ccaa8b8e06b04eafd6d98ee01ba6",
          "md5": "971fbc85726d3318c8d8d297d69e6927"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "1648aa28836254bffe740baf2f9dc03a4a02df31200018dd0aad40a368eac06b90995a4bfe77d9da208acf6fb35f128ab63c11814e650aa4175b5e7f39433abb",
          "sha256": "07f522a06a7f5e05fb383075c09756f5e76f030b955c67f2cd118bc3716707c8",
          "sha1": "6f07375b9507ccaa8b8e06b04eafd6d98ee01ba6",
          "md5": "971fbc85726d3318c8d8d297d69e6927"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.2.0-SNAPSHOT/test-util-coroutine-metadata-0.2.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.2.0-SNAPSHOT"
      }
    }
  ]
}
