{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-SNAPSHOT/test-util-coroutine-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "pfkwo3vk5bcrrgegp4c27elcy4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "2cabf452442c0a6ebab19740fcffd07d01bca5d6217e4942f06eade4203c49f9cf48bedce34d3b0c2afe54748341397cc374549cbb7ce5365911625a93898224",
          "sha256": "d9a8ea5311fd2e9a2ddda21441192c9e1c7f790397e559417edb4cb5e45c1313",
          "sha1": "2670137254787144de77370f1473f738a8edd0ff",
          "md5": "1b290eccc8ebff30dae72943e970fedc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "2cabf452442c0a6ebab19740fcffd07d01bca5d6217e4942f06eade4203c49f9cf48bedce34d3b0c2afe54748341397cc374549cbb7ce5365911625a93898224",
          "sha256": "d9a8ea5311fd2e9a2ddda21441192c9e1c7f790397e559417edb4cb5e45c1313",
          "sha1": "2670137254787144de77370f1473f738a8edd0ff",
          "md5": "1b290eccc8ebff30dae72943e970fedc"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.2.0-SNAPSHOT/test-util-coroutine-metadata-0.2.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.2.0-SNAPSHOT"
      }
    }
  ]
}
