{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-SNAPSHOT/test-util-coroutine-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "spphud3arfeypnlnwvilthgfrq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "9b2342af35ff6d8193da6916fb20ccdb26a4e5c3a95d8b6551e44942479f06cbea5e8017b63ddb5d60471576411911c466f9529745cc03644e257e82ebb6372f",
          "sha256": "f332f776798ca66b3a238ec7c066f93e81eb3498c59de6973b6a50e175863bd2",
          "sha1": "0d94456a9a2ded48e215425568566308aa938de0",
          "md5": "eea40af501208cbfe2e33e80b7ba647a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "9b2342af35ff6d8193da6916fb20ccdb26a4e5c3a95d8b6551e44942479f06cbea5e8017b63ddb5d60471576411911c466f9529745cc03644e257e82ebb6372f",
          "sha256": "f332f776798ca66b3a238ec7c066f93e81eb3498c59de6973b6a50e175863bd2",
          "sha1": "0d94456a9a2ded48e215425568566308aa938de0",
          "md5": "eea40af501208cbfe2e33e80b7ba647a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.2.0-SNAPSHOT/test-util-coroutine-metadata-0.2.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.2.0-SNAPSHOT"
      }
    }
  ]
}
