{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "cr7aipwp4zds5prtqxbgexzwii"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "8b6074986be3b760db5e6fa79f1cf381afbf81884459112ffe3de2e423dd3a6b6145475b1aef3b5cb7f7069d8cec400574eaea56a72ce5ae6c82f36c2fc5166e",
          "sha256": "8e5766281ac18668748e2417eb93b7aaf36389f3fabb9b6f93e6408dc7250b35",
          "sha1": "6ab40f33aebac6a8cb5f75e5c3b6b6fccc4d3e66",
          "md5": "f169bb048819bc47ecc848f3c6ebc418"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "8b6074986be3b760db5e6fa79f1cf381afbf81884459112ffe3de2e423dd3a6b6145475b1aef3b5cb7f7069d8cec400574eaea56a72ce5ae6c82f36c2fc5166e",
          "sha256": "8e5766281ac18668748e2417eb93b7aaf36389f3fabb9b6f93e6408dc7250b35",
          "sha1": "6ab40f33aebac6a8cb5f75e5c3b6b6fccc4d3e66",
          "md5": "f169bb048819bc47ecc848f3c6ebc418"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
