{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "yfetf67ltra6lbtwz4p3ohm6zi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14516,
          "sha512": "f32d3c705f4f3982e6dddd93e48a1e3e47534623da0369f251ba8b0328fc86b538193da7173693418f838fe1193bb0186a55060f22525f8f1f294b5dc8ceb2dd",
          "sha256": "00816a43c3d160cd461e6146db0e81980f823f03bc25c497ec7d6d45d2daefbc",
          "sha1": "4b3ae63eb18bac6c8ab901b257b7ff13fe161927",
          "md5": "fa8b41b90bfae526d7100b99c43b862d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14516,
          "sha512": "f32d3c705f4f3982e6dddd93e48a1e3e47534623da0369f251ba8b0328fc86b538193da7173693418f838fe1193bb0186a55060f22525f8f1f294b5dc8ceb2dd",
          "sha256": "00816a43c3d160cd461e6146db0e81980f823f03bc25c497ec7d6d45d2daefbc",
          "sha1": "4b3ae63eb18bac6c8ab901b257b7ff13fe161927",
          "md5": "fa8b41b90bfae526d7100b99c43b862d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
