{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tk6kp7m4vjdzfa6imn67mvi7qi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "3c54082c9451ec5998dbf36615d399a364736dfc1b87f35caba4d759ce631205fa49616416f7337dc5d53e168ba2173d85f29c1d6b24058e92eed0caafbe3c65",
          "sha256": "079ca79fb02e6aed56ec4d44481905e56faaa768c57384b4f734bf90058107bc",
          "sha1": "354949850ca46bb0877b9a20bb443862db850b02",
          "md5": "148f2eabdc6c45a9028068d937dab877"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "3c54082c9451ec5998dbf36615d399a364736dfc1b87f35caba4d759ce631205fa49616416f7337dc5d53e168ba2173d85f29c1d6b24058e92eed0caafbe3c65",
          "sha256": "079ca79fb02e6aed56ec4d44481905e56faaa768c57384b4f734bf90058107bc",
          "sha1": "354949850ca46bb0877b9a20bb443862db850b02",
          "md5": "148f2eabdc6c45a9028068d937dab877"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
