{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "f3qhtsysgbb6roioxpnpnalh7u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "0904148781edc569ed1b5f45d3b0490d703ab2cd2b4bf9d233efa06496f305c1e8ae5b6c3619bcfa793b13ac39d94e5ee61584d34352cea635468c7c684990b0",
          "sha256": "00e6af250d704bc909a89cccea7246cee0a25662d5627fc601e04384fb6620b8",
          "sha1": "f030c50d9f6af21872290a0a4748a27f941c21c8",
          "md5": "dca338c1997b932c69526978a7ed6421"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "0904148781edc569ed1b5f45d3b0490d703ab2cd2b4bf9d233efa06496f305c1e8ae5b6c3619bcfa793b13ac39d94e5ee61584d34352cea635468c7c684990b0",
          "sha256": "00e6af250d704bc909a89cccea7246cee0a25662d5627fc601e04384fb6620b8",
          "sha1": "f030c50d9f6af21872290a0a4748a27f941c21c8",
          "md5": "dca338c1997b932c69526978a7ed6421"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
