{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bqk6vzudjrhuzk3twx7xlzfexi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "7546134fc982483c07e1404aaa32662ca77ec001b12293b39e0492e04cbc9652e7cc95aaa87ef480285e7ca70a9cbd798587fcbcd4dd1d5ee673c0efe22e66f9",
          "sha256": "118a51911c16afde97661f06ac38d4e0296422117bede90e86b4c9433f58259f",
          "sha1": "62b459af7c44ab670cd1f4bdb8ae6e324887b59a",
          "md5": "4cb90cb4d85b8ea19d33d0cf76b9c0bc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "7546134fc982483c07e1404aaa32662ca77ec001b12293b39e0492e04cbc9652e7cc95aaa87ef480285e7ca70a9cbd798587fcbcd4dd1d5ee673c0efe22e66f9",
          "sha256": "118a51911c16afde97661f06ac38d4e0296422117bede90e86b4c9433f58259f",
          "sha1": "62b459af7c44ab670cd1f4bdb8ae6e324887b59a",
          "md5": "4cb90cb4d85b8ea19d33d0cf76b9c0bc"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
