{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "27mjf4gx3jc7pms4hixoqd43dq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "3c2f5347a7d49e6c79bd6e87a99821a3a16ad2ed7332c9108c726724511f13bffa31c539e654fe4bede51971497a879961b60bc6f85951728e834be1ccdf234d",
          "sha256": "3e13849dcde17fbe6999f56bd7c74d28503b29f22f6b51c659d15b8f86550fb3",
          "sha1": "6dc02415ad30249d39c3bc836863a273e5005917",
          "md5": "a9f187a01f453a9ea5cadb7d3cfd0ea9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "3c2f5347a7d49e6c79bd6e87a99821a3a16ad2ed7332c9108c726724511f13bffa31c539e654fe4bede51971497a879961b60bc6f85951728e834be1ccdf234d",
          "sha256": "3e13849dcde17fbe6999f56bd7c74d28503b29f22f6b51c659d15b8f86550fb3",
          "sha1": "6dc02415ad30249d39c3bc836863a273e5005917",
          "md5": "a9f187a01f453a9ea5cadb7d3cfd0ea9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
