{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "vxerz33uunfl3matk4acnlbp2q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "ed60e44d80b5853307f6951695a48640b606552eac6114bfdd480e3e33a484edbd2b30cdf63477bdb9a67479c8ec986b9bee0c256fe111cffaf2b865a5a16362",
          "sha256": "ffdc82b64e52dcacfe6d92890d79372ef7680e9ccd01de89724ecc6b5dfecff1",
          "sha1": "0ca2143b27eb07382d72de1670d2b0bc3d7c9273",
          "md5": "b80ec48ed11faa2a45d09025ed4d0ef2"
        }
      ]
    }
  ]
}
