{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "qeacrvx7oza2vooklwp37d57o4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "97d9e177f46a8756b64fc0e3a53cc06a9e59dfb50edf17a1f1cb5df25e567e99705ada1e594a93181d7fc7c452482cecd6f64003020d0e9af2b3b51bd8938722",
          "sha256": "5d08e8c06a0021b650951f8ee8aa1773b99da18d7f52c32a1a56da471ed78b6f",
          "sha1": "e55e5e7e11c13852c8b79f54e001cc6645d10b68",
          "md5": "53178f227fce29486d396956dcf7158f"
        }
      ]
    }
  ]
}
