{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "us6apo6pzfe7vaxfy4dax4sowq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "3c88907a43ffa857179d3a22bf1ca758292e9ee044d290c228189b2c553d2405093ae60a35cebb51594aa422c098d67a7a1fbd4b8acf235564a42771566158e0",
          "sha256": "f1565e7935ad73f9b544bf8bafe6acad691660780d2f13dea71c3b27523d200c",
          "sha1": "66cdba7f7f0559456ba60bf48b1c940b4cc6cea4",
          "md5": "d933025d7cbc1acd98000f4e0df2d254"
        }
      ]
    }
  ]
}
