{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "pgmt23hk55f2tpmeundvbkseca"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 33909,
          "sha512": "49c39926e7fec94ba57cb6f3d9ca6f5de81d9b9b2705d26d8d1401a806d8eef9d7cf5868196b721ffcc768179af504009939603e748d7e696ce0cab4c23cd263",
          "sha256": "0763603402968e5356c264b8e923711fcb9c267d5a0396b61359a65a8e0ba630",
          "sha1": "fc78838fa94e2c829184d803e36dc027bd3ef100",
          "md5": "19433ee5de1a3c1f8358a2eb1faa029c"
        }
      ]
    }
  ]
}
