{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "zrnjrrummfhnxofrx7tkeffehu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "778509ce43a2c6cf681f861b5cc1c68008debc27ab8e1713e357926d3046753609ff72c997391bc381290bd826f6f6acc0e5f008f6d93ab1a588524f636033b2",
          "sha256": "299f67eb2455b01755377fcab8de41921e7aa87857f6bacc6f0b50e2a22bf413",
          "sha1": "55e7d4e1868dc4bdc4eb8a53fdde330445ea8224",
          "md5": "254cb6901e5cdffbe1146447c0f793bd"
        }
      ]
    }
  ]
}
