{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "ws5da64stva7nb7u2dhb4xmqle"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "4993cb8923d092934cc93cf4f2da2efbd8cbb2859d3e33e3c03da49f68f8c2040d9c74f88da83e9599b86d8449eaa2d81c721789110de57b3032b50ec4696105",
          "sha256": "352d1e956f2ff8399db59bd0fef60457b244eea00a7fffc35fad82a4373f13f1",
          "sha1": "801aed2579b9e63b6d5fcecad19bac33a7a8d6a5",
          "md5": "0d747881570958d5f2c4ff43abf612aa"
        }
      ]
    }
  ]
}
