{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "nt2i5mindzdehofyz3nqvxnp4e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 48107,
          "sha512": "b7cedcf2a4fbec5e0bb07656d14738ab9ba1ce41cb706880fd575cd0ebfdc7d4d6327b5e4b5ca6cfede996a3ef4960bc2338f61c2925c4c5fa86f2a226a931de",
          "sha256": "230f69c980e990f637626e339ca2a45b4ce25ffab0ef32eb9408cd52612d1dee",
          "sha1": "d04108ab838dd6e277a7a179ec5aeac86b22cd27",
          "md5": "41462d2c9d6f93a84db2ebb57dc6d8f4"
        }
      ]
    }
  ]
}
