{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "wqmjyeo7q5fdrla7hjnyshmv6m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 48107,
          "sha512": "cb5889a7a6a28f07a8e5ca807fb6b57f3f881612d70a748072db730c0a3e421c91d87a9e6371ea77fd80ca3e2e1c8c1692489aa29e6878fadd6ce0f7c476a899",
          "sha256": "7acb88fb205508d15404f6e585a40f5a816499f3c46a4907593cf714ca6ccde3",
          "sha1": "299e99bb5216d8bce363ff7793537307f28685b8",
          "md5": "26fc991a6cb4fd718c9b89b6814554b8"
        }
      ]
    }
  ]
}
