{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "or5barz4vvc6hd2ibtjche3pam"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "b276bdba1ac98475c3d12ce36694bab82a6d2562c057b0a9769aeb4d1f3efa984107d752e94e25af68192e09474c685ef134fd106cf8bbadea6513b864b377eb",
          "sha256": "a4230e2a75545c19f240126b8aa74515a01d9eda24c3b60761af7271b5a97965",
          "sha1": "1af1d2b45a668f2121c7148432ce42d0e7305494",
          "md5": "a04ff6a0897eb2c08e73354315ba3c6d"
        }
      ]
    }
  ]
}
