{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "siclic2xhbfetof6sjmt6kwviu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "size": 87691,
          "sha512": "b074776367b7a0ab40628d6115eacafa172b68c6c3498be3c78ea971c8b57e5cc3b243d77701167cc698d92c18ec41195482070741b13bbd9b5446fe42fb0e5a",
          "sha256": "00f2cc3c7186d5070dd200d73f89dfc8dafa876436c7c65cbd7fb38aca437da1",
          "sha1": "d0de4f9c10036c562376075ba50fb6538af0fadc",
          "md5": "dd7868f814b93a5c3dace2d2688764b2"
        }
      ]
    }
  ]
}
