{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "zs7sezq4w5eo3hccsvfps44fva"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "size": 76053,
          "sha512": "5e73828e0a871d86fe0245fb3b3ab918c38581d10821649e79a10cd683a46faac0c71f0b344cebe600921941ca8a52aa3804454cd0db3672fd79eba1196aef2a",
          "sha256": "35f19f5b463c3e055ac5efe545deee515410c2dbf0099e89448121045553fafa",
          "sha1": "3d3031706965e6aa5f7af1a05ffe7d95e0bbcb2c",
          "md5": "a47b0212c1f986a71e2d531b7a6c31e8"
        }
      ]
    }
  ]
}
