{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "46nrgzsgpnbfpe3jinbiwtuf4i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "size": 80551,
          "sha512": "d666e5faf0301aae77b1fe8996bfda4dcd2683c418f1175188ab31cdf356dd31d2c58f810aac17d996f3eb267604ae33963f787b13b64979c363934ad358deb4",
          "sha256": "d9491e293396cac9b5c1159532ee9d66d54141afebadc44c77718b834cb3718e",
          "sha1": "cbd48c22338aec3602f167839d9db32c16c6e31a",
          "md5": "1a01483ba12426ab084bc2a21b186625"
        }
      ]
    }
  ]
}
