{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "fljch3q5pbezrjggbx6yjad65e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-SNAPSHOT.jar",
          "size": 97923,
          "sha512": "01c485c82d2bda1a886dd902bf29010a64344603f64bfc3c026a584afbf6f9a2043b35cbe915445f673fda5d361dd2956e512dec72c1f9e5399f1a27c13cbb12",
          "sha256": "20b3cb74f23084dfccf56de97dfa5bf884f6296e26e4b88ab722f145d1a66113",
          "sha1": "e7721092a22861ab438267c8bec1ec08c01c1430",
          "md5": "34e2526842211431c222fd6fe2ba351a"
        }
      ]
    }
  ]
}
