{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fikn64roh5byxnsmbsaizxjoyq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "82eba433e97d88d3908e09dc53cdbe493d5d0b04062a48bc334319b996347a874fdd7799f2f66ec4a7f559bdab042fe3bf2d5ff009cf81842ce33b6eae89623e",
          "sha256": "ace68ff4c92db35ec1abc1a68d651da5aeb20d4bd4448cf5aef57084e16ea50c",
          "sha1": "6e21374398e49341afce7083d77e5e89055d5412",
          "md5": "ef0a1ffd1ffec6556e631756c9188894"
        }
      ]
    }
  ]
}
