{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "63xl4settnbaznonocozsvzjkq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "0c289aa86d1d5db3e66df70de97ac3c2994cabb7583923e4203f170c088b42205c85af35d1aa5803637fbad2b8d1455f96014367806b6ad9d267232de7011bc9",
          "sha256": "82f0dcf6f757aa4261cf328f265fed272b6ca66b3fd62826db7f6fed9706221f",
          "sha1": "3fd8ebc5d65e473a98fb6363e068c01b2016eb7b",
          "md5": "067102292480f43a9286ed64e991bd2e"
        }
      ]
    }
  ]
}
