{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor-jvm/0.2.0-SNAPSHOT/test-util-ktor-jvm-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor-jvm",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "gmisvzmodbai7pe356hknw3ypi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-0.2.0-SNAPSHOT.jar",
          "url": "test-util-ktor-metadata-0.2.0-SNAPSHOT.jar",
          "size": 3186,
          "sha512": "0463c9e8cadd002775db2af91b13927ce05bf6362a0dedb335a9a64312d06f3bb2d2bff561652d55cb267981c87207c7be217cf18601bc18bba1284726ffc753",
          "sha256": "530fdb70aa69ebc6444c30e84e6e130d3d798a5f6de693e4c9c563a0ccebdc11",
          "sha1": "766a32c41a88fdb707f9d9fbeb43cbeac93d2652",
          "md5": "d7296d55d5559f4accead2dbe3513237"
        }
      ]
    }
  ]
}
