{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor-jvm/0.2.0-SNAPSHOT/test-util-ktor-jvm-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor-jvm",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "spphud3arfeypnlnwvilthgfrq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-metadata-0.2.0-SNAPSHOT.jar",
          "url": "test-util-ktor-metadata-0.2.0-SNAPSHOT.jar",
          "size": 3186,
          "sha512": "fd01a39e7a7c8c2f8c1c30faeeafa3770374c6cc58acb5411e0c2df0ad951df81f3c17c273e2a4a01ea1ff16561d9d61af99af1071af121ea4a9ac239d10e701",
          "sha256": "2a37c276aa45900577341fc589c081e455406fdc804fff496bd7003334af4389",
          "sha1": "80034400bb0c15c6f4b9411f1a95da8e273d6dd0",
          "md5": "e957dfb2bd9ca3ddaaa3a165d6614bc7"
        }
      ]
    }
  ]
}
