{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.8.1-SNAPSHOT/util-coroutine-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qfxdttj5qnao3aqvaaugb32xmm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.8.1-SNAPSHOT.jar",
          "size": 2237,
          "sha512": "d0e6c46fa2beabebaf5854fb53bdb6965acd882d8ef944906bb978cd8b17573c8d0d46ba3d448d2ec0580a25e390ad324a0da408cadaa9e419aa166d72b03c36",
          "sha256": "7d43a0e49ae3227d9fd0ee971c332a87e988b6f692f03669ee412f6dcb5df1cd",
          "sha1": "cc4430d23211860ddb6e5c58f8f92ad398442745",
          "md5": "643097a9d28cb56171421976cb945282"
        }
      ]
    }
  ]
}
