{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qlgearrk4vexthlm7fxtai5hci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7780e34f99f90904dfa4c3040ae3a8a8602b24aad5ff764d4984b79e9facf17740ce87455220703bc54fbae36c3e517c7390e1c78ac4f97c5c965b29b282027f",
          "sha256": "693169a3d45006e29d9a581d977bbdd487f231b3bca86b5e14e79cb2ee291487",
          "sha1": "21bc2e8ad90d113b8f9176423914448e3fb04f01",
          "md5": "e1ea24fdc2b4a5956348046d09f8330c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7780e34f99f90904dfa4c3040ae3a8a8602b24aad5ff764d4984b79e9facf17740ce87455220703bc54fbae36c3e517c7390e1c78ac4f97c5c965b29b282027f",
          "sha256": "693169a3d45006e29d9a581d977bbdd487f231b3bca86b5e14e79cb2ee291487",
          "sha1": "21bc2e8ad90d113b8f9176423914448e3fb04f01",
          "md5": "e1ea24fdc2b4a5956348046d09f8330c"
        }
      ]
    }
  ]
}
