{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v7c5s6v2vjg5rppvy5jghwttee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "21e4d96e90e44748555d5f88904ea519668f7a548d248778d2ef1831bdb31ac4c2c5c537d708b21b932e9ded9635c4059fdacc5356d75c2070d6f5de6ce6608d",
          "sha256": "a8468255a6cd42e2aca0fc282ab2bd360934d5e867e91bce29e2901407aba48e",
          "sha1": "45cf08de1c6d6d52ca0dae9c0ea389b9585e7848",
          "md5": "46a9db1d3ec9ecc2afbf8074f5bc6fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "21e4d96e90e44748555d5f88904ea519668f7a548d248778d2ef1831bdb31ac4c2c5c537d708b21b932e9ded9635c4059fdacc5356d75c2070d6f5de6ce6608d",
          "sha256": "a8468255a6cd42e2aca0fc282ab2bd360934d5e867e91bce29e2901407aba48e",
          "sha1": "45cf08de1c6d6d52ca0dae9c0ea389b9585e7848",
          "md5": "46a9db1d3ec9ecc2afbf8074f5bc6fc5"
        }
      ]
    }
  ]
}
