{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6td4tx6r4vgjnizjuoyabpxdke"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a97daa6981a92335b52826238f288a47142b7f50c8e3c08937e4baa4c38e3bdae01317815af454c59309b406cc4b19cee659c0cbf65bbd9ee27de9cffc075ea0",
          "sha256": "84156590550ab390048d1ef18b6d013081bd3fbc2ca02809837972cca3ea9c5e",
          "sha1": "75d3b038045e0f5f06adab853b90641638c6ddc9",
          "md5": "a37128247e8f6bc13fbf2fce94256df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a97daa6981a92335b52826238f288a47142b7f50c8e3c08937e4baa4c38e3bdae01317815af454c59309b406cc4b19cee659c0cbf65bbd9ee27de9cffc075ea0",
          "sha256": "84156590550ab390048d1ef18b6d013081bd3fbc2ca02809837972cca3ea9c5e",
          "sha1": "75d3b038045e0f5f06adab853b90641638c6ddc9",
          "md5": "a37128247e8f6bc13fbf2fce94256df5"
        }
      ]
    }
  ]
}
