{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cx65bhetunaoxfxltujfxjmqbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "1ad665fa1c98a9be9ccfa15a20cd4247d2b316ba0f581a640eb4f6fb4a3cb70f932759d2459fc85cec8a26af7b2b260026977bd7c5715f0352d7a374ee38a36e",
          "sha256": "45fb9ca469fbd5f754585aa09f0395a42f551f83b92e70e5767d7a8a8aa106b6",
          "sha1": "431ce76ea394f46e9c200ec704ce05106f66fb81",
          "md5": "9cd22aee972ea4ee4910e5644dc9f073"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.2-SNAPSHOT.jar",
          "url": "securestore-common-1.13.2-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "1ad665fa1c98a9be9ccfa15a20cd4247d2b316ba0f581a640eb4f6fb4a3cb70f932759d2459fc85cec8a26af7b2b260026977bd7c5715f0352d7a374ee38a36e",
          "sha256": "45fb9ca469fbd5f754585aa09f0395a42f551f83b92e70e5767d7a8a8aa106b6",
          "sha1": "431ce76ea394f46e9c200ec704ce05106f66fb81",
          "md5": "9cd22aee972ea4ee4910e5644dc9f073"
        }
      ]
    }
  ]
}
