{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "na63yrchpvcdtb4r5giuarm5sa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "ff4775fc0d409ea289ae8471f24534e003f6d6263ca1792b06c2524dc434c153af692982ecdbce14033cea90da9f67906b24bd9cb0fe4cd8f2384c2e854dd5b5",
          "sha256": "65dd089c4fd8d18731bf3f40b4b6c2210c719830c243c84cdbe79aebbf6bc00c",
          "sha1": "b5a411cb8e00ac5dcdc22843466649d648862320",
          "md5": "4f48c6d2c20b27881dc4791a56989182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "ff4775fc0d409ea289ae8471f24534e003f6d6263ca1792b06c2524dc434c153af692982ecdbce14033cea90da9f67906b24bd9cb0fe4cd8f2384c2e854dd5b5",
          "sha256": "65dd089c4fd8d18731bf3f40b4b6c2210c719830c243c84cdbe79aebbf6bc00c",
          "sha1": "b5a411cb8e00ac5dcdc22843466649d648862320",
          "md5": "4f48c6d2c20b27881dc4791a56989182"
        }
      ]
    }
  ]
}
