{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test/1.9.0-SNAPSHOT/util-coroutine-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6z4fkle5wnaqjjlveuh7aydgvu"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-test.klib",
          "url": "util-coroutine-test-iosarm64-1.9.0-SNAPSHOT.klib",
          "size": 7642,
          "sha512": "e4af5b2d1bdbf3ceb9feab2e9376849a38514889e940c0a5db157ea71695bf1abd3a4e5a695b3a728be2437bdf0a0777246b3a31bf21d9a379689ff9b9a7a02f",
          "sha256": "649f9533c22a5bdaa9afba2d9e03906238956b2642608ba11b63462c06892db5",
          "sha1": "20228e3f655b41cb8244bd6cf8835ffb8d891c11",
          "md5": "c61557c8a6998a988987610d81f2e662"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-test-metadata/1.9.0-SNAPSHOT/util-coroutine-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
