{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/7d1124b/objc-util-7d1124b.module",
    "group": "care.data4life.hc-objc-util-kmp",
    "module": "objc-util",
    "version": "7d1124b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ahdv3iseczasdgttuivbnwh5tm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosarm64-7d1124b.klib",
          "size": 8689,
          "sha512": "afd62b46191a0f4ce5a65199f8bb4f8fea739bfb020d2d3d344dcb987361bef15544f7aecc89c58bd85490203a72007c41f46578e7bbcdc7c7f2839e829a4c70",
          "sha256": "0ef2fd302e49f0af6b0f2970f4e3b6d01b82b67aa35b833aa174cf93b9b79882",
          "sha1": "ebbdceff4c64b267ddf6a1b8deadbf34d06424b3",
          "md5": "5e92301bf10768a0f43436d415d30354"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../objc-util-metadata/7d1124b/objc-util-metadata-7d1124b.module",
        "group": "care.data4life.hc-objc-util-kmp",
        "module": "objc-util-metadata",
        "version": "7d1124b"
      }
    }
  ]
}
