{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.16.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.16.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.16.0-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.16.0-SNAPSHOT.jar",
          "size": 19820,
          "sha512": "55fc3b7317c8317f0acc3c17e3ba96a8c3bfa1f9d13b276f6eb5d6d747b83b560d64d59f41f51889b357ff137d5909c07d2c09b814eab6eb14d71a447d95d48f",
          "sha256": "6032011dad95f374aa2191049679aecfa884134971664f8279531219909edb61",
          "sha1": "f1d48d0901d4924ae718478505368cdc0488fb22",
          "md5": "1dbd49f5b8272c764993e808b4f9346e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-auth-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-crypto-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.16.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.16.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-helper-sdk-kmp",
          "module": "fhir-helper-jvm",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.16.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.16.0-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.16.0-SNAPSHOT.jar",
          "size": 19820,
          "sha512": "55fc3b7317c8317f0acc3c17e3ba96a8c3bfa1f9d13b276f6eb5d6d747b83b560d64d59f41f51889b357ff137d5909c07d2c09b814eab6eb14d71a447d95d48f",
          "sha256": "6032011dad95f374aa2191049679aecfa884134971664f8279531219909edb61",
          "sha1": "f1d48d0901d4924ae718478505368cdc0488fb22",
          "md5": "1dbd49f5b8272c764993e808b4f9346e"
        }
      ]
    }
  ]
}
