{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.9.0-SNAPSHOT/util-coroutine-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6z4fkle5wnaqjjlveuh7aydgvu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.9.0-SNAPSHOT.jar",
          "size": 2237,
          "sha512": "2968deecc7573363d27d7e39ab88e248a01a317f5a3bf1a7ea45e330fd228566859771b6d9fd60a21bdaffe3f6e964896625b520c65feeeba334ef91a687f8dd",
          "sha256": "42397193964d18e672a84ee454a97baa4139b21d129083a6baf5db1bed8e55f6",
          "sha1": "f166bb871f6a0a936b56701612830f313e677e73",
          "md5": "c6b892492fa0d8bff980a86eabfe0d9f"
        }
      ]
    }
  ]
}
