{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2/crypto-1.13.2.module",
    "group": "care.data4life.sdk.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "prpp2tshbvdhjho4hpqafndq5m"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "26b99cc9e226b9b287d281caf123529481885c23c3140715bff0bfc9369f27226f6c3ff6c2a2ad7c8eb6b4a1d47feeaaa49ec8c10d5cc5796defebb3041c5c28",
          "sha256": "d5c6884b6aee9a10de9773731f21a674552a4ba58a0f813487d248f9d4ac071f",
          "sha1": "2cf7722aaa2a3cdbbf926876d453c43646440721",
          "md5": "303f30074b172990f839ce4155b6e54c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2.jar",
          "url": "crypto-jvm-1.13.2.jar",
          "size": 56992,
          "sha512": "26b99cc9e226b9b287d281caf123529481885c23c3140715bff0bfc9369f27226f6c3ff6c2a2ad7c8eb6b4a1d47feeaaa49ec8c10d5cc5796defebb3041c5c28",
          "sha256": "d5c6884b6aee9a10de9773731f21a674552a4ba58a0f813487d248f9d4ac071f",
          "sha1": "2cf7722aaa2a3cdbbf926876d453c43646440721",
          "md5": "303f30074b172990f839ce4155b6e54c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2/crypto-metadata-1.13.2.module",
        "group": "care.data4life.sdk.hc-crypto-sdk-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2"
      }
    }
  ]
}
