{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2fykjxuc6vf33k272qokyyctfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "cfde670438602cb8f8f50e42c92d8012f3d67c91558825294f61f3aece35e5b29447b7830e0bc178b2d08a947f37bc53a7ffadf2f6b5fa0a76a1ea972643ff2c",
          "sha256": "6cd5c5908e4d8e0db715ed80cc45a364e1e23fb0bb29bd5feff24d8c1209c424",
          "sha1": "ea89d8c326c3eb080c8375c5a975c24650eafc96",
          "md5": "780741f5b3bd9554608e6ef3c842ee80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "cfde670438602cb8f8f50e42c92d8012f3d67c91558825294f61f3aece35e5b29447b7830e0bc178b2d08a947f37bc53a7ffadf2f6b5fa0a76a1ea972643ff2c",
          "sha256": "6cd5c5908e4d8e0db715ed80cc45a364e1e23fb0bb29bd5feff24d8c1209c424",
          "sha1": "ea89d8c326c3eb080c8375c5a975c24650eafc96",
          "md5": "780741f5b3bd9554608e6ef3c842ee80"
        }
      ]
    }
  ]
}
