{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "auqklhvfwjbcppg4sdkxl2tqjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "91cde5f9e5af26663a4f153858484036f738bd284b8b345b5c73ac92ab6b32b409f2ac4f76d631ab41a92142b862ce2afb4794f3e38ba52b3cd2576907245458",
          "sha256": "87a1a25612ddb257833cc76c1e6f319986cc95ad0f27ce8ccbe39af0495cef31",
          "sha1": "18da32bc2bdb9e33042c94b22f6920e7b4c38c25",
          "md5": "a70ab4185d6f2a2ab17aac8ec2cbc267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "91cde5f9e5af26663a4f153858484036f738bd284b8b345b5c73ac92ab6b32b409f2ac4f76d631ab41a92142b862ce2afb4794f3e38ba52b3cd2576907245458",
          "sha256": "87a1a25612ddb257833cc76c1e6f319986cc95ad0f27ce8ccbe39af0495cef31",
          "sha1": "18da32bc2bdb9e33042c94b22f6920e7b4c38c25",
          "md5": "a70ab4185d6f2a2ab17aac8ec2cbc267"
        }
      ]
    }
  ]
}
