{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n2g3z3c4ejfnpmwgn7cyvo5rmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "47b2c136d63eca4271f6e7edef3ae1caa7ab52a42d6b632c6141df34f9fe3b8fcd40c07eb7f6da59f3a571b82ab049ce2ec35e5944f8714fb9bbc7fc0574d7de",
          "sha256": "3cc948eaa0e1ab6258cf9b386adb687e74b3910fc012fb3f7b00e3a04a3190af",
          "sha1": "b340833512e02dec339942b5c8e981d1c38526b0",
          "md5": "40544f4d8aec7fecc84b869f56ad790e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "47b2c136d63eca4271f6e7edef3ae1caa7ab52a42d6b632c6141df34f9fe3b8fcd40c07eb7f6da59f3a571b82ab049ce2ec35e5944f8714fb9bbc7fc0574d7de",
          "sha256": "3cc948eaa0e1ab6258cf9b386adb687e74b3910fc012fb3f7b00e3a04a3190af",
          "sha1": "b340833512e02dec339942b5c8e981d1c38526b0",
          "md5": "40544f4d8aec7fecc84b869f56ad790e"
        }
      ]
    }
  ]
}
