{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lenvfmshubfgpfcwxttldlaas4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "f464078faaa64b2db4895e9051971d6227846ce642308bb84449b9c13e3f5133c2a02470b3f6b499c8a77dcc0773c820bbaf1a069536849ba46d7a92d1d0d301",
          "sha256": "b83ac86014e378b2fddd476d3d97010aff4b7c6b81ccc6567b2e113322b2b10e",
          "sha1": "67332b5c54317297995f87798d6d6d9b9f98be2c",
          "md5": "9a9c066e23c721ab7a74896f939a802b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "f464078faaa64b2db4895e9051971d6227846ce642308bb84449b9c13e3f5133c2a02470b3f6b499c8a77dcc0773c820bbaf1a069536849ba46d7a92d1d0d301",
          "sha256": "b83ac86014e378b2fddd476d3d97010aff4b7c6b81ccc6567b2e113322b2b10e",
          "sha1": "67332b5c54317297995f87798d6d6d9b9f98be2c",
          "md5": "9a9c066e23c721ab7a74896f939a802b"
        }
      ]
    }
  ]
}
