{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-android",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m2pydfawtvgrhdpvxqkou5byxy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.11.0-SNAPSHOT.aar",
          "url": "sdk-android-1.11.0-SNAPSHOT.aar",
          "size": 27709,
          "sha512": "8a7b2b1e8d32cea39afe25e12ca0e5e96f85c776393a356cad7755d7d7b95b87d71cdb9a47aaf7564b0c91c4b8b396d9d75243f6fbcd118214360052e3446c19",
          "sha256": "4b44aea52a676ca6ffdbe84343ebb0f394e0c2259b00ec4cceafe3266fcf2ac1",
          "sha1": "ad728732832dea9b7e18a02c95f3b063328e649b",
          "md5": "d801b0b35004b470f099b06082627706"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-android",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-android",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.11.0-SNAPSHOT.aar",
          "url": "sdk-android-1.11.0-SNAPSHOT.aar",
          "size": 27709,
          "sha512": "8a7b2b1e8d32cea39afe25e12ca0e5e96f85c776393a356cad7755d7d7b95b87d71cdb9a47aaf7564b0c91c4b8b396d9d75243f6fbcd118214360052e3446c19",
          "sha256": "4b44aea52a676ca6ffdbe84343ebb0f394e0c2259b00ec4cceafe3266fcf2ac1",
          "sha1": "ad728732832dea9b7e18a02c95f3b063328e649b",
          "md5": "d801b0b35004b470f099b06082627706"
        }
      ]
    }
  ]
}
