{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zh7z4xyipzgwlofic22egzwrei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "ef059cf5f96cf7fac522bda7b6a5b0c36de897b005b6d72f6068bcaf473530229389fce9c42cc2b7446e7e09d31e403145e1558b3255bcd16b8843cbef96d8bf",
          "sha256": "e486915c9060b6c1a6faa19739632b323670c384d8c36dccdc8a78df2ea9c0e4",
          "sha1": "2c4feacb3ddf02551c591ed09bcf5b2407bcac23",
          "md5": "18e64bcaf790b3784ca9978c37f9f7f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "ef059cf5f96cf7fac522bda7b6a5b0c36de897b005b6d72f6068bcaf473530229389fce9c42cc2b7446e7e09d31e403145e1558b3255bcd16b8843cbef96d8bf",
          "sha256": "e486915c9060b6c1a6faa19739632b323670c384d8c36dccdc8a78df2ea9c0e4",
          "sha1": "2c4feacb3ddf02551c591ed09bcf5b2407bcac23",
          "md5": "18e64bcaf790b3784ca9978c37f9f7f4"
        }
      ]
    }
  ]
}
