{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nzdlny3vq5gmbk5z5jgjueypsy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7a89c428934bae7c1e7a634ac4267a861cfe0d237c10fbcb12e3c000987832d0978b9687596fe4bd0b30d471131d640437430f264aca669dadbb11305d28a362",
          "sha256": "5be1a06dd61409e83b0b6979e54f722c96993b4926fda2d0ad2dbba8cd32f3ce",
          "sha1": "6c2b5f7b59de0c2d076fc9cd488569c11e887722",
          "md5": "804a6d2f191481bb8bbc6054479f415a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7a89c428934bae7c1e7a634ac4267a861cfe0d237c10fbcb12e3c000987832d0978b9687596fe4bd0b30d471131d640437430f264aca669dadbb11305d28a362",
          "sha256": "5be1a06dd61409e83b0b6979e54f722c96993b4926fda2d0ad2dbba8cd32f3ce",
          "sha1": "6c2b5f7b59de0c2d076fc9cd488569c11e887722",
          "md5": "804a6d2f191481bb8bbc6054479f415a"
        }
      ]
    }
  ]
}
