{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jupbzt5jpzelfhghzkqlld2fme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "e1d75357332e5bbb69abb5216f2704bb7c07dc21ae9d9bee312471e44ac127a3d295dc6647ed8dadea0ec27ba7dd9044b67e664a53f2d0e3e6ec39576a7ef2ff",
          "sha256": "d058c63f2d330c0868372c9fce6a797224490002ded9ffd3b5f53ee6b48096da",
          "sha1": "d5054019db334a66418573d1185074c9a4343f30",
          "md5": "2a0809f4ea19c4f95423fb07f8cf1f08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "e1d75357332e5bbb69abb5216f2704bb7c07dc21ae9d9bee312471e44ac127a3d295dc6647ed8dadea0ec27ba7dd9044b67e664a53f2d0e3e6ec39576a7ef2ff",
          "sha256": "d058c63f2d330c0868372c9fce6a797224490002ded9ffd3b5f53ee6b48096da",
          "sha1": "d5054019db334a66418573d1185074c9a4343f30",
          "md5": "2a0809f4ea19c4f95423fb07f8cf1f08"
        }
      ]
    }
  ]
}
