{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sivb2qegtvd4zomr64qwvu6v7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cbbde73b4019113e0d9e3baaa512f4a4e0f6d9e7748760239d8667bbcb5a44ce8f6a25f2859d16be3492ad3ab2becdcb6af655ba39d85a63abf63586626ae3b2",
          "sha256": "e9f0f2bbceb77f4030d5ef51bea2ebc0d7fa60dee309546c965aa3ae8e6e7415",
          "sha1": "784b72e0c20736c546fb9f2431ca98214c044286",
          "md5": "40d18d01e903a4a574cecfdfb825c67a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cbbde73b4019113e0d9e3baaa512f4a4e0f6d9e7748760239d8667bbcb5a44ce8f6a25f2859d16be3492ad3ab2becdcb6af655ba39d85a63abf63586626ae3b2",
          "sha256": "e9f0f2bbceb77f4030d5ef51bea2ebc0d7fa60dee309546c965aa3ae8e6e7415",
          "sha1": "784b72e0c20736c546fb9f2431ca98214c044286",
          "md5": "40d18d01e903a4a574cecfdfb825c67a"
        }
      ]
    }
  ]
}
