{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gmosjtalmzhnxbkkehus55gdcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "fbf7c3fe2c0294389d80bad5e5e3824934a3794da4b7261a7c53c8f62bc937d31ce697e72b898eb053424920706dca727e0caa199301510623d51cf582d40b79",
          "sha256": "ffae3b6831a1a6e478adf7bf0258e4e019309878a10a3b13769701b6d096d8ce",
          "sha1": "d97138e12d743a95444d3a27f933a4e3ff4cdb91",
          "md5": "82b85aa820a7c341647328b874b2b038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "fbf7c3fe2c0294389d80bad5e5e3824934a3794da4b7261a7c53c8f62bc937d31ce697e72b898eb053424920706dca727e0caa199301510623d51cf582d40b79",
          "sha256": "ffae3b6831a1a6e478adf7bf0258e4e019309878a10a3b13769701b6d096d8ce",
          "sha1": "d97138e12d743a95444d3a27f933a4e3ff4cdb91",
          "md5": "82b85aa820a7c341647328b874b2b038"
        }
      ]
    }
  ]
}
