{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cgs2cyoal5hu5lfvopmqhxsvt4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b081138d13fcf1dccdb5973e03eaf3ff718eaea0c679a1471399e428e32d8e6b5b5c4390eed375040ae3f209dd23676130e4a445e7093a0e28604c9e1202d384",
          "sha256": "ee8d1cdb213fef708bae72917d9da1d7ccefb3aa197509ea0f970563e823db6a",
          "sha1": "640d0a6d57dd850d1471e2745b6a529c84a8577c",
          "md5": "5a81c8c2adcfe16d3c9ea73b882b9818"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b081138d13fcf1dccdb5973e03eaf3ff718eaea0c679a1471399e428e32d8e6b5b5c4390eed375040ae3f209dd23676130e4a445e7093a0e28604c9e1202d384",
          "sha256": "ee8d1cdb213fef708bae72917d9da1d7ccefb3aa197509ea0f970563e823db6a",
          "sha1": "640d0a6d57dd850d1471e2745b6a529c84a8577c",
          "md5": "5a81c8c2adcfe16d3c9ea73b882b9818"
        }
      ]
    }
  ]
}
