{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ihcu3rj3gvcxlhyahobmzsdsfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "70e5199713dd1951886caef70feff76b3ebc7240f3736402286b14914a3c426928b8eaaadd6deb2b5b61c1b0d9488e891b1395834835d59307fcac725d5a24c9",
          "sha256": "07871fd57e7f5bb9d072220e7dc703555d4ae373b4cb5a71c2bc46f50169c409",
          "sha1": "28a9a8102100fd3d97d15b267b5d65abbcd0c6e1",
          "md5": "9fc69a90eaf5590cdd943c9d0db77530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "70e5199713dd1951886caef70feff76b3ebc7240f3736402286b14914a3c426928b8eaaadd6deb2b5b61c1b0d9488e891b1395834835d59307fcac725d5a24c9",
          "sha256": "07871fd57e7f5bb9d072220e7dc703555d4ae373b4cb5a71c2bc46f50169c409",
          "sha1": "28a9a8102100fd3d97d15b267b5d65abbcd0c6e1",
          "md5": "9fc69a90eaf5590cdd943c9d0db77530"
        }
      ]
    }
  ]
}
