{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1/util-1.8.1.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7e2bowb3z5ahtnmdzp2j4zsuzi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1.jar",
          "url": "util-jvm-1.8.1.jar",
          "size": 19627,
          "sha512": "ca6d8cb6bdf519107f89c59026b31b553af32a646a4bcb47592607f29e67e5bce57ad1b0cc2fabf9540f4aa3075ed96f86e421e938c4e582b3ba29c46af971a4",
          "sha256": "00e8bed902d9cc14b3ef03d3cd5adb84cf6642715f676b9d8c0bb11eb604e402",
          "sha1": "4f8e75b890aa18496aa23105d198d867ab1286d3",
          "md5": "45feb33b57d60a2bc92b95e2f3d150c2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1.jar",
          "url": "util-jvm-1.8.1.jar",
          "size": 19627,
          "sha512": "ca6d8cb6bdf519107f89c59026b31b553af32a646a4bcb47592607f29e67e5bce57ad1b0cc2fabf9540f4aa3075ed96f86e421e938c4e582b3ba29c46af971a4",
          "sha256": "00e8bed902d9cc14b3ef03d3cd5adb84cf6642715f676b9d8c0bb11eb604e402",
          "sha1": "4f8e75b890aa18496aa23105d198d867ab1286d3",
          "md5": "45feb33b57d60a2bc92b95e2f3d150c2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1/util-metadata-1.8.1.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1"
      }
    }
  ]
}
