{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zh7z4xyipzgwlofic22egzwrei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "f9fa725141a16cb2a189c2835732176a08e014b19203ea8caaefe07fa5466df78fcd7883399fd59576cff726455ac032e6b6befeb51ca765d60b47cc24c30ed5",
          "sha256": "8ff05838fada064738c4d8b083aa1b36fb1dda8bff6be983ab2bec847858aa51",
          "sha1": "f79370ff903b0180d9d6dddccc5ad625b2ca6d20",
          "md5": "a401f9f77d0a704ce4d984e923203d04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "f9fa725141a16cb2a189c2835732176a08e014b19203ea8caaefe07fa5466df78fcd7883399fd59576cff726455ac032e6b6befeb51ca765d60b47cc24c30ed5",
          "sha256": "8ff05838fada064738c4d8b083aa1b36fb1dda8bff6be983ab2bec847858aa51",
          "sha1": "f79370ff903b0180d9d6dddccc5ad625b2ca6d20",
          "md5": "a401f9f77d0a704ce4d984e923203d04"
        }
      ]
    }
  ]
}
