{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hicci6e6mnbatnxajb3zug2w7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "23cfae7118893daeb44c7a209614c67a1264d858a2ae617ffd6f922b566a8d594778f5adb0df749799ef16a2f9ce7cbf423c849c70ee9f18e85f34d055c2860a",
          "sha256": "f23d89a2f2094e953b21dd3a84fc5c018cf6031855bae91fff01a3764350a397",
          "sha1": "986d2a87656c88b779fee73c896265ab5a85883b",
          "md5": "daed9c04ad41fc44146ad4d5b35a05a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "23cfae7118893daeb44c7a209614c67a1264d858a2ae617ffd6f922b566a8d594778f5adb0df749799ef16a2f9ce7cbf423c849c70ee9f18e85f34d055c2860a",
          "sha256": "f23d89a2f2094e953b21dd3a84fc5c018cf6031855bae91fff01a3764350a397",
          "sha1": "986d2a87656c88b779fee73c896265ab5a85883b",
          "md5": "daed9c04ad41fc44146ad4d5b35a05a8"
        }
      ]
    }
  ]
}
