{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5ppy2afsurftplp56elvhb4uma"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "39f695e7d927f7dec0686e3ec43fec603d83b89d77187d41e7332ce179ec647ecc78b85478896f20827ff1b17a788fd30ff87e23f3c8404b2eb7f690b39e7ee1",
          "sha256": "d758ac09af57db427d11cdce3e542a64da5c52dea26ac8e93d2443e891ec22a4",
          "sha1": "1081fc6a04d64d20cfcd67cd265aa6e69c2c6eca",
          "md5": "172ea2e116b593f267ffb4d758a6c4e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "39f695e7d927f7dec0686e3ec43fec603d83b89d77187d41e7332ce179ec647ecc78b85478896f20827ff1b17a788fd30ff87e23f3c8404b2eb7f690b39e7ee1",
          "sha256": "d758ac09af57db427d11cdce3e542a64da5c52dea26ac8e93d2443e891ec22a4",
          "sha1": "1081fc6a04d64d20cfcd67cd265aa6e69c2c6eca",
          "md5": "172ea2e116b593f267ffb4d758a6c4e7"
        }
      ]
    }
  ]
}
