{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tavioprourgytfqzcbnqqmdeuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0cefece95c78ffacc27a531b25ff55268da275151d8a7af8f19a8022ac1a3e2ef1f98ea2a5bf99e6195ccf83f49dc1a73f30fcc93e991258e1bffba43e0cc0a5",
          "sha256": "265b25da1a39ac49a6836739bc9e0668d52b5a47b81f2e2382a405dfb593a767",
          "sha1": "954a02f66d39d80661cc9056fa4ad66903d2d508",
          "md5": "c60cf2015bf2bfa2ee458e94e3b52b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0cefece95c78ffacc27a531b25ff55268da275151d8a7af8f19a8022ac1a3e2ef1f98ea2a5bf99e6195ccf83f49dc1a73f30fcc93e991258e1bffba43e0cc0a5",
          "sha256": "265b25da1a39ac49a6836739bc9e0668d52b5a47b81f2e2382a405dfb593a767",
          "sha1": "954a02f66d39d80661cc9056fa4ad66903d2d508",
          "md5": "c60cf2015bf2bfa2ee458e94e3b52b44"
        }
      ]
    }
  ]
}
