{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dduojoxfnzb5li74ou3gg4mzcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0b537e3db22c5bcb932ff196229c049aab89ca06c408e158aeb103c476c0afdc9f06687650fd5dbc467b9705d527c611a0d6c12c85a4181691a59c7e9e01d4cc",
          "sha256": "9ce53a33c9f5c646aeb587a775ea1cbeb9b8f38f5ab5d05a8ca0358f0ec21179",
          "sha1": "3f8ac7daaa1bd6ef8001483a5f6502e5aa271aeb",
          "md5": "d4e759b301739aaa7e34fd6684111974"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0b537e3db22c5bcb932ff196229c049aab89ca06c408e158aeb103c476c0afdc9f06687650fd5dbc467b9705d527c611a0d6c12c85a4181691a59c7e9e01d4cc",
          "sha256": "9ce53a33c9f5c646aeb587a775ea1cbeb9b8f38f5ab5d05a8ca0358f0ec21179",
          "sha1": "3f8ac7daaa1bd6ef8001483a5f6502e5aa271aeb",
          "md5": "d4e759b301739aaa7e34fd6684111974"
        }
      ]
    }
  ]
}
