{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sivb2qegtvd4zomr64qwvu6v7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0725557117ba762ab78eb73874a3c70246e5468b6626c1080786761dd3a9f673088b8d987b86c6d4bcaf65e6462f5f334f37b5f7a6751c088dd3a9b3f1c20a6c",
          "sha256": "efa4918e6a651cd07828f1fd3ec033f59d94285a37deab918d51bc8d65d8b220",
          "sha1": "e817f79aaf5168de58342848c63f4e7f07d059b9",
          "md5": "fe4410af4463c7240e558f7ced7105df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0725557117ba762ab78eb73874a3c70246e5468b6626c1080786761dd3a9f673088b8d987b86c6d4bcaf65e6462f5f334f37b5f7a6751c088dd3a9b3f1c20a6c",
          "sha256": "efa4918e6a651cd07828f1fd3ec033f59d94285a37deab918d51bc8d65d8b220",
          "sha1": "e817f79aaf5168de58342848c63f4e7f07d059b9",
          "md5": "fe4410af4463c7240e558f7ced7105df"
        }
      ]
    }
  ]
}
