{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hwutcwczk5farpgy42pen3pvfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "5dad2b108d1cb5cb3d78edb7d810ad46aecd92786a7d1eff828a21b767433a0dd3e26e9eca8f96cb6e24fbefd938fc4a5b8013419ba5c2584ca3d473709be59c",
          "sha256": "a3d3d4391f1d53508d5eaba1249d11ca3e0c1fbcac68b64407e618a80ff24505",
          "sha1": "3bcbf2d15d899ee6ac0afd5c62410462ff176149",
          "md5": "9e843447ead76be272433716e869bb9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "5dad2b108d1cb5cb3d78edb7d810ad46aecd92786a7d1eff828a21b767433a0dd3e26e9eca8f96cb6e24fbefd938fc4a5b8013419ba5c2584ca3d473709be59c",
          "sha256": "a3d3d4391f1d53508d5eaba1249d11ca3e0c1fbcac68b64407e618a80ff24505",
          "sha1": "3bcbf2d15d899ee6ac0afd5c62410462ff176149",
          "md5": "9e843447ead76be272433716e869bb9e"
        }
      ]
    }
  ]
}
