{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "nmccptubfvaf5dlvyazhtpjxey"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT.klib",
          "size": 8745,
          "sha512": "2c236ee4dbc89f32668fcc194990fb55883764e4da4069396b740bf8dfe783ba569b4359c39fde99727e6de2f1e14be1416cbfbf8dbf005c6ced0035fad706fa",
          "sha256": "dc9102d2d832f6db88c87dab74aff1387fa9aec2dfca344a0afe3f56577fca66",
          "sha1": "b45f24d3aebb27cfd7d057ac676b7deb1273ecb3",
          "md5": "4e9aba5410410a037b02578fd3058744"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5787,
          "sha512": "d49f591918337a3624c22882f4a77de6b818134b58c877a9c25e54a3cbd714b4f2fe4cf77b4855b94d1b8f9b3bfc5afec05c7d0ef0452f6a041a5916fb08f305",
          "sha256": "87f9aa21b5f2a52670ddca26be5fca3aa97c245d33afb2a2e784c56bfe6eb747",
          "sha1": "d61a81544f424f57e52f39078e8f06d033190a05",
          "md5": "18ae17c99130a3b8f636fc1fcb5b3b4a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
