{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT.klib",
          "size": 8969,
          "sha512": "c2cdedfa0c2178f43921678cb2f4c15ad487795f209f7a4203678df319266b5e24213dd9f5fb3a64fd4350143c9fbcce23d912216a80058c5a8078d6b6929015",
          "sha256": "40a8e258e21a12b1f7155a9abb71d8091ecee5f38c203e10af66875597d4cf0b",
          "sha1": "9bd1795efffe5053ee36a87f6993506629027b86",
          "md5": "66707e8d2e200ca3d85db41329ac7cae"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5803,
          "sha512": "ccecef09d3c09fe9f49f40ae641d79d9492158744793efb97d52c93f55301aa769534b0bf232d945c4d2479523d01539004141d862c88b1a5614b0bed467ffd3",
          "sha256": "253e52b3c2fd31f5f134790e07d14e9c02dddb315909d8830e75362b6eb45f9c",
          "sha1": "1d9eae43eb39b337be233333b2ebd087cae186e1",
          "md5": "c3939eed00b6aab20b1d4dfe23fe3f54"
        }
      ]
    }
  ]
}
