{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-SNAPSHOT/coroutine-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT.klib",
          "size": 8969,
          "sha512": "c2cdedfa0c2178f43921678cb2f4c15ad487795f209f7a4203678df319266b5e24213dd9f5fb3a64fd4350143c9fbcce23d912216a80058c5a8078d6b6929015",
          "sha256": "40a8e258e21a12b1f7155a9abb71d8091ecee5f38c203e10af66875597d4cf0b",
          "sha1": "9bd1795efffe5053ee36a87f6993506629027b86",
          "md5": "66707e8d2e200ca3d85db41329ac7cae"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5803,
          "sha512": "79dae8dcfe984bd685d24f266bab116a1b27fa4ee03d3a866b697bc53d784a6593bd3ca3f478ec27844a8da50ab778e9c789dda1ae6f1110bc884ea8be641bc0",
          "sha256": "9dd95b4920827de7504d037d1b589181af296aeffe9618dbf57de38e34a89088",
          "sha1": "94e69e7180430edf7c3d2e83c4e78dbb1efa1a88",
          "md5": "d4225231113d06e85b2d41c9caf42d9c"
        }
      ]
    }
  ]
}
