{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "chuudfukdza3bgyo7pdcmn3rcu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-SNAPSHOT.jar",
          "size": 70015,
          "sha512": "d3f765b4297696637e0990963035ffff3a0e0997699c6df552cf7597ee011740b91b96daf94fbd3da11df3f4c78532ce2c672951cac014c100c03253620dff01",
          "sha256": "14bcdde91be9a73498f2a5a913a29f583e944a7a704ce79e822b6fdaec9e55fd",
          "sha1": "088baeca8e0f2186caabc50f3fbabcaf0ef434a1",
          "md5": "da4fff25662e6dc5154d30be56b7ae07"
        }
      ]
    }
  ]
}
