{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zqhrq36subccfp3wr2z5y3pvaa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-SNAPSHOT.jar",
          "size": 69393,
          "sha512": "3d579043029f2914cb867b5f0a2bf6a415bcde3483f5f656ea0f5a045fa3d22dff679f58a6432a6914ecccde2ee8047737ce9e6fee3aa633ea75f9752208fdaf",
          "sha256": "f51c16b5cab511ae7dbee4dbc9b44a15eb72d4d2d82c65c06103434af47f9d55",
          "sha1": "2400dbe5c1a13cb4a76347f9f93202729cd63ec0",
          "md5": "de3326c6ee786b54bc4c997a1887c067"
        }
      ]
    }
  ]
}
