{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-SNAPSHOT/securestore-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-1.13.2-SNAPSHOT.aar",
          "size": 31890,
          "sha512": "037005a8cb8aaa46d0ab4ad6ee556d9d38db7d4d462629d3c366b68c481b4b7a8212a93b499e9b9b8f2786fe2808b86dc6ab3f21cab725a0caceff1e6288bad4",
          "sha256": "a347d495b00a53d9c11bfe6edca8a07600c492f66988f88083cd38eda3b398ef",
          "sha1": "27ae9a8d21bb06c4f9b8ac168595628a27899623",
          "md5": "a474743d850ece6ee946af98fdca5839"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-1.13.2-SNAPSHOT.aar",
          "size": 31890,
          "sha512": "037005a8cb8aaa46d0ab4ad6ee556d9d38db7d4d462629d3c366b68c481b4b7a8212a93b499e9b9b8f2786fe2808b86dc6ab3f21cab725a0caceff1e6288bad4",
          "sha256": "a347d495b00a53d9c11bfe6edca8a07600c492f66988f88083cd38eda3b398ef",
          "sha1": "27ae9a8d21bb06c4f9b8ac168595628a27899623",
          "md5": "a474743d850ece6ee946af98fdca5839"
        }
      ]
    }
  ]
}
