{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/2977192/test-util-2977192.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "2977192",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "l2dfpflk7bgankgfihmc46sw24"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-2977192.klib",
          "size": 12265,
          "sha512": "0a688b7be1907e328a162c8c5d46e588d908ff60df60dbb2ef26b647368deab8f223c70ee3f55c1ffdea7238e8a218229f123666db1969bd442df216922c8c0c",
          "sha256": "75a7c355ce3e4a10628a10f0b227009d1799be49ce7602fd99b315d64f516e5f",
          "sha1": "6c20284cac99fa4944e1f22743fa2b4c1759a80b",
          "md5": "1e7072434d5525e5fc6780affe2dca2f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/2977192/test-util-metadata-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "2977192"
      }
    }
  ]
}
