{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ixhlacwh6feslddfidqpqtt5oy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.5.0-SNAPSHOT.jar",
          "url": "fhir-java-1.5.0-SNAPSHOT.jar",
          "size": 1000227,
          "sha512": "6aadda6576d5f029fede2844d2a2d58d6674dca013e773c29044a95c1131045260a3941b351b7ec7ce966678897bd9d4f0d7f6cce369e69d2f469a9f648b6a28",
          "sha256": "2beabe6c4d672cd4a4917a34503ba245c8ee4787659c87210a5f14c14be5436b",
          "sha1": "a85a081520775f37e0f1e41c996ba1a017e5edab",
          "md5": "adcfb0f9e1bbfab8a35869f2ed0be2eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.5.0-SNAPSHOT.jar",
          "url": "fhir-java-1.5.0-SNAPSHOT.jar",
          "size": 1000227,
          "sha512": "6aadda6576d5f029fede2844d2a2d58d6674dca013e773c29044a95c1131045260a3941b351b7ec7ce966678897bd9d4f0d7f6cce369e69d2f469a9f648b6a28",
          "sha256": "2beabe6c4d672cd4a4917a34503ba245c8ee4787659c87210a5f14c14be5436b",
          "sha1": "a85a081520775f37e0f1e41c996ba1a017e5edab",
          "md5": "adcfb0f9e1bbfab8a35869f2ed0be2eb"
        }
      ]
    }
  ]
}
