{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4mocntodfvhz3aqs2mt3hmbmjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.5.0-SNAPSHOT.jar",
          "url": "fhir-java-1.5.0-SNAPSHOT.jar",
          "size": 1000227,
          "sha512": "84bafda456c0ba84b7e7e5e6dba8e70be8fcf035080f7aa773f620bc26ee27067a90d83247f2084571656423ae4f7d6e538ecab19605c1ec02a64046124ea22e",
          "sha256": "f92ebb0801ff831043e6dddd38492f5066cab59874fb26dd7945262bd6f7f68c",
          "sha1": "4b752ae3ead17427b7f344227893ff146d7a78d9",
          "md5": "1f3bd3957438df94d61aa6dcb74da645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.5.0-SNAPSHOT.jar",
          "url": "fhir-java-1.5.0-SNAPSHOT.jar",
          "size": 1000227,
          "sha512": "84bafda456c0ba84b7e7e5e6dba8e70be8fcf035080f7aa773f620bc26ee27067a90d83247f2084571656423ae4f7d6e538ecab19605c1ec02a64046124ea22e",
          "sha256": "f92ebb0801ff831043e6dddd38492f5066cab59874fb26dd7945262bd6f7f68c",
          "sha1": "4b752ae3ead17427b7f344227893ff146d7a78d9",
          "md5": "1f3bd3957438df94d61aa6dcb74da645"
        }
      ]
    }
  ]
}
