{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth/1.13.2-SNAPSHOT/auth-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "4wfpoyhh5reijnmbrphjd7oqxa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "size": 34648,
          "sha512": "105b228090ee863247b9f1f898be1318022bc2e89dd7db255669deceb41069e3ff39b2650ad4eba5255859ed9f43100f6ed4ba1f81510ba7842181391968b4b7",
          "sha256": "e19441e6103dcd7b88e5f970681f8d8ba50b1dc7aec856275130af14d0d71a73",
          "sha1": "60827db47ef7cc62f7352ddb51ac9bf830537053",
          "md5": "20ee6fe418dca80418ca1f415e50c537"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-SNAPSHOT.jar",
          "size": 34648,
          "sha512": "105b228090ee863247b9f1f898be1318022bc2e89dd7db255669deceb41069e3ff39b2650ad4eba5255859ed9f43100f6ed4ba1f81510ba7842181391968b4b7",
          "sha256": "e19441e6103dcd7b88e5f970681f8d8ba50b1dc7aec856275130af14d0d71a73",
          "sha1": "60827db47ef7cc62f7352ddb51ac9bf830537053",
          "md5": "20ee6fe418dca80418ca1f415e50c537"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../auth-metadata/1.13.2-SNAPSHOT/auth-metadata-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-metadata",
        "version": "1.13.2-SNAPSHOT"
      }
    }
  ]
}
