{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-SNAPSHOT/util-ktor-test-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "esrb7lawqzfnpgnbkhf22vkz64"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test.klib",
          "url": "util-ktor-test-iosx64-1.9.0-SNAPSHOT.klib",
          "size": 14816,
          "sha512": "078271d7c32c8e026f9f68604b54c8678bb0f5fdbb5d6839045dbca0d200f917a92186d0eb6984a128d62be3fa4a3ea5c1aa5b88d479c3b1681760a5f4c9a155",
          "sha256": "9a948489ff1e28f44b77344cbec3583cf9d91a43f986c57b6c583c06f97f0646",
          "sha1": "cdad289430929924fa9b9059588bc287dde17ceb",
          "md5": "893fd488e4c8b0cdc9e97706acc1a9c2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-SNAPSHOT/util-ktor-test-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
