{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.4.0-SNAPSHOT/test-util-coroutine-0.4.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.4.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.4.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "574566a138ff6f445dbbc491955562251fb8d3dc62b663f5e514b1faf0e3a2acf76484e6ad33ea33ef5ac5acf237902cdfba558f186a1cfa6dc74ce31023acac",
          "sha256": "5f34e30b6b6fb393e5817b55795c305dafccda80d188b5be637c9401bb459228",
          "sha1": "33ac67040cffba74ffcd662ece968a78769912c6",
          "md5": "c11986879d660a60dd0455b90a66d8ff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.4.0-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.4.0-SNAPSHOT.jar",
          "size": 6100,
          "sha512": "574566a138ff6f445dbbc491955562251fb8d3dc62b663f5e514b1faf0e3a2acf76484e6ad33ea33ef5ac5acf237902cdfba558f186a1cfa6dc74ce31023acac",
          "sha256": "5f34e30b6b6fb393e5817b55795c305dafccda80d188b5be637c9401bb459228",
          "sha1": "33ac67040cffba74ffcd662ece968a78769912c6",
          "md5": "c11986879d660a60dd0455b90a66d8ff"
        }
      ]
    }
  ]
}
