{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-SNAPSHOT/util-jvm-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5iasa5iuhjg7bela42sx2nlvzi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "bd730bb80dc80541ced66ffb1cc195af5df659f45600e0c7ef07173163ece43905f14a370b6be40215ff721499cefa82b2333a17a5987d7acaae1357088db227",
          "sha256": "a960ea9dbd8749ad57396ed5c6f2f10cf7ac53ab3e79c8ca27d70459c55c7910",
          "sha1": "75f761d9e5021f55e9ea3a3e93103438fd326c4b",
          "md5": "ce2787806b62d822f25b73de1faf9dbe"
        }
      ]
    }
  ]
}
