{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.9.0-SNAPSHOT/util-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "lqlwzev7w5cfzhdaibshlhmq64"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-metadata-1.9.0-SNAPSHOT.jar",
          "size": 4934,
          "sha512": "0d3a36847f3d3efe056c7a252fddefe1b0c026b140b3d7332f8ad1f678ebf60a28d74efdb58bc03d516cc70a6ff9c24fa0d7afac09b3ff11b3dacc2a9322066a",
          "sha256": "fbf307f415ca01fc2eeb3574be1fec188a253986fbc1150f112348eae124fba9",
          "sha1": "ceb1b675b82c53ccf0f14d490139764794671b06",
          "md5": "938a885cf63979b4cf5ffc0bcb02f223"
        }
      ]
    }
  ]
}
