{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.9.0-SNAPSHOT/util-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6z4fkle5wnaqjjlveuh7aydgvu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-metadata-1.9.0-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "f3b215212a859b916e6a87def146c7dc9c887d8436f185b99f45e521ee619b0e2a41c4bc343d57d17558cdc61db3bc4bbcafba455e7884f2deca38dd5fa82ce0",
          "sha256": "7a86e5b83d69b9436c8f0452add2490fb31d6d64033dc0bb5ee5d61b6000171d",
          "sha1": "dd2090309b091f3c170d91f43ead413f368ca61e",
          "md5": "6005ae820e287fb5bb7e6bd7ec4fe78b"
        }
      ]
    }
  ]
}
