{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.9.0-SNAPSHOT/util-jvm-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hyncfjmu6zeuxl3ohgu2ifc2m4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.9.0-SNAPSHOT.jar",
          "url": "util-metadata-1.9.0-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "9e27a2c06a18f5f4064939fba947f43376eed3fd30b003c84a0d64b8aba3f3791d19d048985af2f84f77d01554949347d882e1f2b96b744c25c63cad66e67a6a",
          "sha256": "224d7438d4d56f1f4e0f40f369951e6f396a1b7b37e6124ea88d0e78fe28bab4",
          "sha1": "003838e3099cb9e093895aa49876bbf4db118295",
          "md5": "8ec320371241fd0998403d632accecd1"
        }
      ]
    }
  ]
}
