{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.8.0-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "5cf1ea46374122e8c6c0cf3069ff95e4ab537713c7e8a363f6b7d4d735e721d20fe0240db747965cef25453953e35239a75dc48be066eb42dee3c25fdf747609",
          "sha256": "43fb9e821a63e2f721a556ebfd72c79358ec143883529c62bc1bbc44ef4a7227",
          "sha1": "698198c8709947b3357dad16e704b86becc0898f",
          "md5": "ec4cc0243c19771e3451908363fed8c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.8.0-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "5cf1ea46374122e8c6c0cf3069ff95e4ab537713c7e8a363f6b7d4d735e721d20fe0240db747965cef25453953e35239a75dc48be066eb42dee3c25fdf747609",
          "sha256": "43fb9e821a63e2f721a556ebfd72c79358ec143883529c62bc1bbc44ef4a7227",
          "sha1": "698198c8709947b3357dad16e704b86becc0898f",
          "md5": "ec4cc0243c19771e3451908363fed8c3"
        }
      ]
    }
  ]
}
