{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.8.0-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "5fa2fa78b0206156bf3d7e846e6502f7c40b4688c1109c6fbe4867ab9613ee03317bfa767e64e22aeb2b87d1f3df6a428b4c371c687f289b89ebd26e28bc57be",
          "sha256": "11363af3651ca099053b20b7965f16d5bc416a3168594a823654e385b27b244a",
          "sha1": "cd7e2e7cd11f894cb63a41f3e844972075e86511",
          "md5": "37dbf27f4ebf11a0be8ff620fa1069ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.8.0-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "5fa2fa78b0206156bf3d7e846e6502f7c40b4688c1109c6fbe4867ab9613ee03317bfa767e64e22aeb2b87d1f3df6a428b4c371c687f289b89ebd26e28bc57be",
          "sha256": "11363af3651ca099053b20b7965f16d5bc416a3168594a823654e385b27b244a",
          "sha1": "cd7e2e7cd11f894cb63a41f3e844972075e86511",
          "md5": "37dbf27f4ebf11a0be8ff620fa1069ff"
        }
      ]
    }
  ]
}
