{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "62tcw5jpwfcwnpjv4av3rl2n2m"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosarm64-0.1.0-SNAPSHOT.klib",
          "size": 1348548,
          "sha512": "e668f1da748ecc81a91016c9b416be0597947fb3dbdcbbfd7e69c860d171e17c9243128fe30c8360abcc01997aba1eb6b50f3bbbe77c9fbec3b00bb53340459a",
          "sha256": "f49e6023180d82ec14b86627d6ef526cb60d9f29e6341bed6e72956aa433fe55",
          "sha1": "fde6a4e172cb4b92fdc2c89a06b2955af971d01a",
          "md5": "0b646a9ef33c54bb10b0e2b8f503d126"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
