{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ux34cjpuhva2jcru4dr542zoqi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 2440732,
          "sha512": "ead7baad88cb691549353eb0e31da335a7e6d66ae3c1a4e4a8632f69eee85e63a8a7a458054971ebb3e099de63450f212452e24b8c9abfb336c18672482f9f33",
          "sha256": "f647f079fb4b17119195dfa9c3f565a11990a1ec0e824cf2c7624ea1b5e11212",
          "sha1": "da03fd22c561db94d1fbefcc08e47c48a7717e33",
          "md5": "0370febad2952081c37e0beac6ebb5ae"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 2440732,
          "sha512": "ead7baad88cb691549353eb0e31da335a7e6d66ae3c1a4e4a8632f69eee85e63a8a7a458054971ebb3e099de63450f212452e24b8c9abfb336c18672482f9f33",
          "sha256": "f647f079fb4b17119195dfa9c3f565a11990a1ec0e824cf2c7624ea1b5e11212",
          "sha1": "da03fd22c561db94d1fbefcc08e47c48a7717e33",
          "md5": "0370febad2952081c37e0beac6ebb5ae"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
