{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "s2ui67sngbe6faa7l4ww6y5mlm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 2440732,
          "sha512": "198f64d3c7f21d48e23356c79f62342e1ba966d2410a927612169b1e49749395481bf95f6e546624263ad77e6b7f858ed1aa1532eb1acb9190d3e263288a17b6",
          "sha256": "5d3e57b13e40a77c4e64bbac74880de177dc0060f2a710032c07ad48c164ea49",
          "sha1": "e6a6bc9d1029f1a2bab6fdf2ea6e29c48fc437e3",
          "md5": "bf42b26c41ab7a6ca0d4e3c4bf484b1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 2440732,
          "sha512": "198f64d3c7f21d48e23356c79f62342e1ba966d2410a927612169b1e49749395481bf95f6e546624263ad77e6b7f858ed1aa1532eb1acb9190d3e263288a17b6",
          "sha256": "5d3e57b13e40a77c4e64bbac74880de177dc0060f2a710032c07ad48c164ea49",
          "sha1": "e6a6bc9d1029f1a2bab6fdf2ea6e29c48fc437e3",
          "md5": "bf42b26c41ab7a6ca0d4e3c4bf484b1f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
