{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-SNAPSHOT/fhir-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mqtu7n5lgnaq7i2twugwuqnhsu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 4367748,
          "sha512": "70920a59561344a04b40d5d6462c05c3566814113fbf9618da5fc250ce154e72d8f74ad4ee744fca54d479c6d8ff9fe013efaa08fbaa362f2b9713d2615d4094",
          "sha256": "22ea0f9b1b74717a2c19d4ac0430776350ee8e45323ab6a24e3c7dfbd60d0fc3",
          "sha1": "831398139b34b32e5e2e4f13e51fde4d8f3ffb21",
          "md5": "916b84011d331ca86ac1996bd259f76e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-SNAPSHOT.jar",
          "size": 4367748,
          "sha512": "70920a59561344a04b40d5d6462c05c3566814113fbf9618da5fc250ce154e72d8f74ad4ee744fca54d479c6d8ff9fe013efaa08fbaa362f2b9713d2615d4094",
          "sha256": "22ea0f9b1b74717a2c19d4ac0430776350ee8e45323ab6a24e3c7dfbd60d0fc3",
          "sha1": "831398139b34b32e5e2e4f13e51fde4d8f3ffb21",
          "md5": "916b84011d331ca86ac1996bd259f76e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-SNAPSHOT/fhir-metadata-0.1.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
