{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-SNAPSHOT/test-util-ktor-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "spphud3arfeypnlnwvilthgfrq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-util-ktor-release.aar",
          "url": "test-util-ktor-android-0.2.0-SNAPSHOT.aar",
          "size": 25431,
          "sha512": "6e34dabd95034de6a492740deaeff04b4239d2663a1f25eb034d947477d4f8d7a1554db76ea5a660f835cd2b4eb1585315f3d612c68ed424dd7f69ebac5bc328",
          "sha256": "f63dae71c3760202927516a87f2bdb8e3024db6f5ffafa885038c264cf35abe9",
          "sha1": "470a027471581c4e0a1f7b99f58ee2404310f7c3",
          "md5": "62a0f445223e841a7cfc20af87091a98"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-release.aar",
          "url": "test-util-ktor-android-0.2.0-SNAPSHOT.aar",
          "size": 25431,
          "sha512": "6e34dabd95034de6a492740deaeff04b4239d2663a1f25eb034d947477d4f8d7a1554db76ea5a660f835cd2b4eb1585315f3d612c68ed424dd7f69ebac5bc328",
          "sha256": "f63dae71c3760202927516a87f2bdb8e3024db6f5ffafa885038c264cf35abe9",
          "sha1": "470a027471581c4e0a1f7b99f58ee2404310f7c3",
          "md5": "62a0f445223e841a7cfc20af87091a98"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.2.0-SNAPSHOT/test-util-ktor-metadata-0.2.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.2.0-SNAPSHOT"
      }
    }
  ]
}
