{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-SNAPSHOT/example-kmp-library-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "yfetf67ltra6lbtwz4p3ohm6zi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 5810,
          "sha512": "577f93786e6b243bf36205dcf30d8227806b945afb60f6549706418be1c0e72fd9623d0dcc757c7208e926fbde9575269fe0f3e17de4bad15da61481538f84fc",
          "sha256": "77d983c2222f3552fb87594254dac547867a525b1f09d5d9457556a70ef4a3bb",
          "sha1": "36fef5329bfa06ada66dbd1bd7c52e41ffbe9e22",
          "md5": "844934b47b5114d433c73adba5124f0b"
        }
      ]
    }
  ]
}
