{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-SNAPSHOT/example-kmp-library-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "f3qhtsysgbb6roioxpnpnalh7u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "388d7c3f44894e1fad3583e5a754e861dc40813f16b71e392b6e92c1ea5bb8d973bef1e949dd1b395690b718bcb550744369a14add3365aac1b485fc1674ab98",
          "sha256": "ac5b99fc8be3f359fbe8e90eaabd071085beebd0e16644040cb54b59051ed1ed",
          "sha1": "0026a717277f4ce550b4deb3968c0fe10a310686",
          "md5": "533ce8b55713e30e22ba7928c64257d8"
        }
      ]
    }
  ]
}
