{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-SNAPSHOT/example-kmp-library-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bqk6vzudjrhuzk3twx7xlzfexi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "d791c357224e84e942d97b9285285ea4cdb517295b6dfd54a8cc2f3972c3c828c16cd134b4282957fcd5dd30626db64b14eac347a2c4a57d9291803309f4a703",
          "sha256": "8f44963bb8ec262287ca123d45adb3f69ad4c6799f03ce1c02c0f1edd4dbcc66",
          "sha1": "022e8b91022fd24c8d7c0c653833a6674279af4a",
          "md5": "78134ecd1b3f8bf00515cb2875c15ca7"
        }
      ]
    }
  ]
}
