{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-SNAPSHOT/example-kmp-library-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ydycfp4rxrd5npxgh2at3rfrcy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "b93692a74ef6a9a7c0188a26148e963c6ffde7eeaefd2f6faedccd1788e09b9f68e0f73ab17214ccf33976c5e7ede281cf22af1cddd554465bf3823f6376ee00",
          "sha256": "b72ac62cf86677e48918d0beddb83e0fac11bbbad4682fc8ff4ce8b778fa79a5",
          "sha1": "4e45d4245ae519b12a231da1cde8d26b01c8c87a",
          "md5": "3e6949884c0986687d378765fffdfb63"
        }
      ]
    }
  ]
}
