{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.4.1-SNAPSHOT/test-util-ktor-0.4.1-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "test-util-ktor-debug.aar",
          "url": "test-util-ktor-android-debug-0.4.1-SNAPSHOT.aar",
          "size": 26687,
          "sha512": "77359aed762e0267187d58533e5dbec481a9468ec1249784c778f7bc3874bb574607b34b538133f177480d36250887ba2a94ef843015becd88ea2d8d139b3cf7",
          "sha256": "c8d673a2166e91744947b669bbaa4f5450070ce056fcce25a802fbfb629d4deb",
          "sha1": "69d09e1e51bc165901223710c698cc328af0e3e9",
          "md5": "75022c4d603f401eca10045bc34ac75a"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-debug.aar",
          "url": "test-util-ktor-android-debug-0.4.1-SNAPSHOT.aar",
          "size": 26687,
          "sha512": "77359aed762e0267187d58533e5dbec481a9468ec1249784c778f7bc3874bb574607b34b538133f177480d36250887ba2a94ef843015becd88ea2d8d139b3cf7",
          "sha256": "c8d673a2166e91744947b669bbaa4f5450070ce056fcce25a802fbfb629d4deb",
          "sha1": "69d09e1e51bc165901223710c698cc328af0e3e9",
          "md5": "75022c4d603f401eca10045bc34ac75a"
        }
      ]
    }
  ]
}
