{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/2977192/test-util-coroutine-2977192.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "2977192",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "l2dfpflk7bgankgfihmc46sw24"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-2977192.jar",
          "url": "test-util-coroutine-jvm-2977192.jar",
          "size": 5987,
          "sha512": "9ebd9f747dbefdf205a36e23d419c992e389949731a27d78d0c2f45ca7d4938ed731c819e0e5a538fa59026a0f769158f60c71370d48603cf2f067f8a1adbe6a",
          "sha256": "65891c230f2563c37f0a34a2b7155c7874ecc991935a9666a268d6197d444a4b",
          "sha1": "f5acd29fe48b915801785817d693d6e6bda1cd19",
          "md5": "47114b8710a01e46ec20705a08176573"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-2977192.jar",
          "url": "test-util-coroutine-jvm-2977192.jar",
          "size": 5987,
          "sha512": "9ebd9f747dbefdf205a36e23d419c992e389949731a27d78d0c2f45ca7d4938ed731c819e0e5a538fa59026a0f769158f60c71370d48603cf2f067f8a1adbe6a",
          "sha256": "65891c230f2563c37f0a34a2b7155c7874ecc991935a9666a268d6197d444a4b",
          "sha1": "f5acd29fe48b915801785817d693d6e6bda1cd19",
          "md5": "47114b8710a01e46ec20705a08176573"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/2977192/test-util-coroutine-metadata-2977192.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "2977192"
      }
    }
  ]
}
