{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n22qhycvnzei5em23mfhcjeuwu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-SNAPSHOT.jar",
          "size": 39147,
          "sha512": "42a463e8672157ce0c26e264a34cc98138ade3438864d719634f86e4f729f23d32a793bc9cdac707ef608b9bca99badd76ae480eeee3873b4969500e06f55b67",
          "sha256": "5de20d584580f72aef66fa44611c533384bc369bfc58c7740278abdcc0ca193c",
          "sha1": "604144ad2e9b79357d7c902212260e5824fc4965",
          "md5": "12669204d47a153735d011b71b37ca4c"
        }
      ]
    }
  ]
}
