{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2hassco26nbapggiw6qe3wgyfq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-SNAPSHOT.jar",
          "size": 39161,
          "sha512": "cea712a38fa18f001eff03a40050992d4e1b213d643c35fd178393125162f9fa546a6a324361f9a49b3ff84b386568bf51bea5c4f64939807ce9e29954297721",
          "sha256": "b77c195877dd76d926d77da4d6077eea5adab01bb160a27de2c8a57d4ec2770f",
          "sha1": "47152a953cbe0a1f2b04e4f1bb9001d37cfaf653",
          "md5": "b8bdf37b5115f0f2ff3c236eca478403"
        }
      ]
    }
  ]
}
