{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-metadata-0.3.0-SNAPSHOT-all.jar",
          "url": "test-util-0.3.0-SNAPSHOT-all.jar",
          "size": 6415,
          "sha512": "433f6a592bd13f694e6e1e92291de6884802fcb5c2830319deb9b3d434d85e3ae1c75f52e60880e685e458fdfe0125d5d360d7309b3cea24258b5c846690eedd",
          "sha256": "2a81011c7c80a302bbdef1565f6d6427edc2dc0cef0879dbf35ca494c42a2843",
          "sha1": "acd46c4c046bc3a4631cc4b3c2701f6178018789",
          "md5": "6138422cf52801bf840bf02c9a95a7f0"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-0.3.0-SNAPSHOT.jar",
          "url": "test-util-0.3.0-SNAPSHOT.jar",
          "size": 7315,
          "sha512": "ec30e626a61a5da1821cd930055d201c6ab6af32fa012d584f345c2db41999d0df84e6f4fc41dcf9ab5b24c1bcdc73c488dfcd33314d6385b006a13f0f800079",
          "sha256": "bf9ba909780f8a289b1cd1454c2f5f931743f4fccec3e60e98efcbcdcab483f9",
          "sha1": "beb0108a19b9641645b4f98a95cc41a3a77776ae",
          "md5": "186ab1fa76ba78a223dbab379e9c77ee"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android-debug/0.3.0-SNAPSHOT/test-util-android-debug-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android-debug",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android-debug/0.3.0-SNAPSHOT/test-util-android-debug-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android-debug",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android/0.3.0-SNAPSHOT/test-util-android-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-android/0.3.0-SNAPSHOT/test-util-android-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-android",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosarm64/0.3.0-SNAPSHOT/test-util-iosarm64-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosarm64",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosarm64/0.3.0-SNAPSHOT/test-util-iosarm64-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosarm64",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosx64/0.3.0-SNAPSHOT/test-util-iosx64-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosx64",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-iosx64/0.3.0-SNAPSHOT/test-util-iosx64-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-iosx64",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-jvm/0.3.0-SNAPSHOT/test-util-jvm-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-jvm",
        "version": "0.3.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-jvm/0.3.0-SNAPSHOT/test-util-jvm-0.3.0-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-jvm",
        "version": "0.3.0-SNAPSHOT"
      }
    }
  ]
}
