{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.12.0-SNAPSHOT/util-1.12.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.12.0-SNAPSHOT.klib",
          "size": 25769,
          "sha512": "41694487c662f68d2ed6a1d05af4973f225a3d1bf191ef4e78fcb71323d56bfd819fca2b0e78dde008b351ea4e7f5419a11ef550556fa4d202de72727f9e050b",
          "sha256": "cf81e7166b7e7d242eab202bc8b943e2d2b1a975df14932a76afeaf5fe33ebdc",
          "sha1": "5b18856e53efe56b9d849ae0b14e6a85acd91a0e",
          "md5": "be5e0e80abd1e6eab87535cb6e14d8e9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.12.0-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.12.0-SNAPSHOT-metadata.jar",
          "size": 6109,
          "sha512": "5597a84d7a0a24d703d95cd45a41917bfc92c8aaa10420da0753699edcfebddf446e28f68fe20b3dc56db485548742baec7dab734f833067127b8d2439f2ae53",
          "sha256": "f6f841cddccac9c0706fa47b201e874161b8ad4c2f1134b5deefcc7cb83967c1",
          "sha1": "8d02a17e04f7452510206e0bc1d34a77d5e9df55",
          "md5": "61a4067a562ea4d278dcc0b8a966d894"
        }
      ]
    }
  ]
}
