{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.13.0-SNAPSHOT/util-1.13.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.13.0-SNAPSHOT.klib",
          "size": 25769,
          "sha512": "41694487c662f68d2ed6a1d05af4973f225a3d1bf191ef4e78fcb71323d56bfd819fca2b0e78dde008b351ea4e7f5419a11ef550556fa4d202de72727f9e050b",
          "sha256": "cf81e7166b7e7d242eab202bc8b943e2d2b1a975df14932a76afeaf5fe33ebdc",
          "sha1": "5b18856e53efe56b9d849ae0b14e6a85acd91a0e",
          "md5": "be5e0e80abd1e6eab87535cb6e14d8e9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.13.0-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.13.0-SNAPSHOT-metadata.jar",
          "size": 6109,
          "sha512": "2210c52ccc2a3f60a7a5d7b9170bba22e85026e143224e3de4f8c44241c7792638f22d3e0b70143e3ef8ef35f5e9d0bdbff9bfe6a182e16869d53ff039552d0f",
          "sha256": "404701c5ceefe1fd8e2feaf20ddd2ad27a01067d13c39e088bcbbcd8bb036a6a",
          "sha1": "f28535adac4e66d1c1644c1d9d274a80c1d1b916",
          "md5": "f4896c267319f00a2858bcf17b4d6eee"
        }
      ]
    }
  ]
}
