{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-SNAPSHOT/util-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lyzjzny7rvfyfggh2niazgzxai"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-release.aar",
          "url": "util-android-1.7.0-SNAPSHOT.aar",
          "size": 18143,
          "sha512": "dc09f366be568076db33e9ac22660e0dfac3a2a68e28cf84c8d227b57f9daee6e0c9095a76c73cc730c11d34723ed190d13931c947a21f3841a946562106b1b6",
          "sha256": "6e2be5c549af8a05c92c9a0e964f9cc4acf15ce824a3e6a8fb7f4314405632e1",
          "sha1": "310cf42e4cc71819fc6a64258f1a0116e75abb11",
          "md5": "3c20d1e8360cdef6785518f197166016"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-release.aar",
          "url": "util-android-1.7.0-SNAPSHOT.aar",
          "size": 18143,
          "sha512": "dc09f366be568076db33e9ac22660e0dfac3a2a68e28cf84c8d227b57f9daee6e0c9095a76c73cc730c11d34723ed190d13931c947a21f3841a946562106b1b6",
          "sha256": "6e2be5c549af8a05c92c9a0e964f9cc4acf15ce824a3e6a8fb7f4314405632e1",
          "sha1": "310cf42e4cc71819fc6a64258f1a0116e75abb11",
          "md5": "3c20d1e8360cdef6785518f197166016"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-SNAPSHOT/util-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
