{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.13.2-SNAPSHOT.jar",
          "url": "crypto-1.13.2-SNAPSHOT.jar",
          "size": 12470,
          "sha512": "88cf043b1bbdfedc9d90a31e0768213a2100bf042303f84d0efda717a4c42d734d4918c1e3654c6907292610484f6a765fbec51905a8d8b3b3b80aad77cfe933",
          "sha256": "12876afa48ed3211e7eea182bdb39a9eb380bfe1d9a191044c1feaabe667a06b",
          "sha1": "2ec457cbc5a426b8780c393ae2cd0cc22c5dad14",
          "md5": "3625bf79c72e334847a41fabb6d06cec"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.13.2-SNAPSHOT/crypto-android-debug-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.13.2-SNAPSHOT/crypto-android-debug-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.13.2-SNAPSHOT/crypto-android-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.13.2-SNAPSHOT/crypto-android-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.13.2-SNAPSHOT/crypto-jvm-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.13.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.13.2-SNAPSHOT/crypto-jvm-1.13.2-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.13.2-SNAPSHOT"
      }
    }
  ]
}
