{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/.1.10.0-SNAPSHOT/fhir-helper-.1.10.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": ".1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-.1.10.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-.1.10.0-SNAPSHOT.jar",
          "size": 114322,
          "sha512": "747cc4d8f6215d8277b1ee1289f1e72b92fce1ec9c825d1a1a45552ad1d591deb29612e65bb0b52298238af6809e2f961c06c6661e2244ce66e90ad2044a3f5e",
          "sha256": "2ebd7f9bd1f3b67d2768f944bace1e3e368398c8f1d7668f2d16caa3286bf1c2",
          "sha1": "b01a769318ce11aa63d7de4b1f72756ad6b26097",
          "md5": "0f7e2216129504b23c7a35f225d4bf5f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-.1.10.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-.1.10.0-SNAPSHOT.jar",
          "size": 114322,
          "sha512": "747cc4d8f6215d8277b1ee1289f1e72b92fce1ec9c825d1a1a45552ad1d591deb29612e65bb0b52298238af6809e2f961c06c6661e2244ce66e90ad2044a3f5e",
          "sha256": "2ebd7f9bd1f3b67d2768f944bace1e3e368398c8f1d7668f2d16caa3286bf1c2",
          "sha1": "b01a769318ce11aa63d7de4b1f72756ad6b26097",
          "md5": "0f7e2216129504b23c7a35f225d4bf5f"
        }
      ]
    }
  ]
}
