{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-SNAPSHOT/test-util-ktor-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.3.0-SNAPSHOT.jar",
          "size": 28739,
          "sha512": "d73c69bda82f9e5a65ac18af7216c1f573808fe006b610a09a9a3f8368ccc4cf5ed4a6415299896b63cb6f287db123ce6ac995615c61a0d563045f822ff298e3",
          "sha256": "7970bc7914c1eaed716646b6c78f730e3e8f96cf80b5bcdc647a412600d9acef",
          "sha1": "6849888b364e0b81363206c0bdf499fbdc67f0c3",
          "md5": "eaf14443d3ac67e27b18b820c720664f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.3.0-SNAPSHOT.jar",
          "size": 28739,
          "sha512": "d73c69bda82f9e5a65ac18af7216c1f573808fe006b610a09a9a3f8368ccc4cf5ed4a6415299896b63cb6f287db123ce6ac995615c61a0d563045f822ff298e3",
          "sha256": "7970bc7914c1eaed716646b6c78f730e3e8f96cf80b5bcdc647a412600d9acef",
          "sha1": "6849888b364e0b81363206c0bdf499fbdc67f0c3",
          "md5": "eaf14443d3ac67e27b18b820c720664f"
        }
      ]
    }
  ]
}
