{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vvajixiorfeidb7kkvomftshtq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 39147,
          "sha512": "626fe00f3e3552b907725e2bf56906e5eb0411178f8a36a0bde6df59b0cc4c9881ffa4737796d7edff2f478f9320fe2c3a84869eb88fd097b73de94f17941d9f",
          "sha256": "fd1b33ce539cd8be0e9711ca3ec983dbd6baff414767961030acad7abb76fa4e",
          "sha1": "f6dfb54f0160969bffef9cc1831eedd7d0f40c2a",
          "md5": "8877e438679433e4c7a7a329e8671f89"
        }
      ]
    }
  ]
}
