{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fd6n7ao5ejeknjexranhxqtd6u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 33955,
          "sha512": "512a8c512b5809cf1e3b488e8c3ada554cb9f5387d7ecae9bb7b714131f60605022aed90332a395fe43d68d279e322ce3c5eb645a117a8836bc72d7bc9e62786",
          "sha256": "236c77cb5bae3d5cc9ddcd8364e85785664b8ed3879546e8edf172d2984d3a88",
          "sha1": "5966502cd060fc26b5e41e68d62f8ca0fd2ac70c",
          "md5": "712bce784faf38d8abc776641bb804d2"
        }
      ]
    }
  ]
}
