{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fh4vwbxhifg25icnrebqqjeypy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-SNAPSHOT.jar",
          "size": 39786,
          "sha512": "e12bce8e9c69054ed31057d43b14e5972a229fa55c1832a56b63907473facdcc08aceba23da12c69d8ccb67fcb8adc1f1405cd8c6d495116e72ffe9566ccfd0f",
          "sha256": "1edc4349470a93efe723949342ac4b5b94d2ba9bd20087f2354a1075b8e48315",
          "sha1": "188b012e3c1c1ae9a595962e184ded8558ca1786",
          "md5": "a970f438f782bceb6bdc4f9960194924"
        }
      ]
    }
  ]
}
