{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bm5rghhf3jhsjoc52gph46k66a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "1add9aab36952674508e8f38210fb83d0a652137c2eb36f50eab85e7a72a8eefae17f102697414bc8f387ec85ec574b67f6764c30556ebaddd576e6a97b66e22",
          "sha256": "3b6041f856a673e307734adf4a8090c303c9b01628ebd334f5ce9adbc4085e83",
          "sha1": "33247604784fa7170ca455a627faf8c026509cc8",
          "md5": "35b1419be7e7179fc6c43ae01d9d365e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "1add9aab36952674508e8f38210fb83d0a652137c2eb36f50eab85e7a72a8eefae17f102697414bc8f387ec85ec574b67f6764c30556ebaddd576e6a97b66e22",
          "sha256": "3b6041f856a673e307734adf4a8090c303c9b01628ebd334f5ce9adbc4085e83",
          "sha1": "33247604784fa7170ca455a627faf8c026509cc8",
          "md5": "35b1419be7e7179fc6c43ae01d9d365e"
        }
      ]
    }
  ]
}
