{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cpdcf7xp3jhn5edl25yzy765oe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cb7338549cadf123e0fb39e84cf2669e8c7eb4930530f8ac0ebd494851194ca202d0418f07b5f09cc868854a0a9396c2cd334bbb9714a2d004310adcb62a3c19",
          "sha256": "a8d329cccee63e944944e6664b055f738594f48850a2bff3a367deeceb3e4bbd",
          "sha1": "0a239ac4e8893e94acdb251f0fd54cb921ed7a83",
          "md5": "3c0f3388078acaafaa450f60bff2ffda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cb7338549cadf123e0fb39e84cf2669e8c7eb4930530f8ac0ebd494851194ca202d0418f07b5f09cc868854a0a9396c2cd334bbb9714a2d004310adcb62a3c19",
          "sha256": "a8d329cccee63e944944e6664b055f738594f48850a2bff3a367deeceb3e4bbd",
          "sha1": "0a239ac4e8893e94acdb251f0fd54cb921ed7a83",
          "md5": "3c0f3388078acaafaa450f60bff2ffda"
        }
      ]
    }
  ]
}
