{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ex6wcqgazjfklhprdf67prhaoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "0f73d6c9adb523077e02224f26952982407074054656640b6fe58d50f3890848a65fa15b6d648316d9bfc731bf7a6bd1b2181c8bcae6b15e42e474088bb812d0",
          "sha256": "a440a92ce41ee033c2672382abff0a551b0a58fce53c6ab45b7a27462d79fd72",
          "sha1": "50b012a3c988a767544e80ca54a13c6e53036f8a",
          "md5": "86d0eb28e03b6fffbb378bf32a63a1bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "0f73d6c9adb523077e02224f26952982407074054656640b6fe58d50f3890848a65fa15b6d648316d9bfc731bf7a6bd1b2181c8bcae6b15e42e474088bb812d0",
          "sha256": "a440a92ce41ee033c2672382abff0a551b0a58fce53c6ab45b7a27462d79fd72",
          "sha1": "50b012a3c988a767544e80ca54a13c6e53036f8a",
          "md5": "86d0eb28e03b6fffbb378bf32a63a1bd"
        }
      ]
    }
  ]
}
