{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.7.0-SNAPSHOT/util-test-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g4wfrskl5bd47goxnsdrkrp45i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-test-jvm-1.7.0-SNAPSHOT.jar",
          "size": 5724,
          "sha512": "3bf2325972be29a5b8c0515a89990338835b44e6936d456bb683c227a132d230adac5abe9593c8a79ba6fffa630937662ef28b36e63abf9a4797e952600f92e9",
          "sha256": "3a521d9e3820ae431e265c782f610f28f305289f193ad8ff27b13ed13c013f63",
          "sha1": "0681b4989d53587768c4bd8b01ae1e2de6acaa70",
          "md5": "53db8fef9fa9180a04fa14236c454abf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-test-jvm-1.7.0-SNAPSHOT.jar",
          "size": 5724,
          "sha512": "3bf2325972be29a5b8c0515a89990338835b44e6936d456bb683c227a132d230adac5abe9593c8a79ba6fffa630937662ef28b36e63abf9a4797e952600f92e9",
          "sha256": "3a521d9e3820ae431e265c782f610f28f305289f193ad8ff27b13ed13c013f63",
          "sha1": "0681b4989d53587768c4bd8b01ae1e2de6acaa70",
          "md5": "53db8fef9fa9180a04fa14236c454abf"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.7.0-SNAPSHOT/util-test-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
