{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.7.1-SNAPSHOT/fhir-helper-1.7.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "size": 116089,
          "sha512": "ca7d50b3376bbedc2d96ded4654ac1533b59a2840d626baa4ec3daf0f7fcb78d57f82a945c6f6f6f3a7e4bc7e49df0d7494d48c8739296c5d44140ccd98ed718",
          "sha256": "ce6fc84056aa18fc8709ab59d66ce362babca41f6754a187cec5399f69a504eb",
          "sha1": "4f15289174a4c5353f68395ea20e5a463dbc06fb",
          "md5": "53fabdd18e8cb80c6dcc724f963829eb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "size": 116089,
          "sha512": "ca7d50b3376bbedc2d96ded4654ac1533b59a2840d626baa4ec3daf0f7fcb78d57f82a945c6f6f6f3a7e4bc7e49df0d7494d48c8739296c5d44140ccd98ed718",
          "sha256": "ce6fc84056aa18fc8709ab59d66ce362babca41f6754a187cec5399f69a504eb",
          "sha1": "4f15289174a4c5353f68395ea20e5a463dbc06fb",
          "md5": "53fabdd18e8cb80c6dcc724f963829eb"
        }
      ]
    }
  ]
}
