{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.7.0-SNAPSHOT/util-test-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hzxn3drzajamvikzz4sskpovhe"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-test-debug.aar",
          "url": "util-test-android-debug-1.7.0-SNAPSHOT.aar",
          "size": 6219,
          "sha512": "b41bb94d001236fe246ebdb7101dfc73cc60d8e8c9d6746ebbb888552442c2f85874057fafb37fef2b62405e37337a017313b7e7c8f1b1b2122984d07ff4b044",
          "sha256": "e6671ecf9a07caca82bf1afd0117bc887217eac488c6a119dbc6d66d9cf81249",
          "sha1": "6f837716a94c2e207603ee759e462d52f1ba2f87",
          "md5": "4b038bff3d08baf4930a894fe395372b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-debug.aar",
          "url": "util-test-android-debug-1.7.0-SNAPSHOT.aar",
          "size": 6219,
          "sha512": "b41bb94d001236fe246ebdb7101dfc73cc60d8e8c9d6746ebbb888552442c2f85874057fafb37fef2b62405e37337a017313b7e7c8f1b1b2122984d07ff4b044",
          "sha256": "e6671ecf9a07caca82bf1afd0117bc887217eac488c6a119dbc6d66d9cf81249",
          "sha1": "6f837716a94c2e207603ee759e462d52f1ba2f87",
          "md5": "4b038bff3d08baf4930a894fe395372b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.7.0-SNAPSHOT/util-test-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
