{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qy6bekvwcrhspebbvbo5t2mv2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "0aabbc74eddf33c7546839633dc794e9832d52d948c0b64098596cf991e033e7958d7513f6f41ccf457a6c269844d913d0b5c3951d3456136033b59bb579015e",
          "sha256": "f35773f92467c0618fa487606ba5b7f19aad9b411c4c392c839a3974bffa95f6",
          "sha1": "dee381a442471b0ec53c5e9d6ecf7f744061be2e",
          "md5": "75690290204df09e757f1f8c5615842c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "0aabbc74eddf33c7546839633dc794e9832d52d948c0b64098596cf991e033e7958d7513f6f41ccf457a6c269844d913d0b5c3951d3456136033b59bb579015e",
          "sha256": "f35773f92467c0618fa487606ba5b7f19aad9b411c4c392c839a3974bffa95f6",
          "sha1": "dee381a442471b0ec53c5e9d6ecf7f744061be2e",
          "md5": "75690290204df09e757f1f8c5615842c"
        }
      ]
    }
  ]
}
