{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.9.0-SNAPSHOT/util-1.9.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "63qqs5p2h5ehja6n7z7pbn5fru"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-debug.aar",
          "url": "util-android-debug-1.9.0-SNAPSHOT.aar",
          "size": 18453,
          "sha512": "aa66d97b3184cf7a83f326e5887a90273d3a3a6fb29ec7c2e57195a8d424a26f0f6d9acb86fb7ca5f5949f34d5ecb5fcdfd594ae70c9d5399b1226c10db4fa15",
          "sha256": "7398dcc8a9cfe54a7a7c0668c89a0e80fdabc089cbe2aaf489a544a5a6ab81eb",
          "sha1": "035ac9c763923ac92fd76a67bebab6050c634491",
          "md5": "d2258d9d7fd3281dfcf02c93b77648f3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-debug.aar",
          "url": "util-android-debug-1.9.0-SNAPSHOT.aar",
          "size": 18453,
          "sha512": "aa66d97b3184cf7a83f326e5887a90273d3a3a6fb29ec7c2e57195a8d424a26f0f6d9acb86fb7ca5f5949f34d5ecb5fcdfd594ae70c9d5399b1226c10db4fa15",
          "sha256": "7398dcc8a9cfe54a7a7c0668c89a0e80fdabc089cbe2aaf489a544a5a6ab81eb",
          "sha1": "035ac9c763923ac92fd76a67bebab6050c634491",
          "md5": "d2258d9d7fd3281dfcf02c93b77648f3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.9.0-SNAPSHOT/util-metadata-1.9.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.9.0-SNAPSHOT"
      }
    }
  ]
}
