{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-jvm/0.1.0-SNAPSHOT/test-util-jvm-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-jvm",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "uqu5rbeh55dxbdgbgwttrpeoqi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-metadata-0.1.0-SNAPSHOT.jar",
          "url": "test-util-metadata-0.1.0-SNAPSHOT.jar",
          "size": 3389,
          "sha512": "157b2c9f422a0c4d472d1f668d681bac4bcb5713457c4093a1e862f914cceb674c7b786258a972c5e850fb66a96ba88e4e40cbf6c9174399a800d998e10e5881",
          "sha256": "f97fd56464f10cfc4f24a582de2c1aabdb6da4215dab913bee327909c7824786",
          "sha1": "56877c9323ddad8b23031204f8f7b8120023a153",
          "md5": "9798f7dd513e11bf1f4889650bf5dba4"
        }
      ]
    }
  ]
}
