{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.16.0-SNAPSHOT/crypto-1.16.0-SNAPSHOT.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.16.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.16.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.16.0-SNAPSHOT.jar",
          "size": 58650,
          "sha512": "8fe59918c8312031e8eee55a1d4d84eb157b2f2694117ebfa511800836b3677ea127306c7d7b5c7dc112f7814fc41f86c5995d00d77dbaa22804f9de88222847",
          "sha256": "ea400e1fb550433a0d2e1b1de0795a986038fb74f43a9f5a8f107d4248e8bccd",
          "sha1": "302b21b8897382ce6156ad33ec8edca3c533bdd4",
          "md5": "364ecbe486a2eacf5c9047e7d26885f4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.16.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.16.0-SNAPSHOT.jar",
          "size": 58650,
          "sha512": "8fe59918c8312031e8eee55a1d4d84eb157b2f2694117ebfa511800836b3677ea127306c7d7b5c7dc112f7814fc41f86c5995d00d77dbaa22804f9de88222847",
          "sha256": "ea400e1fb550433a0d2e1b1de0795a986038fb74f43a9f5a8f107d4248e8bccd",
          "sha1": "302b21b8897382ce6156ad33ec8edca3c533bdd4",
          "md5": "364ecbe486a2eacf5c9047e7d26885f4"
        }
      ]
    }
  ]
}
